### ISSUE TITLE
Add highway=construction to presets

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/id-tagging-schema#10]
Currently attempting to search for "construction" finds nothing. Existing `highway=construction` are not described properly (though there is a suitable rendering of a line with this tag).

related to  openstreetmap/iD#5599

**Comment by tiptoptom** [comment]
I think this issue can be closed.
https://github.com/openstreetmap/id-tagging-schema/commit/dd1705e5a7b1b3e83fe37eeb1ad91a45605c0d04
