### ISSUE TITLE
Distinguish rooftop solar panels and solar panel canopies

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/id-tagging-schema#101]
The [Solar Panel](https://github.com/openstreetmap/id-tagging-schema/blob/d19ad88393174d771c71184f54b61f7624e958a5/data/presets/power/generator/method/photovoltaic.json) preset should have a field or fields to distinguish a standalone solar panel from a rooftop solar panel (`location=roof`) or a solar panel that doubles as a canopy (`building=roof`), or perhaps there should even be separate presets for those configurations.

There are currently [27,334 solar panels tagged as canopies](https://overpass-turbo.eu/s/11qs) and [30,817 rooftop solar panels](https://overpass-turbo.eu/s/11qt), out of 37,2 313 solar panel ways globally. Each of these solar panels would’ve been tagged manually, because the preset doesn’t offer `building` or `roof`-related fields. Anecdotally, I’ve come across plenty of solar panels that were undertagged so that a data consumer might mistake them for standalone units.

**Comment by quincylvania** [comment]
@1ec5 Good idea, these will make for helpful presets.

iD doesn't currently have a field type where you can select between two tag values with different keys, but if we add that in the future then we could have a field for this.

**Comment by stragu** [comment]
It's great news to have the new rooftop solar preset.

Is there any reason why I can't find it in the presets currently when using iD on openstreetmap.org? I thought it would have made it into version 2.19.6? Or is it because version 3.0.0 of the presets was packaged before commit 21e9158 ?

**Comment by 1ec5** [comment]
Yes, it’s because that commit hasn’t made it into a release of id-tagging-schema yet. After that, iD would need to upgrade and be released, and the iD release would need to be deployed.

**Comment by stragu** [comment]
thanks @1ec5 , I appreciate it :)
