### ISSUE TITLE
Regex for gnis:feature_id allows leading zeros

### ISSUE THREAD

**Issue by watmildon** [openstreetmap/id-tagging-schema#1017]
**Describe the bug**
The regex for the field gnis:feature_id allows leading zeros. Previous imports have incidentally had IDs with leading zeros but that has now been corrected.

**To Reproduce**
1. Create an object with gnis:feature_id=00000123

**Expected behavior**
Warning as this is not proper for a numerical id field.

**Additional context**
I have supplied this suggested PR https://github.com/openstreetmap/id-tagging-schema/pull/1007

**Comment by qugebert** [comment]
Isn't this closed by #1007 ?

**Comment by watmildon** [comment]
It is! Thanks for pointing it out.
