### ISSUE TITLE
add support for fhrs:id

### ISSUE THREAD

**Issue by RedAuburn** [openstreetmap/id-tagging-schema#1022]
### OSM Tag(s)

fhrs:id=*

### How would you like this tag to see supported?

As a Field

### Label

Food Hygiene Rating Scheme ID

### Terms

FHRS ID

### Link to OSM Wiki page

https://wiki.openstreetmap.org/wiki/Key:fhrs:id

### Status of the Tag

In Use

### Usage of the tag

140,523

### Regional Tag?

United Kingdom

### Further Information

moved from https://github.com/openstreetmap/iD/issues/9220

ideally it would open the FHRS link like the wikidata field does.
Link format: https://ratings.food.gov.uk/business/{{FHRS:id}}

**Comment by arrival-spring** [comment]
Fixed in #987
