### ISSUE TITLE
`vending=sweets` preset name misleading

### ISSUE THREAD

**Issue by arch0345** [openstreetmap/id-tagging-schema#1036]
Currently, the preset for `vending=sweets` is named "Snacks Vending Machine". 'Snacks' covers a much broader range than that of what the wiki suggests should be tagged as `vending=sweets`: https://wiki.openstreetmap.org/wiki/Tag:vending%3Dsweets

A new Snack Vending Machine preset that uses [`vending=snacks`](https://taginfo.openstreetmap.org/tags/vending=snacks) could be created (although it doesn't have quite as many uses), while the current preset could be renamed to something like Candy Vending Machine

**Comment by jnicho02** [comment]
FYI 'Candy' is an American term. 'Sweet(s)' is British English
