### ISSUE TITLE
Stop telling users highway=no is "outdated" and prompting them to remove it

### ISSUE THREAD

**Issue by rjw62** [openstreetmap/id-tagging-schema#105]
On encountering an object tagged with highway=no, iD currently tells users that the tag is "outdated" and prompts them to "upgrade" it by removing the tag. I believe this behaviour is incorrect. It is also harmful, in the sense that it can result in the loss of important information from the OSM data. The warning and suggestion to "upgrade" should be removed.

The tag combination highway=no was previously marked in the wiki as "deprecated" referring to its incorrect use in place of access restrictions. However, as explained in the current wiki page at https://wiki.openstreetmap.org/wiki/Tag:highway%3Dno there is a legitimate use of this tag to explicitly mark a way as not being a highway. Without this tag, there is no way to explicitly record this information, and thus differentiate between a way whose highway status hasn't been checked, and a way that has been checked and has been found not to be a highway.

(If the warning and suggestion is kept for some reason, then it still needs amending. "Upgrade" is not an appropriate verb to use, as the tag is being removed not replaced. The highway=no tag certainly shouldn't be silently removed without the user being asked to consider what, if anything, it should be replaced by.)

**Comment by quincylvania** [comment]
Hmm the issue with tags like `highway=no` is that, despite being human-readable, not every data consumer will understand that they specify a negative. It'd theoretically be okay to tag `railway=rail` with `highway=no`, `building=no`, `amenity=no`, `waterway=no`, `leisure=no`, `playground=no`, etc., but this would almost certainly cause problems in some app. In uncertain situations you can always leave info for other mappers in the `note` tag.

That said, iD doesn't necessarily need to offer to remove the tag either. There are only 1500 uses, so it's relatively low impact either way.

**Comment by 10992-osm** [comment]
Is there any update on the implementation of this, given I was (indirectly) directed here by @mxdanger on an [issue on the main iD repo](https://github.com/openstreetmap/iD/issues/8484)?

**Comment by mnalis** [comment]
For parties interested, I've updated [highway=no](https://wiki.openstreetmap.org/wiki/Tag:highway=no) wiki to indicate possible problems with it and update alternate ways of tagging it (like `no:higway=*` etc.).
