### ISSUE TITLE
Translate keys for recycling materials accepted

### ISSUE THREAD

**Issue by AntMadeira** [openstreetmap/id-tagging-schema#106]
Hi there.
I would like to ask for multilingual support for the values in the amenity=recycling + recycling:* tag

BTW, how are the various values fetched? From the wiki, from taginfo or are they just inputted into iD?

Regards.

**Comment by ireun** [comment]
Bump on this! Where are theses strings located on Transifex?

**Comment by tyrasd** [comment]
These strings need to be defined first in the preset as possible "strings", similar to how it was done in the `diet` field:

https://github.com/openstreetmap/id-tagging-schema/blob/v3.1.0/data/fields/diet_multi.json#L17-L27

Afterwards they are automatically added to transifex for translation.

**Comment by AntMadeira** [comment]
And how can that be done? 
Is there a tutorial or help file on how to do that? I wouldn't mind to add those strings if I knew how...


> These strings need to be defined first in the preset as possible "strings", similar to how it was done in the `diet` field:
> 
> https://github.com/openstreetmap/id-tagging-schema/blob/v3.1.0/data/fields/diet_multi.json#L17-L27
> 
> Afterwards they are automatically added to transifex for translation.

**Comment by tyrasd** [comment]
This one is relatively easy: go to the field you want to add the strings for, which would be this one here: https://github.com/openstreetmap/id-tagging-schema/blob/main/data/fields/recycling_accepts.json

Then click on the edit button (looks like a :pencil2: ), and add the strings similar to how it is done in the [example above](https://github.com/openstreetmap/id-tagging-schema/blob/v3.1.0/data/fields/diet_multi.json#L17-L27). You need to change the individual "options", of course: the so part before the `:` is what comes in the OSM tag key after the field's base part (i.e. after `recycling:`), and the part after the `:` is just a textual representation of the respective tag. For example, one line could read like this: `    "glass_bottles": "Glass Bottles",`. When you're done, you can save ("commit") your changes on the bottom of the page, which will then step-by-step guide you through the creation of a new pull request. That's basically it.[^1]


[^1]: If you are a bit more advanced: one additional step is to run the `npm run build` command locally after the field's strings are added, which would then allow transifex to automatically fetch the new translatable strings, but I would consider that as an optional step.

**Comment by tyrasd** [comment]
this was done in #349, thanks @kjonosm!

**Comment by AntMadeira** [comment]
@kjonosm can you please also add plastic, waste, cooking oil, books and electrical_items, which are very common?

https://taginfo.openstreetmap.org/search?q=recycling%3A
