### ISSUE TITLE
Add Preset for `highway=cyclist_waiting_aid`

### ISSUE THREAD

**Issue by tordans** [openstreetmap/id-tagging-schema#1066]
### OSM Tag(s)

highway=cyclist_waiting_aid

### How would you like this tag to see supported?

As a Preset

### Label

Cyclist waiting aid

### Aliases

cyclist footrests, leaning rails, bike rests

### Link to OSM Wiki page

https://wiki.openstreetmap.org/wiki/Tag:highway%3Dcyclist_waiting_aid

### Status of the Tag

Approved

### Usage of the tag

405

### Replaces other Tag?

-

### Regional Tag?

global

### Further Information

[The proposal](https://wiki.openstreetmap.org/wiki/Proposal:Highway%3Dcyclist_waiting_aid) was approved recently. The usage is still low. But at the same time it should be an easy preset that does not get in the way of other presets.

It should be an interesting preset to build due to the number of new and existing sub tags. But I don't see any issues with the subtags, we can use checkboxes and radiobutton for fields for them.

One thing that is missing is a fitting icon.

**Comment by RudyTheDev** [comment]
There is a bug with this version (#1069) when handling `side` and reversing the way it's on. `side` represents the side of the waiting aid from the _cyclist's_ perspective, not from the way's perspective. 

For example, add `highway=cyclist_waiting_aid` + `direction=forward` + `side=right` to a way's node. Then reverse the parent way. Observe that `direction=backward` got swapped correctly, but also `side=left` got swapped, which is now on the incorrect side.
