### ISSUE TITLE
Hashtags entered into the hashtag field get lowercased

### ISSUE THREAD

**Issue by mxmeinhold** [openstreetmap/id-tagging-schema#1080]
### How to reproduce the issue?

1. Write a Camel Case hashtag into the Hashtags entry box (e.g. `#ThisIsATest`)
2. Click outside the Hashtags entry box, and see that the hashtag has been lowercased (e.g. now reading `#thisisatest`)

### Screenshot(s) or anything else?

![A screenshot of the iD editor changeset submission page, with a hashtag reading "thisisatest"](https://github.com/openstreetmap/iD/assets/12436574/0f677f00-3de5-4c75-b1d5-dc21db3a4ddb)

This stands out as an issue for me as I'm used to formatting hashtags elsewhere in camel case, so that they're parsable by screen readers

### Which deployed environments do you see the issue in?

Released version at openstreetmap.org/edit, Development version at ideditor.netlify.app, RapiD version at mapwith.ai/rapid

### What version numbers does this issue effect?

2.27.3, 2.1.1, 2.28.0-dev

### Which browsers are you seeing this problem on?

Chrome

**Comment by tyrasd** [comment]
As the hashtags which are automatically parsed from the changeset comment are stored in a case sensitive manner, tools would have to handle the different casings already. Also, it does not make sense for iD to behave differently depending on in which text field the hashtags are entered IMO. Let's continue with case sensitive hashtags.
