### ISSUE TITLE
New preset: Cycle & Foot Path for Europe

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/id-tagging-schema#109]
We already have Cycle & Foot Path, but for US and UK, where tagging is different.
Please add also a preset for other countries: France, Lithuania, Poland where we use
```
highway=path
foot=designated
bicycle=designated

segregated = yes/no
```

**Comment by tordans** [comment]
This was added in https://github.com/openstreetmap/id-tagging-schema/pull/1384
Please use [the PR preview](https://pr-1384--ideditor-presets-preview.netlify.app/id/dist/#locale=en) to test it out.
