### ISSUE TITLE
Add preset for amenity=dog_toilet

### ISSUE THREAD

**Issue by cnotin** [openstreetmap/id-tagging-schema#1094]
### OSM Tag(s)

amenity=dog_toilet

### How would you like this tag to see supported?

As a Preset

### Label

Dog toilet

### Terms

pee-can, excrete, urinate

### Link to OSM Wiki page

https://wiki.openstreetmap.org/wiki/Tag:amenity%3Ddog_toilet

### Status of the Tag

Approved

### Usage of the tag

1818

### Regional Tag?

global

**Comment by tyrasd** [comment]
> Usage of the tag

the current number is actually "only" slightly above 900 according to [taginfo](https://taginfo.openstreetmap.org/tags/amenity%3Ddog_toilet#overview), but that's still OK to be considered for a dedicated preset. :wink:

**Comment by cnotin** [comment]
I hope its usage will increase once it's available in editors and visible in the map ;) But you have more experience than me!

**Comment by tyrasd** [comment]
Surely, though I'd  also say that these are relatively rare map features in general, at least compared to say `amenity=dog_park`.
