### ISSUE TITLE
Bottle tag on amentiy=drinking_water is unclear

### ISSUE THREAD

**Issue by dreua** [openstreetmap/id-tagging-schema#1101]
I propose to remove the "bottle" tag from id presets until there is a clear definition on the wiki. With it being there and shown as "unknown" for most of the instances it may motivate mappers to add unverifiable data to the map.

https://wiki.openstreetmap.org/wiki/Talk:Key:bottle

https://github.com/openstreetmap/id-tagging-schema/blame/2f24b915dfcb8126ee6dc16c54357f2a84e95fe1/data/presets/amenity/drinking_water.json#L10

Example: https://www.openstreetmap.org/edit?node=11262816779#map=20/50.86717/4.34577

**Comment by tyrasd** [comment]
I've moved the field to the optional `moreFields` section, which means that mappers can still edit/add it if they want, but new users will not be asked to fill it out by default.
