### ISSUE TITLE
Deprecate `outdoor_seating=streetside|street_side` (-> `outdoor_seating=terrace|sidewalk|parklet|...`)

### ISSUE THREAD

**Issue by danieldegroot2** [openstreetmap/id-tagging-schema#1112]
### Deprecated OSM Tag(s)

`outdoor_seating=streetside|street_side`

### Replacement OSM Tag(s)

`outdoor_seating=terrace|sidewalk|parklet|...`

### Link to OSM Wiki page

https://wiki.openstreetmap.org/wiki/Key%3Aoutdoor_seating

### Further Information

Deprecate `outdoor_seating=streetside|street_side` in favour of more specific value.
(though arguably could be located on a 'road lane' or 'parking space', here it may be considered ambiguous.);
I am leaving uncommon values as-is, like `pedestrian_zone`, `street`, etc.
alternatively, deprecate `streetside` to sync with parking value, see #1111.

Deprecation is not documented (yet). I will personally not document it, as I focus on mapping.

**Comment by tyrasd** [comment]
See also https://github.com/ideditor/schema-builder/issues/138 for a possible enhancement to support this kind of deprecation in iD as well.

**Comment by danieldegroot2** [comment]
Closing as redundant for now.
