### ISSUE TITLE
Allow bicycle_parking on lines as described in the wiki

### ISSUE THREAD

**Issue by dreua** [openstreetmap/id-tagging-schema#1114]
According to the wiki it should be allowed to tag a not closed line as bicycle parking. I think this should be reflected here in the tagging schema. Currently it shows up as an issue/warning albeit being explicitly allowed in the wiki page.

Thanks in advance!

https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbicycle_parking

https://github.com/openstreetmap/id-tagging-schema/blame/2f24b915dfcb8126ee6dc16c54357f2a84e95fe1/data/presets/amenity/bicycle_parking.json#L21

**Comment by tyrasd** [comment]
I was curious how many bike parking objects are mapped as a line: [currently](https://dashboard.ohsome.org/#backend=ohsomeApi&groupBy=none&time=2007-10-08T00%3A00%3A00Z%2F2024-02-05T14%3A00Z%2FP1M&measure=count&bboxes=-180%2C-90%2C180%2C90&filter=amenity%3Dbicycle_parking+and+geometry%3Aline), there exist about 2k bicycle parking map features mapped as lines in OSM (out of 95k such features mapped as ways, and 633k features overall).

**Comment by dreua** [comment]
Thanks!

**Comment by danieldegroot2** [comment]
@tyrasd rendering is now broken for closed ways (unless explicitly `area=yes`). They should still show up as areas.
There's probably only a few looping bicycle parkings.

Ex. https://www.openstreetmap.org/way/1146011173 (with bicycle rental node)
![image](https://github.com/openstreetmap/id-tagging-schema/assets/67521919/2466096e-ac3f-4f54-9054-278c5d8b4d81)
