### ISSUE TITLE
Different Presets for Underground and Pillar Hydrant

### ISSUE THREAD

**Issue by qugebert** [openstreetmap/id-tagging-schema#1157]
### OSM Tag(s)

fire_hydrant:type

### How would you like this tag to see supported?

As a Preset

### Label

Pillar Hydrant <-> Underfloor Hydrant

### Link to OSM Wiki page

https://wiki.openstreetmap.org/wiki/Tag:emergency%3Dfire_hydrant#fire_hydrant:type.3D.2A_details

### Status of the Tag

Approved

### Usage of the tag

875k / 820k

### Replaces other Tag?

no

### Regional Tag?

global

### Further Information

The suggestion first came up here a few weeks ago: https://github.com/streetcomplete/StreetComplete/pull/5373#issuecomment-1864784864
The pillar icon might be somehow confusing, if there is only a manhole for mounting a pillar.

```fire_hydrant:type=pillar``` and ```fire_hydrant:type=underground``` are the most common types of fire hydrant, so maybe they can get own presets? 

![grafik](https://github.com/openstreetmap/id-tagging-schema/assets/44033795/b34eeff0-51b2-47f0-b9d8-588cb9ecf12e)
![grafik](https://github.com/openstreetmap/id-tagging-schema/assets/44033795/06a4e421-95bd-4288-b25c-7d515c3e573e)

Idk the exakt english terms, in German we say "Oberflurhydrant" vs "Unterflurhydrant"

**Comment by tyrasd** [comment]
a dedicated icon is available in the latest temaki, see: https://github.com/rapideditor/temaki/pull/91
