### ISSUE TITLE
(Re)add Traffic Calming Islands drawn as separate areas

### ISSUE THREAD

**Issue by RudyTheDev** [openstreetmap/id-tagging-schema#1162]
#1076 appears to have removed the preset for separately-drawn traffic islands. These were de facto drawn as `traffic_calming=island`. I realize this is not correct and half the reason for this was iD's preset. But, currently, 74,772 elements (Overpass) out of 87,814 elements (Taginfo) are on areas/closed ways without a `highway` tag. In other words, 85% of traffic islands are micromapped this way all over the world as separate areas far exceeding being mapped on road ways.

![taa](https://github.com/openstreetmap/id-tagging-schema/assets/3857299/8b56da92-cfb8-42db-b884-80aaa2d30b4c)

This is not technically correct, but the current editor version not only doesn't have a preset anymore, but it makes these appear as untagged lines and furthermore offers a completely wrong "convert to line" upgrade. (While something like `landuse=grass` + `traffic_calming=island` (or even + `area=yes`) doesn't show any warnings.) So, asking to:

* Add Traffic Calming Island preset as `area:highway=traffic_island` valid for areas (as drawn separately from roads)
* Add (default) validation to upgrade `traffic_calming=island` (+ `area=yes`) areas (that don't have `highway`†) to `area:highway=traffic_island` so as to fix the existing cases.

† Note that there are currently 508 _closed_ ways with both `traffic_calming=island` and `highway=*`. These seem to range from tiny roundabouts and footways/pedestrian areas to variously creatively mistagged elements. I guess these should be manually reviewed.

P.S. I should also note that stuff like `traffic_calming=choker` or `traffic_calming=chicane` still offer a separate area preset with `area=yes`, which would then also be wrong for the same reason that the `island` was wrong.

**Comment by tyrasd** [comment]
Hi. Yeah, I must admit that I didn't think about all potential side effects while reviewing #1076.

I agree that your proposed actions are the best way to address this issue.

As a first step, I've added an tag upgrade rule to automatically replace `traffic_calming=island + area=yes` to `area:highway=traffic_island`. This should be available quite soon with the [v6.7.2](https://github.com/openstreetmap/id-tagging-schema/blob/main/CHANGELOG.md#672) patch release. This covers approx. 40k of the 75k cases mentioned above. Unfortunately the remaining cases of `traffic_calming=island` as a closed way need to be handled as a hardcoded exception in iD itself, as the tagging schema has currently no way to filter ways by geometry or closedness status.

A dedicated preset for `area:highway=traffic_island` was also added here, but not included in v6.7.2 quite yet to give translators some time to do their job. Note that there is already a generic preset for `area:highway=*` and it will show `traffic_island` in the Type field.

> [choker and chicane] still offer a separate area preset

Yeah, this was still a bit of a mess. :see_no_evil:  I've now fixed this and changed all traffic calming presets to work like this:

* only vertex geometry is allowed in the "standalone" presets
* a `traffic_calming` field is available on road presets as an optional field to mark a section of road as having the respective traffic calming feature installed on its length.

I think this should be quite close to how the tag is intended to use.

**Comment by tyrasd** [comment]
[12b0528](https://github.com/openstreetmap/iD/commit/12b0528175015d5c8964b1d1db28204016ac7b9c) should resolve the missing piece for this on iD's side. This exception is literally hardcoded for now. Eventually a more flexible way to define tag upgrade rules would be nice to have (https://github.com/ideditor/schema-builder/issues/141).
