### ISSUE TITLE
Include water=oxbow

### ISSUE THREAD

**Issue by fqdb** [openstreetmap/id-tagging-schema#118]
(copied from https://github.com/openstreetmap/iD/issues/8314)
Please consider adding water=oxbow in the preset picker, just like for lake, pond, reservoir etc.

`natural = water`
`water       = oxbow`

https://wiki.openstreetmap.org/wiki/Tag:water%3Doxbow 

![image](https://user-images.githubusercontent.com/2826336/105628226-092e2580-5e3c-11eb-87c4-a02694fe0881.png)

**Comment by quincylvania** [comment]
Interesting, I didn't realize this tag existed. If these are all lakes, wouldn't this make more sense as a subtag like `water=lake` + `lake=oxbow`? In any case, this has lots of usage so supporting it sounds okay.
