### ISSUE TITLE
area:highway=traffic_calming wrongly applied

### ISSUE THREAD

**Issue by AntMadeira** [openstreetmap/id-tagging-schema#1180]
Hi there.
I've noticed that iD started to show a message to correct ` traffic_calming=island + area=yes` with `area:highway=traffic_calming`, but I think it should be correcting these with `area:highway=traffic_island` instead, just like the [wiki](https://wiki.openstreetmap.org/wiki/Tag:traffic_calming%3Disland) states. 
Is it a preset mistake or is it purposely like that?

**Comment by 1ec5** [comment]
Related: #1076 #1162.

**Comment by AntMadeira** [comment]
Thanks, @1ec5. I should have searched better for this issue. I'm glad it's already being addressed.
Regards.

**Comment by tyrasd** [comment]
Oh, this was actually a mistake when configuring the tag upgrade rule. The tag should have been actually `area:highway=traffic_island` (see also the commit description and changelog change in 01e7739976fcf6db8ba9f253ce52e72f0cc4242a)! Sorry for the oversight and thanks for noticing!

**Comment by tyrasd** [comment]
released bugfix as [v6.7.3](https://github.com/openstreetmap/id-tagging-schema/blob/main/CHANGELOG.md#672)
