### ISSUE TITLE
Add support for amenity=swingerclub

### ISSUE THREAD

**Issue by Asteliks** [openstreetmap/id-tagging-schema#1186]
### OSM Tag(s)

amenity=swingerclub

### How would you like this tag to see supported?

As a Preset

### Label

Swingers Club

### Link to OSM Wiki page

https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dswingerclub

### Status of the Tag

In Use

### Usage of the tag

362

**Comment by osmuser63783** [comment]
I can see the PR has been merged, looks like the issue can be closed?

**Comment by Asteliks** [comment]
Yep we can close it
