### ISSUE TITLE
Confusion with Dance School preset

### ISSUE THREAD

**Issue by Hufkratzer** [openstreetmap/id-tagging-schema#1189]
Creating a new object (e.g. a node) and applying the preset for "Dance School" (tag [amenity=dancing_school](https://wiki.openstreetmap.org/wiki/Tag:amenity=dancing_school)) results in
![dance](https://github.com/openstreetmap/id-tagging-schema/assets/5958184/e9f5d423-4531-4c16-91a4-04319acede4a)

So why offer the "Dance School" preset in the first place?
(I am just asking; I have no idea which tagging is "better".)

**Comment by tyrasd** [comment]
that was fixed in 915ed76ac030533c058b8cc84f36ff99616c646f
