### ISSUE TITLE
Show brand field for cinema preset

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/id-tagging-schema#119]
This relates to https://github.com/openstreetmap/iD/issues/5515

By convention iD will show:
* both the "name" and "brand" fields for presets where we may want to lock the "brand" and let the user change the "name", and 
* "name" only for presets where we might want to lock the name

Cinemas are in the first category and should show both "name" and "brand" so users can customize the name field, e.g. "AMC Mountainside 10"

**Comment by tyrasd** [comment]
As far as I can see, the [cinema preset](https://github.com/openstreetmap/id-tagging-schema/blob/v3.1.0/data/presets/amenity/cinema.json#L14) already has the `brand` field (since https://github.com/openstreetmap/iD/commit/5ab713462a755ef69ec616a8f59786f8264c351b). Am I missing something here?

**Comment by bhousel** [comment]
Oh yeah, I think the behavior I described only happens if the field is in `fields` but not in `moreFields`. 
 
But I don't need this anymore, I [added a workaround](https://github.com/osmlab/name-suggestion-index/blame/main/scripts/dist_files.js#L309-L318) in the NSI project to generate the branded presets with the `name` and `brand`/`operator` fields up at the top of the `fields` array.
