### ISSUE TITLE
Add `leisure=bathing_place`

### ISSUE THREAD

**Issue by osmuser63783** [openstreetmap/id-tagging-schema#1217]
### OSM Tag(s)

leisure=bathing_place

### How would you like this tag to see supported?

As a Preset

### Label

Swim spot

### Aliases

Bathing place, bathing spot, swimming spot, wild swimming spot, dip spot

### Link to OSM Wiki page

https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dbathing_place

### Status of the Tag

In Use

### Usage of the tag

1,129

### Replaces other Tag?

No

### Regional Tag?

global

### Further Information

![Böhmerheide_-_Badestelle_Landseite](https://github.com/openstreetmap/id-tagging-schema/assets/127188803/d5f8875e-29c9-4223-97af-de50b35997aa)
([source](https://commons.wikimedia.org/wiki/File:B%C3%B6hmerheide_-_Badestelle_Landseite.jpg))

A bathing place (German: Badestelle, Swedish: badplats) is a designated spot where you can swim or 'bathe'. In Europe these are often signposted by the local authority, as these are the spots where swimming is officially allowed or encouraged, water quality monitored, etc.

The English translation 'bathing place' is a bit awkward but I think the concept of a designated or widely known spot for outdoor swimming is a global one. I have tried to suggest a few synonyms. Maybe 'swim spot' would be most commonly used in American English, but I don't have strong views on which one should be the primary label in iD!

[`leisure=bathing_place`](https://taginfo.openstreetmap.org/tags/leisure=bathing_place#chronology) has existed for many years as a tag, but bathing places have also been mapped using various other tags that don't really fit e.g. `leisure=water_park` and I think that's partly because a preset for `leisure=bathing_place` isn't more widely available.

The tagging scheme does already contain a preset for `leisure=swimming_area`, for areas only. In a recent [community forum discussion](https://community.openstreetmap.org/t/clarification-on-the-mapping-of-bathing-places/105017) it was agreed that `leisure=swimming_area` is for the part of the water that has been roped off or otherwise clearly designated for swimming, whereas a `leisure=bathing_place` doesn't usually have a clearly defined boundary so it will usually be mapped as a node. It's a POI - in some languages, people say the equivalent of "let's meet at the bathing place".

**Comment by tordans** [comment]
I agree. I recently ran into this and had to go on a deep dive into the wiki to find the right tagging for https://www.openstreetmap.org/node/11834195614
