### ISSUE TITLE
Add capacity to the default fields offered for amenity=bench

### ISSUE THREAD

**Issue by maxspicer** [openstreetmap/id-tagging-schema#1221]
The [`amenity=bench` preset](https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/amenity/bench.json) includes [seats ](https://wiki.openstreetmap.org/wiki/Key:seats) in the default fields but does not include [capacity](https://wiki.openstreetmap.org/wiki/Key:capacity). Both of these tags are suggested by https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbench.

`seats` describes the number of separate seats on a bench. Most benches will only have one seat, which could be considered the default value for objects without this tag.

`capacity` describes the number of people who can comfortably sit on a bench. Every bench _could_ have a non-zero capacity recorded and it is not possible to deduce the capacity of a bench without this tag.

There is possibility for confusion between `seats` and `capacity`, with contributors incorrectly using `seats` to describe the capacity of a bench rather than its number of physical seats. The likelihood of this confusion is increased by the `amenity=bench` preset only including the `seats` field. I myself have tagged a reasonably large number of benches incorrectly as a result of this as my editor (iD and OSM Go) only asked me for a value for seats and I assumed this was how I should record the bench's capacity.

I think the preset should be modified to be as follows:

```
    "fields": [
        "backrest",
        "material",
        "capacity",
        "seats",
        "colour"
    ],
```
By including both `capacity` and `seats` next to each other with `capacity` first, I believe contributors are more likely to choose the correct tags.

**Comment by pandadeepimpact** [comment]
I find this rather ambiguous, as it would require a lengthy explanation to differentiate the 2 tags (`seats` and `capacity`). How about introducing a new tag, `armrest`, instead, where one can specify the no. of armrests the bench has?

**Comment by maxspicer** [comment]
https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbench explains these tags and they are already in use.

The page also documents armrest=yes/no. This is separate to capacity and seats. A bench with seats=1 (or no seats tag) and capacity=4 can have armrests=yes ie one at each end.  A bench with seats=4, armrests=yes would have armrests for each seat.

I intend to open another issue to propose adding `armrests` to the default fields as well as this is important accessibility information.

**Comment by maxspicer** [comment]
I've just noticed that if a bench is tagged with `capacity=4`, iD actually says that the tags are outdated and suggests "upgrading" them to change it to `seats=4`. Based on https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbench, I believe this to be an error.

**Comment by bhousel** [comment]
For context, looks like @tordans requested this in 2020:
https://github.com/openstreetmap/iD/issues/7886
https://github.com/openstreetmap/iD/pull/8002
Someone probably changed the wiki if it says something else today.

**Comment by maxspicer** [comment]
The wiki page does not appear to be consistent. https://wiki.openstreetmap.org/wiki/Key:seats still says to use this instead of capacity but https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbench explicitly says to use capacity for this under How To Map.

I don't have strong views on this but would like iD to encourage "the right thing". How should we proceed?

**Comment by maxspicer** [comment]
I have updated the wiki page to make it consistent and remove the stipulation about not using seats for what is in fact its most common usage. This issue can now likely be closed.
