### ISSUE TITLE
Should not recommend adding bicycle=designated for hw=cycleway

### ISSUE THREAD

**Issue by bigon** [openstreetmap/id-tagging-schema#1225]
**Describe the bug**
https://wiki.openstreetmap.org/wiki/Key:cycleway says that `highway=cycleway` implies that bicycle=designated is set.

Today id proposed me to add it nevertheless, that seems redundant?

**To Reproduce**
1. Create a way with:

```
foot=designated
highway=cycleway
oneway=no
```

**Expected behavior**
If `bicycle=designated` is really implied (at least in some country) for `highway=cycleway` it shouldn't be proposed

**Screenshots**
![image](https://github.com/openstreetmap/id-tagging-schema/assets/264358/e5163dbd-9301-4472-9b18-6171026a6578)

**Additional context**
This was mentioned in https://www.openstreetmap.org/changeset/151368889#map=19/50.83891/4.39948

**Comment by bigon** [comment]
Extra reference: https://wiki.openstreetmap.org/wiki/Tag:bicycle%3Ddesignated

**Comment by mikkolukas** [comment]
Yeah, stumbled upon this too. It seems like a stupid recommendation.
Next would be to recommend tagging that cars, buses, trucks, motorcycles etc can drive on normal roads.

**Comment by nickoe** [comment]
Maybe this is similar with the exception made here?
https://github.com/openstreetmap/id-tagging-schema/pull/1058

**Comment by mikkolukas** [comment]
> Maybe this is similar with the exception made here? #1058

In Denmark we most often use `highway=cycleway` + `footway=designated` for combined foot- and bicycle paths.

**Comment by balchen** [comment]
The agreed schema for Norway is `highway=cycleway` + `foot=designated`. The iD preset is continuously introducing non-conforming tags. Not a big issue, but it would be nice to have the preset either changed or replaced for NO.

**Comment by tordans** [comment]
The behavior described here come from the id-tagging-schema repo. We have an issue over there to discuss changing the schema. I will close the issue here to funnel the discussion to that place where the fix needs to happen.
https://github.com/openstreetmap/id-tagging-schema/issues/1411
