### ISSUE TITLE
Allotments preset

### ISSUE THREAD

**Issue by boothym** [openstreetmap/id-tagging-schema#123]
In the UK there's a maproulette task and quarterly project to add allotments from a dataset. However I've noticed a number of users tag an area as individual allotment plots (i.e. allotments=plot) instead of as a larger allotment garden (i.e. landuse=allotments).

I'm guessing this is caused by the former appearing first in iD's preset list when searching.
![Screenshot_2021-01-26 OpenStreetMap](https://user-images.githubusercontent.com/16965772/105923686-9fc53700-6034-11eb-8085-1ad7ebec73da.png)

Generally, if someone is searching for allotments, then they will mean landuse=allotments.

So I propose the allotments=plot is renamed to **Individual Allotment Plot** and landuse=allotments is renamed to **Allotment Gardens**

Also, is it possible for iD's validator to check if a certain tag/value is on an area is contained within a larger area? (i.e. plot inside an allotment)

**Comment by boothym** [comment]
@quincylvania any chance this could be fixed in iD, as I'm still finding allotments=plot being added by editors when clearly they meant to added landuse=allotments.

**Comment by tyrasd** [comment]
@boothym can you please check if this is perhaps an issue in the en-UK translation of the preset strings? Because the preset in the repository is actually titled _"Community Garden Plot"_ (and does not come up in the search when typing in "Allotments"), see: https://github.com/openstreetmap/id-tagging-schema/blob/v3.1.0/data/presets/allotments/plot.json#L17

**Comment by boothym** [comment]
I've changed the en-GB translations on transifex 👍 so hopefully it now puts the landuse first. (when does iD bring in the new translations?)

What comes up for non UK users if they type in "allotment", just the landuse?

**Comment by tyrasd** [comment]
> What comes up for non UK users if they type in "allotment", just the landuse?

Yeah, just the preset for `landuse=allotments` and some by-catch:

<img src="https://user-images.githubusercontent.com/1927298/148367767-8401f5a6-d88d-4490-87fd-ec477a88c1a7.png" width="300px">
