### ISSUE TITLE
Typographical error: reinforced_conrete

### ISSUE THREAD

**Issue by Oivo35** [openstreetmap/id-tagging-schema#1244]
`reinforced_conrete": "Reinforced Concrete",` "

**Comment by Dimitar5555** [comment]
Nice catch! After the PR is merged and released, there should be a mass edit to fix the typo.

https://taginfo.openstreetmap.org/tags/material=reinforced_conrete

**Comment by tordans** [comment]
Thanks for the fix. From https://github.com/openstreetmap/id-tagging-schema/pull/1245#issuecomment-2150676973 : Does someone pick up the task to cleanup those 3k values? Otherwise I think we should add a deprecation rule to start the slow cleanup via iD.

**Comment by Dimitar5555** [comment]
The wrong values have been cleaned up by OSM user mapperrue (see https://www.openstreetmap.org/changeset/153484243 and next/previous changesets).
