### ISSUE TITLE
Add covered=* to man_made=storage_tank

### ISSUE THREAD

**Issue by AntMadeira** [openstreetmap/id-tagging-schema#125]
Hi there.
I would like to suggest adding the option to state that a storage_tank is covered or not.
When mapping, for example:
man_made=storage_tank
content=water

it's always useful to know if it's covered or not.

Regards.

**Comment by tyrasd** [comment]
Hey. Usage of `covered` on storage tanks seems to be relatively low (2.5% currently). I'm also wondering… isn't a not-covered tanks basically just a _reservoir_? Or does `covered=yes` on a storage tank mean that there is an additional roof over of the top of the tank? :thinking:

**Comment by AntMadeira** [comment]
Hi, @tyrasd.

I never had thought about this as in "covered by something else", like a roof or similar. For me, it doesn't matter if an element has a detachable cover or not. If it's covered, it's covered. If someone wants to go into more detail to specify the kind of covering, that's also possible.
A `storage_tank` can be open or closed, which is very important for various reasons (ex: firefighters). Since the most obvious tag to differentiate that is `covered=yes/no`, I always assumed this to be the correct one.
You can even check the approved proposal:
https://wiki.openstreetmap.org/w/index.php?oldid=394118

which states 
> This tag potentially deprecates the following tags: `man_made=reservoir_covered` by `man_made=reservoir` + `covered=yes`


The fact that is not used many times, it's probably due to poorly written/defined wiki and lack of iD and JOSM support.

Regards.

**Comment by tyrasd** [comment]
I found that there was an older issue on the iD repo about the same, which I transferred to this repo now: #344.  Since that one has a bit more discussion, let's continue there.
