### ISSUE TITLE
Don't render `railway=ventilation_shaft` as rails

### ISSUE THREAD

**Issue by Dimitar5555** [openstreetmap/id-tagging-schema#1263]
**Describe the bug**
Features tagged with `railway=ventilation_shaft` and without other "area" tags are rendered as rails.

**To Reproduce**
1. https://www.openstreetmap.org/edit?way=685774055#map=19/40.80283/-73.95643

**Expected behavior**
Render them as areas?

**Screenshots**
![image](https://github.com/openstreetmap/id-tagging-schema/assets/19364673/92bc6be2-3f78-4199-b97e-b8e4362df835)

**Additional context**
It would be nice to have a preset but there is also the competing tag `man_made=venttilation_shaft`...

**Comment by tordans** [comment]
>Features tagged with railway=ventilation_shaft and without other "area" tags are rendered as rails.

I am pretty sure this is something for the iD Repo. @tyrasd can move the issue if that is true.

>Expected behavior
> Render them as areas?

That sounds like the right thing to do IMO.
That is, if we want to create a special rule for a usage of just 1.6k.

>It would be nice to have a preset but there is also the competing tag man_made=ventilation_shaft...

Given just 1.6k usage https://taginfo.openstreetmap.org/search?q=railway%3Dventilation_shaft#tags I don't think this tag is used enough to get it's own preset ATM. We would

https://taginfo.openstreetmap.org/search?q=man_made=ventilation_shaft#tags has 2.2 k usage. Also not a lot and not a big difference. Do we have documentation on which is to be considered preferred? We could create an unsearchable preset for "the other".

**Comment by Dimitar5555** [comment]
Of course we don't have documentation and we don't know which one is preferred...

**Comment by k-yle** [comment]
This is solvable without creating a preset, the tag just needs to be added here:

https://github.com/openstreetmap/iD/blob/49492a0e06aef71f90e96ab3ed50098df0f4ce93/modules/osm/tags.js#L55-L62

Linear features require a slightly different approach, see https://github.com/openstreetmap/iD/pull/9142 which fixed the issue for `railway=platform_edge`
