### ISSUE TITLE
Deprecate `natural=grass` to `landuse=grass` ?

### ISSUE THREAD

**Issue by tordans** [openstreetmap/id-tagging-schema#1269]
### Deprecated OSM Tag(s)

natural=grass

### Replacement OSM Tag(s)

landuse=grass

### Link to OSM Wiki page

https://wiki.openstreetmap.org/w/index.php?title=Tag:natural%3Dgrass

### Further Information

Apparently this is deprecated https://wiki.openstreetmap.org/w/index.php?title=Tag:natural%3Dgrass&diff=2494435&oldid=2470268

The change in the wiki does not link to any reference for this deprecation. _Can someone look for some discussion on this?_

If this is valid, we should also check our presets and update them and add the deprecation.

**Comment by Dimitar5555** [comment]
It seems more like a misspelling of `natural=grassland`.

**Comment by matkoniecz** [comment]
And it was mentioned before it was removed without explanation. I restored earlier page version and mentioned also landuse=grass and surface=grass on it

Now it has

> Please use [natural](https://wiki.openstreetmap.org/wiki/Key:natural)=[grassland](https://wiki.openstreetmap.org/wiki/Tag:natural%3Dgrassland) or [landuse](https://wiki.openstreetmap.org/wiki/Key:landuse)=[grass](https://wiki.openstreetmap.org/wiki/Tag:landuse%3Dgrass) or [surface](https://wiki.openstreetmap.org/wiki/Key:surface)=[grass](https://wiki.openstreetmap.org/wiki/Tag:surface%3Dgrass) when possible.

**Comment by tordans** [comment]
Thanks. I will close this issue without action, then.
