### ISSUE TITLE
text 3832 in transifex = Brake run

### ISSUE THREAD

**Issue by Mahabarata** [openstreetmap/id-tagging-schema#1292]
**Describe the bug**
We have to translate this text "Brake run". This text is used for the preset "roller_coaster=brake_run".

But there is no wiki page for this preset = https://wiki.openstreetmap.org/wiki/Tag:roller_coaster%3Dbrake_run
And no element in the osm database is using this tag = https://taginfo.openstreetmap.org/tags/roller_coaster=brake_run#overview.

I suspect that the good preset should be "roller_coaster:track=brake_run", visible here https://wiki.openstreetmap.org/wiki/Key:roller_coaster:track and here https://taginfo.openstreetmap.org/tags/roller_coaster:track=brake_run#overview

**Comment by tordans** [comment]
@arch0345 you added this tag in https://github.com/openstreetmap/id-tagging-schema/commit/0f157cc98de8425cf6bd553af32491ef4fd030f3 – could you take a look and update the preset?
