### ISSUE TITLE
restobar searchability

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/id-tagging-schema#1305]
I encountered some things that classified themself as "restobar" and had a bit of trouble in classifying/mapping them with iD presets

What would be the best way to handle https://en.wiktionary.org/wiki/restobar ?

Add it as search term to both bar and restaurant?

**Comment by bhousel** [comment]
I’d just tag that as a restaurant.

**Comment by matkoniecz** [comment]
likely yes, but would be nice if someone putting "restobar" into search would get restaurant entry as suggestion (and maybe some other entries?)

**Comment by 1ec5** [comment]
Some possible overlap with the existing Brewpub preset.

**Comment by tordans** [comment]
Given that no one used this value, yet, I don't think it is something we need to promote as a preset or even just a search term, yet.
https://taginfo.openstreetmap.org/keys/amenity#values
There is also no mention in the wiki https://wiki.openstreetmap.org/w/index.php?search=restobar&title=Special%3ASearch&go=Seite

In addition, adding a search term and by that making a tagging decision without any signals from the rest of the community does not conform to [our guidelines](https://github.com/openstreetmap/id-tagging-schema/blob/main/GUIDELINES.md).

I will close this for now. But let's open it again once there is some evidence of the keyword in the wiki.

**Comment by matkoniecz** [comment]
added `{{RelatedTerm|restobar}}` in https://wiki.openstreetmap.org/w/index.php?title=Tag:amenity%3Drestaurant&diff=2742128&oldid=2741646

though I guess that may be enough for now
