### ISSUE TITLE
Describe area:highway=footway area as "footway area", not "road area"

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/id-tagging-schema#131]
See for example https://www.openstreetmap.org/way/300555812

Similar would be useful for `area:highway=cycleway` `area:highway=path`

https://taginfo.openstreetmap.org/keys/area%3Ahighway#values

![screen02](https://user-images.githubusercontent.com/899988/108382712-633ac480-7209-11eb-8eaa-0ffed58affab.png)

**Comment by matkoniecz** [comment]
I am willing to make a pull request implementing it, after https://github.com/openstreetmap/id-tagging-schema/pulls/matkoniecz are processed (note: it far future I may have less time and be unable to do this)

**Comment by matkoniecz** [comment]
Relevant file: https://github.com/openstreetmap/id-tagging-schema/blob/9fdecc983443ce75185c2923caae9f7703f2cae4/data/presets/area/highway.json

From what I see I would need to create a new file for each tag value, see say https://github.com/openstreetmap/id-tagging-schema/blob/9fdecc983443ce75185c2923caae9f7703f2cae4/data/presets/shop/car/second_hand.json

**Comment by tyrasd** [comment]
> I am willing to make a pull request implementing it

:+1: go ahead :blush: 

> From what I see I would need to create a new file for each tag value

In principle yes, but we could start by only adding specialized presets for the "pedestrian/bike" type of pavement areas:

* `area:highway=footway`
* `area:highway=cycleway`
* `area:highway=pedestrian`
* `area:highway=path`

And keep the rest as generic "Road Area"s.

**Comment by matkoniecz** [comment]
@tyrasd Is there some way to preview created changes in a reasonable way? I can try to make them blindly but it seems there should be some better way.

I know about #289 and know that there is no easy way, but is there something at all reasonable?

**Comment by tyrasd** [comment]
> Is there some way to preview created changes in a reasonable way?

Here's what I currently do:
* have [request-interceptor extension](https://addons.mozilla.org/en-US/firefox/addon/request-interceptor/) installed on firefox
* configure the request-interceptor extension to trigger on a test instance of iD (e.g. https://ideditor.netlify.app), and redirect the presets URL (e.g. `https://cdn.jsdelivr.net/npm/@openstreetmap/id-tagging-schema@3/dist/presets.min.json`) to a local dev server URL (e.g. `http://localhost:3000/presets.min.json`)
    ![image](https://user-images.githubusercontent.com/1927298/148265671-6ae3841b-ebde-4741-b87b-6dfeaedc8088.png)
* run `npm run dist` on the id-tagging-schema repo (one might or might not need transifex credentials for this, I don't actually know)
* run a local dev web server on the above mentioned port in the `dist` folder of the id-tagging-schema repo with CORS header active – I use this one: `npx serve --cors`
* now open the test instance of iD and check in the network tab that the redirect actually loaded the presets data from the local server

It really should be easier, though, as proposed in #289.
