### ISSUE TITLE
Adding amenity=funeral_hall from search menu removes building=funeral_hall

### ISSUE THREAD

**Issue by Oivo35** [openstreetmap/id-tagging-schema#1313]
Adding amenity=funeral_hall from search menu removes tag building=funeral_hall.
1. original tag
![1](https://github.com/user-attachments/assets/38c839d9-2aa2-4b25-9e58-041652720d9b)
2. choosing amenity=funeral_hall from menu
![2](https://github.com/user-attachments/assets/af15b89f-7078-4595-8f46-97f19bb369dc)
3. tags after adding amenity=funeral_hall
![3](https://github.com/user-attachments/assets/c33a0215-2069-4ef3-826c-78e2da5eaa6f)

**Comment by tordans** [comment]
@Oivo35 could you please review https://github.com/openstreetmap/id-tagging-schema/pull/1324#issuecomment-2308915096 if that fixes the issue and add some test cases to that PR? That would help a lot.

**Comment by Oivo35** [comment]
@tordans Thanks, now it seems fixed,
