### ISSUE TITLE
Hilti

### ISSUE THREAD

**Issue by Mahabarata** [openstreetmap/id-tagging-schema#1314]
Currently there is a preset for this company :
name=Hilti 
shop=hardware
brand=Hilti
brand:wikidata=Q1361530

the main tag seems wrong, see https://www.hilti.fr/content/hilti/E2/FR/fr/company/corporate-information/company-profile.html.
Or see https://en.wikipedia.org/wiki/Hilti

They don't sell "screws and bolts, nails, hooks and other metal materials as well as metal tools" that we find in a hardware shop (see [Tag:shop%3Dhardware](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dhardware)). They mainly sell electric supplies.

And they don't sell to individuals but to companies (some of these companies are hardwares selling Hilti products therefore individuals can buy Hilti products)

So I will suggest to replace "shop=hardware" by "shop=trade"  + "trade="electric_supply".

Or delete this preset (Hilti looks like [Black&Decker](https://en.wikipedia.org/wiki/Black%2BDecker) company and there is no preset for this company).

Best regards.

**Comment by Oivo35** [comment]
I think better tag for Hilti is [shop=power_tools](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dpower_tools).

**Comment by osmuser63783** [comment]
I think you are looking for https://github.com/osmlab/name-suggestion-index/issues :-)

**Comment by Mahabarata** [comment]
Thanks to [Oivo35](https://github.com/Oivo35) and [osmuser63783](https://github.com/osmuser63783) for their suggestions.
