### ISSUE TITLE
Make fitness station features add only 'fitness_station=*' tag

### ISSUE THREAD

**Issue by andris86** [openstreetmap/id-tagging-schema#1319]
Currently whenever user chooses something that would belong in fitness station, iD editor adds three tags:

- fitness_station=*
- leisure=fitness_station
- sport=fitness

Make this recommendation add only `fitness_station=*` tag as `leisure=fitness_station` may already be mapped as an area, resulting in double-mapped feature.

By '*' I mean any value applicable to 'fitness_station' tag.

**Comment by Hufkratzer** [comment]
Duplicate of #1301
