### ISSUE TITLE
Parking lane and street side should be inverted

### ISSUE THREAD

**Issue by Nekzuris** [openstreetmap/id-tagging-schema#1325]
According to the [wiki](https://wiki.openstreetmap.org/wiki/Tag:parking=lane), you could map the whole city with `parking=lane`, but I'm sure that in most cases, when a mapper wants to add parking, it's probably `parking=street_side`. This is confirmed by [taginfo](https://taginfo.openstreetmap.org/keys/parking#values).

The current drop-down menu looks like this:
![img](https://github.com/user-attachments/assets/536a5f22-48c8-41d7-884c-cf4e6bdacab9)
It's even worse in French because the words are basically synonyms, I can't even tell if the translations are inverted. (I'm French btw)
This has led me and I think many other mappers to favor "lane" instead of "street_side".

Also, not sure if this is intended, but when you select "Street-Side", the Type field disappears.

**Comment by maro-21** [comment]
For sure street_side should be higher in the list because it's one of the most, if not the most, popular type of parking lot.

**Comment by tordans** [comment]
See https://github.com/openstreetmap/id-tagging-schema/pull/1326#issuecomment-2322775871 for further suggestions on how to improve this UI.
