### ISSUE TITLE
Add bicycle traffic counter

### ISSUE THREAD

**Issue by Coehill** [openstreetmap/id-tagging-schema#1331]
### OSM Tag(s)

monitoring:bicycle=yes

### How would you like this tag to see supported?

As a Preset

### Label

Bicycle Counter

### Aliases

Bike Counter

### Link to OSM Wiki page

https://wiki.openstreetmap.org/wiki/Key:monitoring:bicycle

### Status of the Tag

In Use

### Usage of the tag

1763

### Regional Tag?

global

**Comment by habi** [comment]
This was brought up in https://github.com/Zverik/every_door/issues/772, would this work with an extension of https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/man_made/monitoring_station.json?

(I'm interested to have these monitoring stations in Every Door :) )
