### ISSUE TITLE
Remove amenity=garage

### ISSUE THREAD

**Issue by mwild500** [openstreetmap/id-tagging-schema#1342]
Remove tag amenity=garage

**Comment by tordans** [comment]
Please add some details to this issue. Why? Context? Use Case? ...

**Comment by mnalis** [comment]
Well, that tag `amenity=garage` is undocumented and has 0 uses according to https://wiki.openstreetmap.org/wiki/Tag:amenity=garage, so if it existed in repo it should be removed.

There is also deprecated [amenity=garages](https://wiki.openstreetmap.org/wiki/Tag:amenity=garages) which has some hundred or so uses in the OSM database...

That being said, unless I'm missing it, I don't really see that this repo uses either of those keys, so it is unclear what @mwild500 wants (and why)? :man_shrugging:

**Comment by tordans** [comment]
Thanks @mnalis for you comment. Given that and that we already have https://github.com/openstreetmap/id-tagging-schema/blob/e0c7efdb21d641c021fb98bcef08aa909a7afc43/data/deprecated.json#L90-L93 I will close this issue.
