### ISSUE TITLE
Typo: tag support=pedestal and pedestral

### ISSUE THREAD

**Issue by Oivo35** [openstreetmap/id-tagging-schema#1358]
Hi, I think there is a typographical error in the tag support=pedestral. According to British English and [wiki](https://wiki.openstreetmap.org/wiki/Key:support), the correct term should be support=pedestal.
![support](https://github.com/user-attachments/assets/8cb7a6b6-f6f9-4d9d-ace2-a46f255cabe5)

**Comment by riQQ** [comment]
This is actually an error in the OSM data, as the proposed values are taken from there:
https://taginfo.openstreetmap.org/keys/support#values

**Comment by tordans** [comment]
Thanks for bringing this up. This fits well into what I started to clarify in https://github.com/openstreetmap/id-tagging-schema/pull/1357/files
This kind of cleanup is not something this Repo is well suited for. Which is why I will close this here.
