### ISSUE TITLE
Make the preset for `shop=yes` searchable

### ISSUE THREAD

**Issue by Dimitar5555** [openstreetmap/id-tagging-schema#1363]
That preset is very helpful when tagging seemingly closed/vacant shops from street level imagery that is a few years old (so you can't be 100% sure if it's still vacant or it has been occupied). Tagging it as `shop=yes` will trigger the respective quest/alert in StreetComplete/Every Door and local mappers can update it almost instantly. On the other hand if I tag such shops as vacant/disused, mappers will get the quest/alert after at least a few months.

**Comment by Dimitar5555** [comment]
There is no other way to easily tag "There is a shop here but I can't remember/didn't write what type it is". Or when mapping from street level imagery, when you are preparing the area for surveying. In fact, it is a lot easier to see on the app "This building has 3 shops on the front, the middle one is grocery, the other two are vacant" and tag them accordingly instead of wondering how and where exactly to place the nodes.

**Comment by matkoniecz** [comment]
> There is no other way to easily tag "There is a shop here but I can't remember/didn't write what type it is". 

this kind of mapping is possible but it is not worth encouraging it

if someone really wants they can edit raw tags and copy such dubious POI

> In fact, it is a lot easier to see on the app "This building has 3 shops on the front, the middle one is grocery, the other two are vacant"

that assumes that shops stayed at the same locations (I do not want to generalize too much but in my city it is common for shops to take multiple spaces or split again). For example https://www.openstreetmap.org/node/11054103599 took space of two previous businesses.

> instead of wondering how and where exactly to place the nodes.

this is quite easy and simple, as long as buildings are mapped, prepositioning `shop=yes` does not really help here

**Comment by Dimitar5555** [comment]
Both of us are talking from personal experience, which is quite different as it seems.

**Comment by tordans** [comment]
Lets see what others think about this. My take is to error on the side of caution with this and not make the change. It is hard to explain to (new) mappers the general present and the workflow in which it might be sensible to use inside of iD and similar apps.

**Comment by matkoniecz** [comment]
For me argument is that mapping outdated POIs as `shop=yes`  is still entirely possible and it is rather advanced thing, so expecting people to use raw tag box is fine.

While if just 1% of people will enter `shop=yes` instead of a good type, then it is larger loss than all additional `shop=yes` added from outdated Bing Street View.

One possible benefit is that people may add `shop=yes` instead wrong shop type if they will fail to find it but I would not expect it to be common.

**Comment by maro-21** [comment]
But it IS and has been searchable. So this issue is invalid.

What I wanted to propose is to make this preset UNsearchable. Unfortunately it's on the first position when I enter "shop".

**Comment by Dimitar5555** [comment]
I wasn't aware of the fact that there are two presets for it. Closing the issue.
