### ISSUE TITLE
Replace `population:source` with `source:population`

### ISSUE THREAD

**Issue by ForgottenHero** [openstreetmap/id-tagging-schema#1376]
I noticed there are 1,020 uses of `population:source` used in [TagInfo](https://taginfo.openstreetmap.org/keys/population%3Asource#overview).
The correct tag would be [`source:population`](https://taginfo.openstreetmap.org/keys/source:population#overview) as described in the wiki [Key:population](https://wiki.openstreetmap.org/wiki/Key:population).

Could a warning be added to change/update the incorrect tags to use the standard `source` tag prefix instead?

**Comment by tordans** [comment]
Thanks for the suggestion @ForgottenHero. Given the low usage, I thing https://github.com/openstreetmap/id-tagging-schema/pull/1357 applies and this is better suited for other ways of cleanup, don't you think?

**Comment by ForgottenHero** [comment]
You're very right @tordans sorry. I'll close this one and look into one of the alternatives you've got listed there.
