### ISSUE TITLE
Ticket validator icon is confusing

### ISSUE THREAD

**Issue by dokutan** [openstreetmap/id-tagging-schema#1387]
**Describe the bug**
The icon for `amenity=ticket_validator` is the generic vending machine icon (`temaki-vending_machine`). This is confusing, as ticket validators aren't vending machines, but are commonly placed near transit ticket and other (sometimes generic) vending machines.

**To Reproduce**
Place a ticket validator next to a vending machine.

**Expected behavior**
1. Reuse the existing ticket vending machine icon (`temaki-vending_tickets`) for ticket validators, this is not ideal but in my opinion still better than the current icon, or
2. Add a new icon for ticket validators.

**Comment by matkoniecz** [comment]
> Reuse the existing ticket vending machine icon (temaki-vending_tickets) for ticket validators, this is not ideal but in my opinion still better than the current icon, or

would reduce confusion with generic vending machine, increase confusion with machine selling tickets, not sure which is worse

trivial to change - I did it in  change ticket_validator icon to ticket #1388  - you can test it there and follow "Checklist and Test-Documentation Template" to make it more likely to merge

if on testing it is not great idea - please comment there so I can close the PR

**Comment by tordans** [comment]
Closed by https://github.com/openstreetmap/id-tagging-schema/pull/1388
