### ISSUE TITLE
iD suggests pediatrics for healthcare:speciality, but should be paediatrics

### ISSUE THREAD

**Issue by ygra** [openstreetmap/id-tagging-schema#140]
Cf. tag wiki: https://wiki.openstreetmap.org/wiki/Key:healthcare:speciality and taginfo: https://taginfo.openstreetmap.org/keys/healthcare:speciality#values

There's only 19 pediatrics, while > 2000 paediatrics.

**Comment by tyrasd** [comment]
Since the typo comes from existing OSM data (through taginfo's API), there's not much we can do about this. Closing here in favour of #290, which will definitely help mitigate the issue.
