### ISSUE TITLE
pipeline=substation does not guarantee an area?

### ISSUE THREAD

**Issue by cicku** [openstreetmap/id-tagging-schema#148]
I created an area with substation (default select)
![image](https://user-images.githubusercontent.com/686438/110985810-e2b84100-833a-11eb-913d-86ed201d7b3a.png)

Then I changed the tag from
![image](https://user-images.githubusercontent.com/686438/110985855-f2378a00-833a-11eb-9496-ca9e1197f717.png)

to

![image](https://user-images.githubusercontent.com/686438/110985951-1004ef00-833b-11eb-8d88-3e5c8d9f71f3.png)

So unless I specify area=yes, iD will not map it as an area.

**Comment by flacombe** [comment]
I second @cicku comment and confirm both power=substation and pipeline=substation are facilities that are mostly mapped as areas.

Additionally, that shouldn't be necessary to look for power=substation to map a pipeline substation.

@cicku Accordin to aerial picture, you probably can change substation=yes to substation=transmission depending of this particular place's role.

**Comment by tyrasd** [comment]
There simply does not yet exist a preset for `pipieline=substation`. That's why it defaults back to being a basic "line".

**Comment by qugebert** [comment]
Is this already closed with https://github.com/openstreetmap/id-tagging-schema/commits/2f24b915dfcb8126ee6dc16c54357f2a84e95fe1/data/presets/pipeline/substation.json ?

**Comment by qugebert** [comment]
@tyrasd i think this can be closed as completed in #[2f24b91](https://github.com/openstreetmap/id-tagging-schema/commits/2f24b915dfcb8126ee6dc16c54357f2a84e95fe1/data/presets/pipeline/substation.json)
