### ISSUE TITLE
Remove landuse=military from military=barracks

### ISSUE THREAD

**Issue by Fizzie41** [openstreetmap/id-tagging-schema#158]
This was previously raised at https://github.com/openstreetmap/iD/issues/8378 & it was suggested that it be moved here.

As part of the proposal for military=bases https://wiki.openstreetmap.org/wiki/Proposed_features/Military_bases, military=barracks were correctly re-defined as only being the actual buildings that military personnel live in, rather than the area of the whole base.

However, iD still has them with a default of also requiring landuse=military, which then has the effect of landuse=military + military=barracks, being located inside landuse=military + military=base!

So, could the requirement for landuse=military please be removed from military=barracks?

Thanks

**Comment by bhousel** [comment]
`military=barracks` currently requires `landuse=military` and has for as long as I can remember.
I agree it's weird, but it's what the wiki says to do.

<img width="263" alt="Screen Shot 2021-04-11 at 9 12 43 PM" src="https://user-images.githubusercontent.com/38784/114328459-b2ff8300-9b0a-11eb-91e5-3348cdec103c.png">

**Comment by Fizzie41** [comment]
Thanks Bryan. Have asked question on tagging list about removing it.
