### ISSUE TITLE
man_made=planter

### ISSUE THREAD

**Issue by RudyTheDev** [openstreetmap/id-tagging-schema#160]
This request is to add tag `man_made=planter` to represent man-made decorative urban boxes/containers where flowers, decorative shrubs, bushes and/or miniature trees are planted, usually one at a time or mixed, sometimes with other elements. These serve primarily as decoration, but also double as barriers in certain scenarios.

Wiki: https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dplanter

Taginfo: https://taginfo.openstreetmap.org/tags/man_made=planter - 1.6k uses

The name would be "Planter" or "Planter box".

Wiki lists `material=*` as an additional tag, and this seems appropriate. It would generally be easy to identify. (I would argue that something like `height` and `species` stuff would also be appropriate, but this is just personal observation and this hasn't been proposed or seen wider use, as far as I know.)

See also iD repo request https://github.com/openstreetmap/iD/pull/7558

The concern from above request was that this is not distinct to [`landuse=flowerbed`](https://wiki.openstreetmap.org/wiki/Tag:landuse%3Dflowerbed), but I believe these serve mostly different purposes. Flower bed is an area, generally on the earth itself. It's normally a relatively large feature and not elevated. A planter box is specifically an elevated container not in earth and within an otherwise urban environment. (Basically, you can step into flower beds, but you would have to climb onto planters.) These are usually movable, although heavy by design. Most of the time, they are no bigger than a single node unless there is really high resolution aerials. And these support anything from flowers to bushes to small trees. I do believe they are distinct enough. They offer good landmarks as well. They can serve as traffic calmings as well on pedestrian streets.

Here's what they look like (around where I'm at with strong post-USSR influence on these), which makes them quite distinct:

![planter1](https://user-images.githubusercontent.com/3857299/115108401-f0d03180-9f78-11eb-999f-4c3a6a0cc5df.jpg)
![planter2](https://user-images.githubusercontent.com/3857299/115108402-f168c800-9f78-11eb-945d-a659975b722d.jpg)
![planter3](https://user-images.githubusercontent.com/3857299/115108403-f2015e80-9f78-11eb-9b36-e787971886e9.jpg)

**Comment by tordans** [comment]
Hi @RudyTheDev, I like the idea of adding this preset to encourage this kind of micropmapping. It would help me for sure.

A few thinks I am not clear about:

a. Should this preset also deprecate the alternative tags? https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dplanter#Alternative_Tags 
- `man_made=plant_container`
- `man_made=planter_box`
Does this need community discussion or maybe even a deprecation proposal? 
Or, if not, how would the preset "explain" the difference / differentiate itself from those other two?

b. Which attributes should the preset have?
The wiki lists `material=*`. But maybe also some of the "useful combinations from landuse=flowerbed https://wiki.openstreetmap.org/wiki/Tag:landuse%3Dflowerbed like `operator=*` and something about the type of plant like `species:wikidata=<WikiDataID>` https://wiki.openstreetmap.org/wiki/Key:species:wikidata?

b2. The tagging should be allow on point- and area-geometry in iD. (Right?)

c. What about barriers?
IMO those planters are used quite frequently as barriers. How would the preset handle those situations? Eg. a `true/false` checkbox saying "barrier: yes/no" with adds the tag `barrier=planter` (usage: 450, https://taginfo.openstreetmap.org/keys/barrier#values)?

**Comment by RudyTheDev** [comment]
Hey @tordans!

Taginfo says that there are 15 `man_made=plant_container`s and 20 for `man_made=planter_box`es. I think it's safe to say they are simply mistagged due to not knowing or not having a clear tagging scheme. They can probably be fixed manually and they likely don't need full-on deprecation. I don't think anyone would mind about these few cases. I imagine a preset in iD is enough to avoid future mistagging.

I think `material` sounds good. I also think something like species may work (with whatever exact scheme is used for this; I have never actually used it; does iD have a standard way for this?). `operator` sounds fine too. I obviously don't oppose adding any of the reasonable fields that editors may be able to fill. iD is very liberal with extra fields as is.

I have no idea what to do about `barrier=planter`, I was not even aware of it (it's not in the barrier preset's `type=*` list). I want to say that we should upgrade them to add the `man_made=planter_box`. I really like the checkbox idea (although, I am not sure what exactly happens in iD when someone initially adds a barrier and then sets it to a planter - does the planter preset override? It would be an issue since barriers have a different tag layout, like the access ones). This may need a more formal proposal and notification; but I haven't really looked into proposal process since I wasn't intending to actually change anything.

I assumed all 3 geometries are valid - point, line, area. Some planters are elongated but aerial is bad, so they can be a line, although I don't have immediate real examples.

**Comment by RudyTheDev** [comment]
Looks like #506 added planters as man made and optionally as barriers. This covers both cases nicely, so I'll close this. Unless someone wants to pursue additional fields, I think this is good enough for my original proposal.
