### ISSUE TITLE
Clear contribution/development instructions

### ISSUE THREAD

**Issue by lizzyd710** [openstreetmap/id-tagging-schema#161]
Maybe I'm just illiterate, but I want to work on an issue (#153) and have no idea how to actually work on this repo. I know I will need iD, and the README references iD's documentation, but I don't know how to test local changes made to _this_ repo, the tagging schema specifically, since it's separate from the actual editor. 

Again, I might just be missing something, but I think having clear instructions as to how to contribute to this repository specifically would help in getting more people involved.

**Comment by tyrasd** [comment]
Sadly, it's quite the opposite of easy at the moment to test the presets. See #289 for some possible improvements and https://github.com/openstreetmap/id-tagging-schema/issues/131#issuecomment-1005951773 for a hacky solution.

Closing here in favour of #289
