### ISSUE TITLE
Parking "Type" dropdown missing "street_side"

### ISSUE THREAD

**Issue by dreua** [openstreetmap/id-tagging-schema#165]
I think the similarity between "Roadside" and "street_side" makes this a likely cause for tagging errors. Is the "street_side" option simply missing and could be added?

I think this is the relevant code:
https://github.com/openstreetmap/id-tagging-schema/blob/278b0441afe4d34993ac9a409a168241a4a69efd/data/fields/parking.json#L6-L15

[Tag:parking=street_side - OpenStreetMap Wiki](https://wiki.openstreetmap.org/wiki/Tag:parking%3Dstreet_side)

**Comment by ireun** [comment]
This was already proposed in #73

**Comment by AntMadeira** [comment]
Independently of the "Roadside Lane", it should have the option for street_side, since it's a value more and more used.

**Comment by tyrasd** [comment]
this was added in #73
