### ISSUE TITLE
place=square vs highway=pedestrian + area=yes is confusing

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/id-tagging-schema#167]
Maybe using `place=locality` icon would make more clear its distinction from pedestrian area? Technically, #41 would be still the same - but would make the important distinction more clear

here confusion is likely and any help would be nice:
![screen27](https://user-images.githubusercontent.com/899988/116297500-9a929800-a79b-11eb-9a1e-8f1951cedc39.png)

**Comment by tyrasd** [comment]
I used the generic maker icon (for `place=*`) for now.

![image](https://user-images.githubusercontent.com/1927298/148527994-bd3b0266-8edd-42d9-8c2a-a5ca30060f75.png)
