### ISSUE TITLE
Add "OSM Note" as changeset Source option

### ISSUE THREAD

**Issue by martin-kokos** [openstreetmap/id-tagging-schema#188]
OSM Notes are one of the key features and the number of them are growing ( http://resultmaps.neis-one.org/osm-notes ) . Some mappers even specialize on resolving notes. I think it makes sense to have it as one of the presets when saving a changeset.

**Comment by tordans** [comment]
I expect this to be a feature request in the iD Repo. But a maintainer can move the issue over there.

**Comment by martin-kokos** [comment]
Actually I found the options are not in iD but here in schemas. See #189

**Comment by tyrasd** [comment]
this was already fixed in #189
