### ISSUE TITLE
Add `police=checkpoint`

### ISSUE THREAD

**Issue by mfbehrens99** [openstreetmap/id-tagging-schema#197]
Tags that are needed:
```
amenity=police
police=checkpoint
```

**Comment by tyrasd** [comment]
OSM wiki: https://wiki.openstreetmap.org/wiki/Tag:police%3Dcheckpoint (btw: `amenity=police` should not be used according to it, but the proposed preset in #304 looks fine)

Taginfo: https://taginfo.openstreetmap.org/tags/police=checkpoint – currently used about 600 times in OSM
