### ISSUE TITLE
Potential adding a preset for highway=emergency_access_point

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/id-tagging-schema#20]
wiki: https://wiki.openstreetmap.org/wiki/Tag:highway%3Demergency_access_point

Seems approved:
https://wiki.openstreetmap.org/wiki/Proposed_features/emergency_access_point
and is well distributed:
https://taginfo.openstreetmap.org/tags/highway=emergency_access_point
https://taginfo.openstreetmap.org/tags/highway=emergency_access_point#map

Has quite constant organic growth:
https://taghistory.raifer.tech/#***/highway/emergency_access_point

Fields:
`ref`, (not sure about fields `emergency_telephone_code` and `operator` yet)

**Comment by westnordost** [comment]
Would you accept a PR for this?

**Comment by westnordost** [comment]
Disclaimer:

There is also `emergency=access_point` with considerate, but much less usage, with the same meaning

![taghistory(1)](https://user-images.githubusercontent.com/4661658/112906103-e5ad8280-90eb-11eb-96ea-014bbea3b742.png)

`emergency=access_point` is objectively the better tag design and usage numbers of this tag is enough to assume that any data consumer that uses the data will check for both tags. On the other hand, unlike the former, `highway=emergency_access_point` was both approved and has a lot of usage.
So I think the only way to "get rid of" `highway=emergency_access_point` would be to create a proposal to deprecate/replace it with `emergency=access_point`.

So until that should happen (it will probably never happen), I think it is good to use `highway=emergency_access_point` and it will not create any stir.

**Comment by tyrasd** [comment]
> Would you accept a PR for this?

yes, definitely. :smiley: 

> `emergency=access_point` is objectively the better tag 

I wouldn't disagree, but [`emergency=access_point`](https://wiki.openstreetmap.org/wiki/Tag:emergency%3Daccess_point) is still considered to be a "draft" tag, so I would start with the approved one.

**Comment by tiptoptom** [comment]
I found `emergency=access_point` at this list: https://github.com/openstreetmap/id-tagging-schema/issues/529#issue-1301906440

Should this be added even though it has not yet been approved?
