### ISSUE TITLE
Translations not updated

### ISSUE THREAD

**Issue by AntMadeira** [openstreetmap/id-tagging-schema#207]
Hi there.

I'm the Portuguese iD translator and whenever iD was updated to a new version, translations were also updated, but in its last update, translations were not updated. Am I missing something or is iD and translations made via Transifex now separated? If so, when are translations updated?

Regards.

**Comment by AntMadeira** [comment]
The new version 2.20.1 came out and still no new translations...

**Comment by 1ec5** [comment]
> Can you please explain what this means?
> How can I help to solve this?

Translations are blocked until this package’s latest release is uploaded to NPM by one of the package’s maintainers. Unfortunately, there’s nothing translators like you and me can do about it at the moment.

**Comment by AntMadeira** [comment]
I just want to say that the translations were (finally!) updated.
If there's anything I can do to help on this front, please contact me here or via my OSM profile.

Regards.

**Comment by Mahabarata** [comment]
I'm not sure this issue is the same than the issue #269 = I don't know if AntMadeira talks about translations in translatewiki.net or about Portuguese translations in transifex (or both).

But for French translations in transifex, we still have old translations in ID.
So the issue #269 is not closed unlike this one.
Best regards

**Comment by AntMadeira** [comment]
@Mahabarata, for clarification, as I state in the first message, I was referring to translations in Transifex. Translations in translatewiki.net are meant for the OSM website.

Regards.

**Comment by Mahabarata** [comment]
Ok,
according to me, see my tests [here](https://github.com/openstreetmap/id-tagging-schema/issues/269#issuecomment-1011057972), portuguese transifex are not up to date in ID.
On october 29, portuguese translations were not in ID (see comment above at this date) and between october 29 and december 12 nothing appended (or the translation created on october 26 would be visible, see my tests) so I don't understand why you said it was ok and you closed your issue.
Best regards
