### ISSUE TITLE
remove tags "fee" and "charge" from the amenity=telephone preset, because it is too difficult to provide differentiated information with these tags

### ISSUE THREAD

**Issue by Lukas458** [openstreetmap/id-tagging-schema#208]
Hello, I want to suggest removing the fields "fee" and "charge" from the telephone preset, because **that there is a fee to use the payphone is very, very common**. I know many public telephones all around the world and they have always a fee. So this tag is **redundant**. **I will be very difficult to find a public telephone which you can use for free**.

Maybe I make an example here:
- There can be the one or two exceptions, where there is a telephone that doesn't have a fee. But that's often limited to local calls. But a **general** fee=no is then wrong in my eyes. It would be even more helpful to add this information in a description instead of tagging general fee=no then. In my Overpass Query (see below) I found some of those.
- Why is this tag redundant then? You can go over to tag the **payment methods** directly, which gives **much more** information either. We also do not tag a chewing gum **vending machine** with fee=yes, even though you'll have to pay for the chewing gum. Because it's clear that you will have to pay.

I searched Overpass for those phone which have fee=no. There are some, but many of them are special ones or they're tagged wrongly.
1. This is a phone where nationwide calls are free: https://www.openstreetmap.org/node/7572144641 but a general "fee=no" would be wrong. Because at a public phone, you cannot assume that someone maybe dosen't want to call somebody in another country.
2. The same here: https://www.openstreetmap.org/node/5834806361
3. Here a phone which has no fee but does accept coins? https://www.openstreetmap.org/node/3462242024
4. Here a public phone which has no fee, but is a **special one (usable only for crossing the railway crossing)**: https://www.openstreetmap.org/node/8501292936 (in my eyes amenity=telephone would be wrong here, because this isn't a "normal" public phone, we'd need another, a new tag for this).
5. This one has fee=no but the tag amenity=telephone is wrong here, because the description says it's disused: https://www.openstreetmap.org/node/6988182141
6. Here another telephone which has fee=no, but amenity=telephone is wrong as there's only the box left: https://www.openstreetmap.org/node/6328057269
7. This is also a special one: https://www.openstreetmap.org/node/3638039953
8. Here a phone which has limited free-calls: https://www.openstreetmap.org/node/1000481215  - but when you look at the website linked, you can read "The cost for outgoing local and long-distance calls is 1.4 cents per minute", so a **general** fee=no is also here wrong in my eyes. It only *then* free, when people donate enough.

Of course there are also counter-examples, forexample https://www.openstreetmap.org/node/8568224279 seems to be one.
But I think that's the extreme minority. **fee should at least not be a mandatory tag in order to be able to add the payment methods only then.**

Also, describing the **charge** for using a public phone is very hard.
Charges for international calls, mobile communications, SMS, video calls etc. are often very different. A general statement about "charge" would be rather misleading, right? Where is defined that tagging "charge" means landline communicatons per minute? Landline calls can also have different rates for local and long-distance calls.

Here's a public phone which is tagged very detailed with fee and charge: https://www.openstreetmap.org/node/1783493212/

But let's be honest: Can we expect every mapper who wants to register a public phone to have that much knowledge? Hardly any other phone is tagged so precisely.

**Comment by FaFre** [comment]
I support this. According to taginfo (https://taginfo.openstreetmap.org/tags/amenity=telephone#combinations) `fee=*` is also only used for 0.81% of all `amenity=telephone`. Further `payment_multi_fee` and `charge_fee` are also not used in that combination. 

It would make more sense to introduce `payment:coins=* and `payment:telephone_cards=*` instead, which are commonly tagged and also imply that there is a fee.

**Comment by Adamant36** [comment]
> It would make more sense to introduce payment:coins=* and payment:telephone_cards=* instead, which are commonly tagged and also imply that there is a fee.

Not to convolute things, but a lot of "pay phones" accept tokens. For instance I stayed at a hostel once where the "pay phone" took tokens that you asked for at the front desk, but didn't have to pay for. So IMO technically payment:coins=* doesn't imply a fee. It's more about the medium used to access or obtain something. Payment and fee aren't 1/1 synonyms either.

**Comment by Lukas458** [comment]
> Not to convolute things, but a lot of "pay phones" accept tokens.

Well, you're right, yes. But wouldn't this then be payment:token or payment:token_coin instead of payment:coins then? See https://wiki.openstreetmap.org/wiki/Key:payment#Others

payment:token and payment:token_coin are new, rarely used tags, but their usage will increase I think especially as there are some examples as you mentioned. payment:coins means rather coins in a country-specific currency (or several currencies) I think, so this way why payment:token:coin was created, to differentiate between these two things because there's a dfiference of course, as you mentioned too.

**Comment by Adamant36** [comment]
> Well, you're right, yes. But wouldn't this then be payment:token or payment:token_coin instead of payment:coins then?

Sure, but [tokens are often called token coins](https://en.wikipedia.org/wiki/Token_coin). Since they are both a token and a coin. My guess is that a lot of uses of payment:coins are probably tokens and I think what I said about it still stands until there's enough usage of the alternative tags that are specific to tokens. So payment:coins is just being used for currency. Until then though, IMO payment:coins doesn't assume a fee.

**Comment by Lukas458** [comment]
Hmm, ok, so I see fee=* can have its sense and legitimation indeed...

So in conclusion it would be senseful to let it stay...

Okay, then maybe removing charge=* could be more discussed. I'm not sure about whether its easy for some public phones to describe charge=* accurately in this one key-value-pair.

**Comment by FaFre** [comment]
> > It would make more sense to introduce payment:coins=* and payment:telephone_cards=* instead, which are commonly tagged and also imply that there is a fee.
> 
> 
> 
> Not to convolute things, but a lot of "pay phones" accept tokens. For instance I stayed at a hostel once where the "pay phone" took tokens that you asked for at the front desk, but didn't have to pay for. So IMO technically payment:coins=* doesn't imply a fee. It's more about the medium used to access or obtain something. Payment and fee aren't 1/1 synonyms either. 

That's a weird edge case tho. Would be interesting how many of those machines actually (still) exist. 

IMHO it makes most sense to stick to already commonly used tags instead introducing new ways of tagging for rather ancient technologies. The fee tag is as I mentioned is not really used, so maybe existing software for e.g. showing telephones will not properly recognize those features.

**Comment by Adamant36** [comment]
> kay, then maybe removing charge=* could be more discussed. I'm not sure about whether its easy for some public phones to describe charge=* accurately in this one key-value-pair.

I don't see a problem with that.

> That's a weird edge case tho. Would be interesting how many of those machines actually (still) exist.

I've wondered that myself. Really payphones in general are kind of obsolete. I doubt there are many in Western European or America that take tokens, but there could still be a lot in South America or Africa that do. I know at one time they were pretty popular in South America. 


> The fee tag is as I mentioned is not really used

I just looked and there's 755 uses of `amenity=telephone + fee=*` in Africa alone. I'm sure there more uses outside of there. While it's not a super large amount, I wouldn't call it "not really used." 

One thing that I think is important to this is cases where someone knows a phone has a fee, but they don't no what kind of payment the phone takes. You can't really tag that with someone like `payment:coins=*`. I agree that having both fee and charge as options is not necessary though. Since it looks likes fee is currently being used in some number then my suggestion is to save that and remove the charge tag.

**Comment by Lukas458** [comment]
> Since it looks likes fee is currently being used in some number then my suggestion is to save that and remove the charge tag.

Yeah, I would be fine with that.

pull requests seem to be processed quite slowly here at the moment, I assume? I don't know, but there are so many open at the moment, a bit bad ...

(Has nothing to do with the topic now)

**Comment by Adamant36** [comment]
> pull requests seem to be processed quite slowly here at the moment, I assume? I don't know, but there are so many open at the moment, a bit bad

I think they are still trying to find a full time maintainer. I could be wrong, but I think mbrzakovic is only temporary until they do and mainly focuses on the crucial stuff.

**Comment by Lukas458** [comment]
Okay well, yeah. You're right, surely. Comprehensible.

Then I will make a PR durig next time for removing charge=*.
