### ISSUE TITLE
Add "wing dam" as a synonym for groyne

### ISSUE THREAD

**Issue by karsonkevin2** [openstreetmap/id-tagging-schema#229]
At one point I was mapping wing dams, and I found it very difficult to find the correct tag to use, because I had never heard the term `groyne` before. In the US, the US Army Corps of Engineers uses the term `wing dam` to describe all of these objects on the Mississippi, Missouri, Ohio, etc. Rivers.

Looking at the geographic distribution of `man_made=groyne`, people definitely use this tag for river groynes. Wikipedia shows other synonyms of river groynes as `spur dykes`, `wing dykes`, or `wing dams`
https://taginfo.openstreetmap.org/tags/man_made=groyne#map

**Comment by matkoniecz** [comment]
see also https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dgroyne

> Another name for this structure is wing dam.
