### ISSUE TITLE
Add preset for amenity=dog_parking

### ISSUE THREAD

**Issue by carstenhag** [openstreetmap/id-tagging-schema#233]
The key is [amenity=dog_parking](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Ddog_parking).

Proposal for `moreFields`:
```
    "moreFields": [
        "operator",
        "capacity"
    ],
```

I'm aware that it only had 48 usages, but I just documented it ~ a month ago. In my small town I already found 3 places, so I do think there would be many to tag. Also, it's really useful for dog owners.

**Comment by le-jun** [comment]
To be fair, I’d rather have us open the already existing [amenity=hitching_post](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dhitching_post) to all kind of animals, including dogs (dog=yes ?), than create and support yet another smallish tag. [Wikipedia](https://en.wikipedia.org/wiki/Hitching_post) seems to agree on the non-horse restricted use for hitching posts anyway.

**Comment by tyrasd** [comment]
given the still very low number of usages, and the fact that this tag didn't undergo a proper proposal process, I think it's better to not include this tag for the time being.
