### ISSUE TITLE
shooting range is missing (and the current closest match is quite unfortunate, especially for people from US)

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/id-tagging-schema#237]
![screen01](https://user-images.githubusercontent.com/899988/133435775-037af445-6454-4a1b-b031-f4f35c319e4b.png)

**Comment by westnordost** [comment]
According to the wiki a shooting range should be tagged `leisure=pitch` with `sport=shooting`. 

https://wiki.openstreetmap.org/wiki/Tag:sport%3Dshooting
