### ISSUE TITLE
Add Cafeteria preset

### ISSUE THREAD

**Issue by TheAdventurer64** [openstreetmap/id-tagging-schema#25]
The tag `fast_food=cafeteria` is used for a canteen, refectory or a cafeteria, a type of food service location in which there is little or no waiting staff table service, usually found within an institution such as an office building, factory, hospital, or school. 
Source: https://wiki.openstreetmap.org/wiki/Tag:fast_food%3Dcafeteria

Tag with `amenity=fast_food`and `fast_food=cafeteria`.

**Comment by qugebert** [comment]
I think this can be closed as completed.

**Comment by qugebert** [comment]
@tyrasd I think this can be closed as completed in #613
