### ISSUE TITLE
Add preset for landuse=salt_pond

### ISSUE THREAD

**Issue by Mahabarata** [openstreetmap/id-tagging-schema#258]
### Description

Hi,

on ID, when we choose landuse:salt_pond, there is no translation in french.
Probably because when I go to transifex, salt_pond is missing
Could you add it ?

Best regards

edit on 21 Dec 2021 =
because this issue is still open and I found another 'landuse' missing, I add this request.
We don't have either in transifex "landuse=depot" so no translation in ID.
Could you add it too ?
Thanks.

**Comment by matkoniecz** [comment]
I would be strongly against `landuse-depot`

This tag is frequently used to everything that can be called depot including tram depots, warehouses, container depots, bus depots, aircraft boneyards, areas for storage of produced vehicles and more. Such mix of features in one tag is not really useful, and most of them are well covered by existing tags.

See also https://github.com/gravitystorm/openstreetmap-carto/issues/3480 https://github.com/gravitystorm/openstreetmap-carto/issues/2989 https://github.com/gravitystorm/openstreetmap-carto/issues/1716 (all are "Add rendering for landuse=depot")

**Comment by Mahabarata** [comment]
According to taginfo, the key "depot" is used with the value "bus" 819 times. Next value is "container", only 158 times and the next one (tram) only 74 times.

So if we want to talk about depot, we should look at depot=bus.

Bus are big, buildings cost money, so a lot of areas for bus are open spaces.

There are 2 possibilities for areas with buses :
- it is a place for companies that build buses. They store their buses before to sell them : this area clearly is an industrial area
- it is a place for companies using buses as a service, they store their buses at night because not using them : a service company should use the key "commercial", this area is clearly a commercial area.

The areas of the first kind are very few in the world : there are few companies that build buses and each company has very few places where they build and store their buses.
But the second kind is huge : almost all medium and big cities have a transportation company and all have to put their buses somewhere at night. 

It means that (if I use alternative tags) industrial=depot should be a very small number and commercial=depot should be a big one in osm.

In taginfo, it is the exact opposite (more than 3,000 for industrial, less than 50 for commercial) !

I see several reasons for that :
- because of the wiki page for industrial=depot : it is clearly a bad definition, the page talks about commercial=depot and not about industrial=depot
- because of the wiki page for commercial=depot : there is no page.
- when I use "landuse=commercial+commercial=depot" I have in ID "commercial area" = when I see that, I try to find something else for my depot of buses
- when I use "landuse=industrial+industrial=depot" I have in ID "industrial area" = when I see that, I try to find something else for my depot of buses
- if I search "depot" in ID or another word like storage, store, warehouse... I never find something which fit with a depot for buses (but sometimes I find very strange tags. Maybe the funniest = with "depot" we find "psychotherapist" ?!)

Some other informations. When I look for "depot=bus" (819 items with these tags according to taginfo) with overpass, I find today :
- 481 landuse=depot
- 238 industrial=depot (or bus_depot)
- 43 building=yes, depot, garage, commercial or industrial
- 25 commercial=depot or similar
- 18 amenity=parking
- 15 landuse=garages
- 15 amenity=bus_depot, bus garages, bus station, depot

According of what I read in the links you put, the winner should be commercial=depot but it is not what we find in osm.

Somewhere I read that osm was what contributors put in it.
Some use industrial=depot because of the bad wiki page. Without these bad informations, probably everybody will use landuse=depot.

Conclusion :
- osm is what contributors put in it
- contributors, when using "depot", it is for a bus depot
- contributors, when using depot=bus, use first landuse=depot, sometimes landuse=industrial but it is probably an error because of the wiki page

You are right when you say that landuse=depot could be used with a lot of different kinds of depot. Is it really a problem ? There are many different things for natural=water, for natural=wetland. We use water= or wetland= to be more specific. So why not for landuse=depot ?

A preset for landuse=depot seems to me the best choice.

Best regards

**Comment by tyrasd** [comment]
Hey @Mahabarata! I appreciate your effort to explain your reasoning of proposing `landuse=depot` as a new preset. But I do also see that the tag is also clearly not unproblematic, as outlined by @matkoniecz above. I think this issue tracker is really not a good place to discuss these tagging questions, however. Could you please try to find a better forum to clarify the tagging of various kinds of depots, for example the _tagging_ mailing list would be a better option in my opinion?

PS: 

> if I search "depot" in ID or another word like storage, store, warehouse... I never find something which fit with a depot for buses (but sometimes I find very strange tags. Maybe the funniest = with "depot" we find "psychotherapist" ?!)

This one was easy to fix by adding search term to the respective alternative presets: b213170.

<hr>

For now, I would like to limit this ticket to the addition of the originally proposed `landuse=salt_pond` tag.
