### ISSUE TITLE
Enhance camp_site and caravan_site preset fields

### ISSUE THREAD

**Issue by hiddewie** [openstreetmap/id-tagging-schema#26]
I would like to request a number of fields to be added to the tourism `camp_site` and `caravan_site` presets:
- `tents` (yes/no)
- `caravans` (yes/no)
- `static_caravans` (yes/no)
- `backcountry` (yes/no)
- `group_only` (yes/no)
- `nudism`

The reason that these fields are important, is for finding a camp site with a certain vehicle or with a tent. Without these properties, camp sites may not allow access for camping with the vehicle/tent at hand. Situations like this occur when:
- A camp site is visited where nudism is the norm, but the visitors would rather not camp in a nude manner
- A camp site is paved with asphalt and cannot facilitate pitching tents
- A caravan site only allows static caravans, and no overnight camping with any vehicle/tent
- A camp site only allows tents and does not allow caravans or other large vehicles.
- A camp site only allows groups
- A camp site only allows private / members only access

Editors like iD and JOSM are the first point to improve the tagging experience for mappers. JOSM has a good preset, but the iD preset is lacking the required fields.

The [open camping map](https://opencampingmap.org/#10/48.6100/8.2400/0/1/bef) visualizes this well.

Also see [this tagging mailing list conversation](https://lists.openstreetmap.org/pipermail/tagging/2020-August/054828.html) about differentiating caravan_site and camp_site.

---

If I can make the time I will also try a pull request for this enhancement.

---

iD screenshot of camp_site preset:

![image](https://user-images.githubusercontent.com/1073881/90331634-5fa65680-dfb6-11ea-8dc6-80ef81bbdfa4.png)

JOSM screenshot of camp_site preset:

![image](https://user-images.githubusercontent.com/1073881/90331598-1524da00-dfb6-11ea-8757-7bcc68c1f94b.png)

//edit @tyrasd 

checklist for proposed fields:

* [x] `tents` #749
* [x] `caravans` #750
* [x] `static_caravans` #751
* [x] `picnic_table` #745
* [ ] `backcountry`
* [ ] `group_only`
* [x] `nudism` #752

**Comment by osmuser63783** [comment]
I think this issue can be closed, as the fields requested are all part of the preset? Plus separate presets for backcountry and group-only campsites.

**Comment by tordans** [comment]
All right. I did not check it in detail but I see a few linked PRs. Please create a new issue if something is missing.

**Comment by hiddewie** [comment]
Thanks everybody involved for the work improving this preset!
