### ISSUE TITLE
Add regional presets for german cycleway tagging

### ISSUE THREAD

**Issue by tordans** [openstreetmap/id-tagging-schema#267]
I am thinking about adding regional presets for cycleways in Germany … – Any thoughts on this? Would such a PR be merged?

Presets I am considering:

- [ ] https://wiki.openstreetmap.org/wiki/DE:Tag:traffic_sign%3DDE:240
    See https://github.com/openstreetmap/id-tagging-schema/pull/345
- [ ] https://wiki.openstreetmap.org/wiki/DE:Tag:traffic_sign%3DDE:241-30
- [ ] https://wiki.openstreetmap.org/wiki/DE:Tag:traffic_sign%3DDE:241-31
- [ ] "Fahrradstraße" https://wiki.openstreetmap.org/wiki/DE:Key:bicycle_road with traffic_sign=DE:244.1 ([Example](https://www.openstreetmap.org/way/744158640)) ==> https://github.com/openstreetmap/id-tagging-schema/pull/1207

They describe very specific tagging for footways with access rules for bikes.

The traffic sign could be part of the icon and also added as part of the preset.

I think having a clear name in iD (…) for a way with this tagging would be helpful.

---

**Notes about regional presets:**

(Thanks to [a comment by Bryan](https://github.com/openstreetmap/id-tagging-schema/pull/288#issuecomment-986919641))

Presets and fields support a `locationSet` to include/exclude countries.
- `locationSet: { include: ["de"] }`
- `locationSet: { exclude: ["de"] }`

The code in iD (https://github.com/openstreetmap/iD/pull/8305/files#diff-f38480d9980a09d7046b627edd05069ed2b53e545697888c66b697e855b8d886R10-R22) uses the location-conflation module https://github.com/ideditor/location-conflation#what-is-it which in turn allows uses country-coder https://github.com/ideditor/country-coder#what-is-it which allows all kinds of regional identifiers.

Quick link to a search result list of presets and fields that use this feature right now: https://github.com/openstreetmap/id-tagging-schema/search?q=locationSet

**Comment by tordans** [comment]
I added the "Fahrradstraße" bicycle road to the list of additional presets.

**Comment by tordans** [comment]
I updated the issue with what I learned about the locationSet feature and clarified the general question about those presets.

**Comment by tyrasd** [comment]
> Any thoughts on this? Would such a PR be merged?

Sure, why not! Btw. related is also #109.

**Comment by tordans** [comment]
@tyrasd would love to hear your thoughts on those regional bike presets. There where quite a few tickets here and in iD and the schema repo which are related to this in the sense, that regional presets cause some issues. And working on https://github.com/openstreetmap/id-tagging-schema/pull/345 I had the same feeling, that those presets might stretch the current setup too much. However, I want to get them going as well since they add a lot of clarity and enable good data.

So my question is: What are your thoughts which tickets need to be solved before adding more of those regional presets? And do you have plans to tackle those tickets in the near future (from your personal roadmap point of view)? 
A review of #345 might be a good start to get this answer going (we could also do this in a screenshare session if you like).

(Please let me know if this was too vague and I will go into more details.)

**Comment by tordans** [comment]
I will close this for now. The traffic sign related presets are better resolved by improving the `traffic_sign` field. And the bicycle road has a draft to add a preset at https://github.com/openstreetmap/id-tagging-schema/pull/1207
