### ISSUE TITLE
Broken links in GNIS Feature ID field

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/id-tagging-schema#272]
The USGS has sunsetted the GeoNames domestic name lookup tool that the GNIS Feature ID field links to:

https://github.com/openstreetmap/id-tagging-schema/blob/9fdecc983443ce75185c2923caae9f7703f2cae4/data/fields/gnis/feature_id.json#L5

These URLs now redirect to [a landing page](https://www.usgs.gov/core-science-systems/ngp/board-on-geographic-names/domestic-names), which explains that many of the GNIS feature classes that had been imported into OSM have been archived and will no longer be searchable online. They remain downloadable in a data dump, but that isn’t helpful for this field. The feature classes were archived because of being unmaintained, but many of the features are still extant ([example](https://www.openstreetmap.org/node/357514006)).

For the feature classes that haven’t been archived, a new search tool is available, but [its permalinks](https://edits.nationalmap.gov/apps/gaz-domestic/public/search/names/8b5029c4-1621-545b-82ac-d031d0d0f63b/summary) include a UUID that’s unrelated to the GNIS feature ID. I’m unsure if the search form can take the feature ID as a query parameter.

The National Map program also has a MapServer containing GeoNames, but you can only [query one layer at a time](https://cartowfs.nationalmap.gov/arcgis/rest/services/geonames/MapServer/4/query?where=feature_id%3D1061736&outFields=*&returnGeometry=true), and it doesn’t contain all the metadata that’s in the main search tool. It probably also doesn’t include the archived feature classes.

**Comment by jleedev** [comment]
The link button in the upper corner of that site gives a reasonable-looking URL:

https://edits.nationalmap.gov/apps/gaz-domestic/public/summary/1187058

**Comment by 1ec5** [comment]
Thanks, that would be a clean replacement for the old URL format. Still, I’m a bit concerned about the legacy feature classes being archived: if users get the idea that this link helps to verify the veracity of a GNIS feature ID, then seeing a false negative “not found” could lead to some POIs getting unnecessarily deleted, or at least their feature IDs getting untagged. Maybe we should import the rest of GNIS into Wikidata (beyond the parks and populated places) and link there instead.

**Comment by jleedev** [comment]
For context, NationalFile_20210825.txt contains 2279130 records, and Wikidata contains 670610 statements of p:P590.

**Comment by tyrasd** [comment]
I'm not sure how to best proceed here. Should we use the new url (`https://edits.nationalmap.gov/apps/gaz-domestic/public/summary/…`?)? Or would it be better to drop the link for now until a better solution is found?

**Comment by 1ec5** [comment]
For now, I guess the National Map URL is better than the current broken link. One way to allay the concern about the deleted categories would be to stand up a Web-based tool that can display the metadata and description from the GNIS dump given a feature ID. It might be easier than figuring out the logistics of importing the POIs into Wikidata and conflating them with existing Wikidata items. But standing up that tool wouldn’t be your responsibility; we can always update the link once it’s available.
