### ISSUE TITLE
Issue on network presets

### ISSUE THREAD

**Issue by Kalepom** [openstreetmap/id-tagging-schema#274]
Hi, 
On bike rentals operated by JCDecaux, the preset suggest you to swith to network "Bicloo", which is the bike network in Nantes, but not in every city of France. 

![image](https://user-images.githubusercontent.com/12937457/142781738-551c24f8-c7eb-4fc9-b684-4620bc60a611.png)

**Comment by tas50** [comment]
@Kalepom you'll want to report this to https://github.com/osmlab/name-suggestion-index where that data comes from

**Comment by matkoniecz** [comment]
According to https://github.com/osmlab/name-suggestion-index/issues/5772 it is fixed. Fix should become visible on new release by NSI and either way this issue can be closed.
