### ISSUE TITLE
translation of highway=construction and proposed

### ISSUE THREAD

**Issue by Mahabarata** [openstreetmap/id-tagging-schema#275]
Hi,

in transifex we have a lot of things about construction : railway, building, area for example
But we don't have highway=construction so we don't have a good translation in ID (only the generic translation for highway=*).
Same thing for highway=proposed.
Could you add presets ?

Best regards

**Comment by matkoniecz** [comment]
For `highway=construction` see #10

If `highway=proposed` would be added care should be taken to not make it searchable to avoid encouraging its use, though it can be useful to show already mapped ones. See https://github.com/openstreetmap/iD/issues/7636

**Comment by Mahabarata** [comment]
For "construction", the issue #10 (sorry not to have seen it before) is ok for me, no need of my own issue.

For "proposed", you're right, it's not a good idea to have a preset.

So I close this issue.
