### ISSUE TITLE
incomprehensible text to translate

### ISSUE THREAD

**Issue by Mahabarata** [openstreetmap/id-tagging-schema#276]
Hi,

in transifex we have a text to translate. But this text is full of bugs (too many spaces, typing errors), very long with too many 'and', too many 'that', 'in order to', 'by', 'towards' so this text is not clear almost incomprehensible = 

This is a new  chapter at out institute and we are looking forward to use our financial education that we are receiving here at the campus  and link ig with the environment in order to develop our sustainable environment towards helping the community  with the effects of our environment in a financial ways by converting them into numbers. this is widely explained in ecosystem accounting and environmental accounts.

It will great to have a better text with short sentences. Or, because I find strange to have this text in ID, maybe you could delete it in ID+transifex ?

Best regards

**Comment by matkoniecz** [comment]
Which text? Can you quote what is supposed to be translated, give its identifier or at least attach screenshot?

**Comment by bryceco** [comment]
I think the middle paragraph is the text in question, but I don't understand where they found it.

**Comment by matkoniecz** [comment]
Then screenshoot would be useful, I suspect that there is some confusion and the transifex is not an iD transifex.

**Comment by Dimitar5555** [comment]
It's item 635 in the Community section and it's key is  `ym-Institute-of-Finance-Management.extendedDescription`.
![image](https://user-images.githubusercontent.com/19364673/143470418-9f0133f7-a7c2-406b-be11-bde5c371c034.png)

**Comment by matkoniecz** [comment]
That is coming from osm-community-index 

I created https://github.com/osmlab/osm-community-index/issues/493 to report problem.

Thanks for noticing and reporting! This issue can be closed, as problem is not iD tagging presets

**Comment by Mahabarata** [comment]
Ok, I understand.
Thanks for all your answers, I close this issue.

Best regards
