### ISSUE TITLE
sidewalk + transit platform

### ISSUE THREAD

**Issue by Mahabarata** [openstreetmap/id-tagging-schema#279]
Hi,

when you have 3 connected ways :
- a sidewalk (highway=footway + footway=sidewalk)
- a transit platform (a way with only the tag public_transport=platform)
- another sidewalk (highway=footway + footway=sidewalk)

if the first sidewalk is connected to others highways, if the transit plaform is connected to both sidewalks (in the middle of) and if the second sidewalk is connected only to the transit platform (or to something not connected to all others highways), ID indicate a false problem = the 2d sidewalk is not connected to others highways.

Example here =
https://www.openstreetmap.org/way/897222578

Best regards.

**Comment by 1ec5** [comment]
Please see the discussion in openstreetmap/iD#8760. In short, the warning is intended to alert you to the fact that most routers will not route over the second way in your example. openstreetmap/iD#8800 changed the wording to be a little clearer. iD doesn’t suggest a solution, but one approach that some mappers take is to map the platform as an area and map a footway through it. Regardless, validator rules are implemented in iD, not in the id-tagging-schema project. Some validator rules are informed by data in this project, but the routability warning is not.

**Comment by Mahabarata** [comment]
Your answer is ok for me so I close this issue.
Best regards
