### ISSUE TITLE
Preset for tofu shops

### ISSUE THREAD

**Issue by nicolasmaia** [openstreetmap/id-tagging-schema#28]
Very common in Japan. 豆腐屋

    shop=deli
    product=tofu

See https://wiki.openstreetmap.org/wiki/JA:How_to_map_a

Alt names: tofu seller; tofu maker

**Comment by tyrasd** [comment]
closing because of the (currently still) too low usage. If this gains traction, we can reconsider it in the future, of course :relaxed: 

see also #27
