### ISSUE TITLE
Show official_name if tagged already

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/id-tagging-schema#283]
Some objects such as https://www.openstreetmap.org/way/25506183 https://www.openstreetmap.org/relation/9465346 have regular actually used `name` and officially assigned `official_name`

Some new mappers change `name` tag to what is already in `official_name` what is a repeated annoyance.

It would happen less often if `official_name` would be shown by iD and make clear that this info is collected already

**Comment by 1ec5** [comment]
#215 adds an Official Name field.
