### ISSUE TITLE
Add a colour field type

### ISSUE THREAD

**Issue by tyrasd** [openstreetmap/id-tagging-schema#284]
Editors might want to show a color picker for ["colour" fields](https://wiki.openstreetmap.org/wiki/Key:colour). For this a dedicated field type (`"type": "colour"`) would be useful.

See https://github.com/openstreetmap/iD/pull/8782#discussion_r739929246.

**Comment by 1ec5** [comment]
This field type would need to be added to [schema-builder](https://github.com/ideditor/schema-builder/) first.

**Comment by tyrasd** [comment]
this field type is now implemented in v5.0 (#598)
