### ISSUE TITLE
Preset for sport=pickleball

### ISSUE THREAD

**Issue by talllguy** [openstreetmap/id-tagging-schema#286]
I'd like to see a tagging preset added for [Pickleball courts](https://wiki.openstreetmap.org/wiki/Tag:sport%3Dpickleball). Pickleball courts are smaller than tennis courts.

## Tags

    leisure=pitch
    sport=pickleball

## Justification

Pickleball is a paddle sport similar to tennis that [has experienced explosive growth in popularity in the United States](https://usapickleball.org/about-us/organizational-docs/pickleball-fact-sheet/). There are 4.2 million players in the US according to the US Pickleball Association ([source](https://usapickleball.org/about-us/organizational-docs/pickleball-fact-sheet/)). Pickleball courts are typically set up on tennis courts using temporary lines, using tape or chalk. However, new courts are starting to be built specifically for Pickleball (see below). I'd like to see a preset added for these courts in iD.

## Comparison

![Pickleball and tennis court comparison](https://user-images.githubusercontent.com/1827881/144457289-486369aa-9919-4ceb-b9c8-ff3c4c263f18.png)

**Comment by 1ec5** [comment]
This preset should have “tennis” as a search term too. I encounter pickleball courts all the time but can never remember what it’s called.

**Comment by talllguy** [comment]
Good point @1ec5 ❗ 

Here is [an example](https://www.openstreetmap.org/way/1008653771) of a Pickleball court installed on top of an existing tennis court. The Pickleball court uses yellow lines in this case. These are also becoming more common with the increase in pickle🥒 and decrease in tennis🎾. I believe technically the pickle net is supposed to be lower than what regular tennis uses so these options are more of a compromise.

![image](https://user-images.githubusercontent.com/1827881/144485235-ccd126e1-bf69-436c-9c67-e621bd53dd41.png)

**Comment by pardthemonster** [comment]
@talllguy we have shared courts too, but have ability via crank to lower net when we play pickle ball (and raise back up after for the tennis players).

**Comment by 1ec5** [comment]
Each of the `leisure=pitch` presets retains its Sports field, which accepts multiple values. I often use that field to tag multipurpose athletic fields/courts when the sports are indistinguishable. However, the Sports field [doesn’t have any predefined values](https://github.com/openstreetmap/id-tagging-schema/blob/7986680ea10bb97983775ed2e1d8b9156110a0a3/data/fields/sport.json#L5), so it just lists the most common values from taginfo without any localization.

Another approach is to map overlapping `leisure=pitch` areas, which makes more sense when each sport’s court has different dimensions. No field changes would be needed to support this approach. Some renderers, like the French [osmfr-cartocss](http://tile.openstreetmap.fr/?zoom=19&lat=37.31773&lon=-122.00854&layers=B00000000FFFFFF), do the right thing when athletic fields/courts overlap in this manner.

**Comment by semriop** [comment]
Pickleball is played on a much smaller court. Whereas tennis courts are 60 feet wide and 120 feet long, pickleball courts are 20 feet wide and 44 feet long,

**Comment by 1ec5** [comment]
Understood, but some users (myself included) remember “tennis” much more easily than “pickleball”, so the extra term in the preset makes it easier to find the correct preset.

**Comment by uzairahmadkl** [comment]
https://trizonsports.com/best-pickleball-paddles-for-beginners/
