### ISSUE TITLE
Add preset for "Altglascontainer" glass bottle container

### ISSUE THREAD

**Issue by tordans** [openstreetmap/id-tagging-schema#294]
It looks like this is a thing for Germany only(?).
But we have them everywhere, and I always pick the wrong preset first. So it would be great to have a specific preset for this.

<img width="395" alt="Bildschirmfoto 2021-12-14 um 20 22 32" src="https://user-images.githubusercontent.com/111561/146066123-7643bc0a-f248-4fc0-8271-602cc7f1edbe.png">

https://wiki.openstreetmap.org/wiki/Altglascontainer
```
amenity=recycling
recycling_type=container
recycling:glass_bottles=yes
```

Other wiki pages
* https://wiki.openstreetmap.org/wiki/Tag:amenity%3Drecycling
* https://wiki.openstreetmap.org/wiki/Key:recycling_type

Alternatively, we could improve the search keywords on https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/amenity/recycling_container.json.

Icon: I would keep the existing generic recycling icon, but we could make a composite icon with ![](https://wiki.openstreetmap.org/w/images/thumb/c/c9/R%C3%B6ntgen_wine_bottle.svg/64px-R%C3%B6ntgen_wine_bottle.svg.png) from https://wiki.openstreetmap.org/wiki/Tag:amenity%3Drecycling#Rendering.

![](https://wiki.openstreetmap.org/w/images/thumb/8/80/Altglas.jpg/400px-Altglas.jpg)

**Comment by bhousel** [comment]
You might also consider just adding it to NSI, if it's a commonly branded recycling container in Germany..

We're already tracking a bunch of branded recycling containers for things like bottle dropoff and clothing donation.
https://nsi.guide/index.html?t=brands&k=amenity&v=recycling

**Comment by matkoniecz** [comment]
Is it a brand of recycling container? Or a special world for just glass container standing alone from other recycling containers?

> I always pick the wrong preset first.

Which one you pick?

**Comment by kjonosm** [comment]
It's not a brand but the common term for such containers. It's the German term for a [bottle bank](https://dictionary.cambridge.org/dictionary/english/bottle-bank).

**Comment by tyrasd** [comment]
"Altglascontainer" is not a brand, it's just the German term for "Recycling Container for Glass Bottles" (actually they are ususally not only for glass _bottles_, but all [container glass](https://en.wikipedia.org/wiki/Container_glass) which also includes jars, vases, drinkware, etc.).

**Comment by tyrasd** [comment]
Closing until https://github.com/ideditor/schema-builder/issues/25 is implemented upstream.

I have however added "Altglascontainer" to the translated list of alternative terms of the "recycling container" preset, which should make it possible to find the preset in the search.
