### ISSUE TITLE
Add preset for "Altkleider-Container" `recycling:clothes=yes`

### ISSUE THREAD

**Issue by tordans** [openstreetmap/id-tagging-schema#295]
I think a preset would be a good ideal. Any thoughts?
Alternatively I suggest we add more search terms to the generic recycling preset. But even then, I would have to lookup the best tagging, which is not a nice thing to do :).

https://wiki.openstreetmap.org/wiki/DE:How_to_map_a#Altkleider-Container

```
amenity=recycling
+ recycling_type=container
+ recycling:clothes=yes
+ recycling:shoes=yes
+ operator=*
+ brand=*
```

- Points only
- Generic icon for recycling (is good enough IMO)
- Scoped for Germany only

Current search results:
<img width="397" alt="Bildschirmfoto 2021-12-14 um 20 22 20" src="https://user-images.githubusercontent.com/111561/146066581-1844825d-2370-44c1-a689-3211a9320bf7.png">

**Comment by bhousel** [comment]
Same as #294, this preset could live in NSI also

**Comment by matkoniecz** [comment]
Is it a brand of recycling container? Or a special world for just second hand clothes container standing alone from other recycling containers?

**Comment by kjonosm** [comment]
It's not a brand but the common term for such containers. It's the German term for [clothing bin](https://en.wikipedia.org/wiki/Clothing_bin).

**Comment by tordans** [comment]
> Same as #294, this preset could live in NSI also

Thanks, that is good to know. I wondered about this when I saw that someone actually created a wiki-page to standardize the operator at https://wiki.openstreetmap.org/wiki/Deutsche_Altkleider-Container_Betreiber. 

But for now, I think we will show enough love to this topic by giving it it's own preset. AFAIK the operators change a lot and – at least in Berlin – are kind of seedy(?) (dubius?) most of the time.

**Comment by tyrasd** [comment]
See https://github.com/openstreetmap/id-tagging-schema/pull/308#pullrequestreview-842648480

Adding a preset for this is not possible with the current tagging/presets schema. I have however added "Altkleidercontainer" to the translated list of alternative terms of the "recycling container" preset, which should make it possible to find the preset in the search.

**Comment by tyrasd** [comment]
Closing until https://github.com/ideditor/schema-builder/issues/25 is implemented upstream.
