### ISSUE TITLE
Parking orientation options are misspelled

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/id-tagging-schema#299]
The `parking:orientation` options say “carriage way”, but the correct spelling is “carriageway”. This spelling error [has been fixed](https://wiki.openstreetmap.org/wiki/Special:Diff/2231362) on the wiki.

https://github.com/openstreetmap/id-tagging-schema/blob/97240c04a96f0c022e074a556b596e8f181637d7/data/fields/parking/orientation.json#L7-L9

“Carriageway” is a British English term, but the default locale of this project is American English. Of the two senses of “carriageway”, I’m pretty sure the documentation intends to refer to the part of the street, as opposed to the concept specific to divided highways (dual carriageways). So “Carriage Way” should be replaced by “Roadway” in this repository, then translated as “Carriageway” in iD’s British English localization in Transifex.

/ref https://github.com/openstreetmap/id-tagging-schema/pull/73#discussion_r747308643

**Comment by tordans** [comment]
> So “Carriage Way” should be replaced by “Roadway” in this repository, then translated as “Carriageway” in iD’s British English localization in Transifex.

That sounds good to me. 

Ping @jdhoek @SupaplexOSM since you created [the proposal](https://wiki.openstreetmap.org/wiki/Proposed_features/parking%3Dstreet_side) linked in the last issue and [worked a lot with this tagging schema](https://supaplexosm.github.io/strassenraumkarte-neukoelln/?map=parkingmap#18/52.47502/13.43726).

**Comment by jdhoek** [comment]
Does iD default its locale to `en` (i.e., unspecified/generic English) or `en_US` (American English)? Transifex calls the source language 'English' (presumably referring to `en`).

I'm a bit worried about English terms used in the documentation (using British English by strong convention) and in related tools diverging. For translations to other languages this is not as much of a problem, as wiki pages can be translated as well and more technical users often set their language preferences to English (as in `en`) in any case, but this is not the case for language variants (it would be a silly duplication of effort).

If `en` is the default locale, then changing British (and OSM) terminology to American English seems more harmful than useful to me. If 'en_US` is the default then this is less objectionable, although that choice of default to me does not seem to align very well with the default of British English in OpenStreetMap's tags and documentation.
