### ISSUE TITLE
"railway landuse" should be able to find railway=landuse preset

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/id-tagging-schema#301]
Yes, unlikely to be used by newbies but may help people who know OSM tags and terminology

![screen02](https://user-images.githubusercontent.com/899988/146600501-fa397aab-07e3-42df-8e93-3f8d4dd29921.png)

**Comment by tyrasd** [comment]
https://github.com/openstreetmap/iD/issues/8869 will address the _searching preset by OSM tag_.
