### ISSUE TITLE
Preset for a way designated for both cyclists and pedestrians, without separate spaces (segregated=no)

### ISSUE THREAD

**Issue by ttomasz** [openstreetmap/id-tagging-schema#317]
There seems to be missing a preset for case **S7** in https://wiki.openstreetmap.org/wiki/Bicycle#Miscellaneous

so a combination of tags:
```
highway=footway/highway=cycleway/highway=path
+ bicycle=designated
+ foot=designated
+ segregated=no
```
I think main tag: highway=path would be the most universal for a preset.

Fields can be the same as for cycleway or footway.

This type of footway shared with bicycles is (unfortunately) very popular in Poland and it would be good to have a preset corresponding to that so new mappers aren't confused about mapping those.

**Comment by tordans** [comment]
This tagging is also included in https://wiki.openstreetmap.org/wiki/DE:Tag:traffic_sign%3DDE:240 (which adds the traffic_sign) which I created an issue for in https://github.com/openstreetmap/id-tagging-schema/issues/267

I think it would be ideal, if this preset would have a field (for countries where it applies) that say "This access rights are also signed with a traffic sign", which then would add the traffic_sign-tag and transform this preset to the one with traffic sign from #267. This extra field would nudge mappers to also check for traffic signs to formally confirm the given access-tagging.

**Comment by tordans** [comment]
One more think: AFAIK there is an issue with using `highway=path` as the recommended preset, since there is no corresponding crossing-tagging-recommendation for this. The crossing presets (see those two crossing presets https://github.com/openstreetmap/id-tagging-schema/issues/312) only work with either `highway=footway+cycleway=crossing` or `highway=cycleway+cycleway=crossing`. — At least that is how I understand this for now; I already added it to our topic list for our [next local usergroup](https://wiki.openstreetmap.org/wiki/Talk:Berlin/Verkehrswende/Meetup_2022-01-04).

In any case, we should have a crossing preset as well as a regular preset.

**Comment by ttomasz** [comment]
> One more think: AFAIK there is an issue with using `highway=path` as the recommended preset, since there is no corresponding crossing-tagging-recommendation for this. The crossing presets (see those two crossing presets #312) only work with either `highway=footway+cycleway=crossing` or `highway=cycleway+cycleway=crossing`. — At least that is how I understand this for now; I already added it to our topic list for our [next local usergroup](https://wiki.openstreetmap.org/wiki/Talk:Berlin/Verkehrswende/Meetup_2022-01-04).
> 
> In any case, we should have a crossing preset as well as a regular preset.

Not sure if I understand. Is this a blocker from let's call it a technical standpoint as in when iD automatically creates a crossing when two ways cross and there needs to be a matching crossing type? Or is that more of a concept like there should be matching crossing preset for every highway preset?

**Comment by tordans** [comment]
No, it's nothing technical. It's just very confusing. – How would you tag a way that is tagged like in your proposal as a crossing?

**Comment by kaneap** [comment]
On the wiki path=crossing is documented. https://wiki.openstreetmap.org/wiki/Tag:footway%3Dcrossing

**Comment by matkoniecz** [comment]
Is there any existing presets matching on multiple tags and having priority over another preset ( highway=path + bicycle=designated + foot=designated + segregated=no over bare highway=path) ?

**Comment by kaneap** [comment]
@matkoniecz I believe there are such presets. For example the existing "Cycle & Foot Path" preset (`highway=cycleway` + `foot=designated` + `bicycle=designated`) has priority over bare `highway=cycleway`. 

(The "Cycle & Foot Path" preset doesn't show in some countries: France, Lithuania, Poland, and Germany)

**Comment by tordans** [comment]
Quick update, this is resolved for **crossings** after merging https://github.com/openstreetmap/id-tagging-schema/pull/1201 

It can be [testet in a fresh branch preview](https://pr-1384--ideditor-presets-preview.netlify.app/id/dist/#background=Bing&disable_features=boundaries&locale=en&map=20.00/52.47432/13.44593) (and hopefully soon on the staging version of iD).

<img width="899" alt="image" src="https://github.com/user-attachments/assets/8b425856-5f68-447b-a34a-86d56c78815a" />
<img width="852" alt="image" src="https://github.com/user-attachments/assets/f5c425c3-e67c-4dfb-a9b7-2844e283fdfe" />

---

The `highway=path` part is addressed by https://github.com/openstreetmap/id-tagging-schema/pull/1384 by reusing the fields from https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/highway/cycleway/bicycle_foot.json#L15 for a new preset using `highway=path`.

**Comment by tordans** [comment]
The `hw=path` was just merged in https://github.com/openstreetmap/id-tagging-schema/pull/1384
Please use [the PR preview](https://pr-1384--ideditor-presets-preview.netlify.app/id/dist/#locale=en) to test it out.

**Comment by tordans** [comment]
I think we should close this issue now and create a new one for anything that might be missing. I at least could not tell what we are still missing at a glance.

Will close, please tell me to reopen if needed or create a follow up issue.
