### ISSUE TITLE
Add preset for `memorial=stolperstein`

### ISSUE THREAD

**Issue by tordans** [openstreetmap/id-tagging-schema#318]
We have a lot of those special memorial stones in Germany and both the Wiki(data)/Data Item and OSM Community are recording them. It think a preset would be a nice recognition of this work. 

However, the tagging seems be in a process of change, so we need to find a good preset tagging here.

## **Here is my research:**

- Wiki https://wiki.openstreetmap.org/wiki/DE:Stolpersteine + Discussion https://wiki.openstreetmap.org/wiki/DE_talk:Stolpersteine
- Should only apply for Germany since this is where most of those stones are (right?)
- The recommended tagging changed in 2018 which was discussed on the forum [and the wiki-talk-page](https://wiki.openstreetmap.org/wiki/DE_talk:Stolpersteine#Tagging_scheme_change) and the wiki page shows the result of this change. It was not a formal voting proposal process, though
- The existing tagging was never updated, which means the old tagging still has a lot more use
  - `memorial=stolperstein` 4.499 https://taginfo.openstreetmap.org/tags/memorial=stolperstein
  - `memorial:type=stolperstein` 24.784 https://taginfo.openstreetmap.org/tags/memorial%3Atype=stolperstein
  - I assume the other "unusal" tags will show similar numbers.
- There are two JOSM presets which also still follow the old tagging guideline
  - https://josm.openstreetmap.de/wiki/Presets/Stolpersteine
  - https://josm.openstreetmap.de/wiki/Presets/StolpersteineLight
- There is an active community adding this data as Wikidata Data Item, eg. https://www.wikidata.org/wiki/Wikidata:WikiProject_Stolpersteine [with a map of this data](https://query.wikidata.org/embed.html#%23defaultView%3AMap%0ASELECT%20%3FStolperstein%20%3FStolpersteinLabel%20%3Fgeographische_Koordinaten%20WHERE%20%7B%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%2Cen%22.%20%7D%0A%20%20%3FStolperstein%20wdt%3AP31%20wd%3AQ26703203.%0A%20%20OPTIONAL%20%7B%20%3FStolperstein%20wdt%3AP625%20%3Fgeographische_Koordinaten.%20%7D%0A%7D) => I think we should recommend Wikidata as a preset field as well

## Preset

**What tags to add to the preset:**

* `historic=memorial` – Required
* `memorial=stolperstein` – Required, The presets **reference**
  - And not the IMO outdated `memorial:type=stolperstein`
* `name` – Name of person 
  - And not the IMO outdated `memorial:name`
* `inscription` – Text on stone
  - And not the IMO outdated `memorial:text`
* `website` – There are whole websites about his ([example](https://www.stolpersteine-berlin.de/biografie/1760)), which are useful to have so lets nudge users to add them
* `wikidata`

**More fields-Area:**

* `image` - Wikipedia image URL
* `memorial:addr` – Wikipage was not sure which address, and I don't see it adding a lot of value, since this is geo referenced; therefore place in "more fields"
* `wikipedia`- I would nudge for the wikidata ID instead, therefore place in "more fields"

**What I would leave out:**
* `memorial:ref=<123>` – I don't understand where this official number should come from

## Discuss

**Questions we should talk about**

- See tagging above; @dieterdreist you wrote about this in 2018, what are your thoughts
- How should iD handle the outdated tags? Should we add another, non-searchable preset for the old tags? Or even recommend a tag-update in iD?

**Comment by tyrasd** [comment]
> Should only apply for Germany since this is where most of those stones are (right?)

Austria also has quite a few of them mapped: currently about 1.1k when including both tagging variants vs. 24k in Germany which is about the same order of magnitude when considering their relative population sizes. If I'm counting correctly, this leaves about 1.3k mapped objects remaining, most of which are probably scattered throughout Europe (I found about 230 in Italy and 100 in France, 70 in Spain).

According to [wikipedia](https://de.wikipedia.org/wiki/Stolpersteine), these countries would in principle have Stolpersteine:
![map of which countries have stolperstein memorials according to wikipedia](https://upload.wikimedia.org/wikipedia/commons/5/51/Stolpersteine_in_Europe.svg)

> `wikidata` […] `wikipedia`

Wouldn't the `subject:wikidata` (and `subject:wikipedia`) tags be more appropriate?

**Comment by dieterdreist** [comment]
from my understanding, subject:wikidata would be about the people who are commemorated on the stones, most of which are not famous and there is neither a wikidata nor a wikipedia article about them.

**Comment by tyrasd** [comment]
Since the raw `wikidata` tag should be about the individual Stolperstein memorials themselves, I assumed these would be even more unlikely to exist, but I was wrong: There are currently [16400 wikidata entries of individual Stolperstein memorials](https://w.wiki/4hjB 
) (14500 of which are geolocated – here's an example: https://www.wikidata.org/wiki/Q87722039). Not bad!

**Comment by tordans** [comment]
@tyrasd what are your plans on those issues that rely on https://github.com/openstreetmap/id-tagging-schema/issues/351. Can we move them forward for the time being and refactor them once there is more login in to im prove the situation for translators? Or do you consider them blocked until that issues is resolved?

I would love to see this present going. But also the bike related issues that I started a while back.

**Comment by tordans** [comment]
About the open discussion above:

> `wikidata` vs. `subject:wikidata`

I the preset should stick with `wikidata`. Mappers are asked to add the wikidata entry of the corresponding stone, which is what the top level `wikidata` tag is for IMO.

> How should iD handle the outdated tags? Should we add another, non-searchable preset for the old tags? Or even recommend a tag-update in iD?

To keep thinks simple, I would add unsearchable preset to at least show those old tags the same way. The question of how to harmonize the two schema can be raised later / elsewhere.
