### ISSUE TITLE
Add safety:​mask:covid19 field.

### ISSUE THREAD

**Issue by TheAdventurer64** [openstreetmap/id-tagging-schema#32]
This field would allow users to put down if a place requires you to wear a mask, or not. More info [here](https://wiki.openstreetmap.org/wiki/Key:safety:mask:covid19).

**Comment by TheAdventurer64** [comment]
This would also help us cases like McDonalds; Where even though mask regulations may vary by state, the fast food franchise requires all customers to wear a mask.

**Comment by tyrasd** [comment]
I have the impression that this tag didn't get much traction in the past year or so. I think it is not really worth to include at this point.
