### ISSUE TITLE
typo in string 6933

### ISSUE THREAD

**Issue by Mahabarata** [openstreetmap/id-tagging-schema#321]
Hi,

in transifex, we have a text to translate with the number 6933, context = "imagery.LSA-DOP20.description".
The original text is : "areal image of the state saxony-anhalt, 20cm resolution"

Maybe this text would be better with something like "aerial image of the state Saxony-Anhalt, 20 cm resolution".

Best regards

**Comment by matkoniecz** [comment]
It seems to be for name suggestion index project
