### ISSUE TITLE
Add preset for crosswalks controlled by traffic lights.

### ISSUE THREAD

**Issue by mxxcon** [openstreetmap/id-tagging-schema#332]
Please add a preset for `crossing=traffic_signals` to make it easier to tag crosswalks that are controlled by traffic lights.

Currently iD has 2 crosswalk presets:

**Marked Crosswalk** which creates:
`crossing=marked`
`highway=crossing`

And **Unmarked Crosswalk** which creates:
`crossing=unmarked`
`highway=crossing`

According to [crossing=marked](https://wiki.openstreetmap.org/wiki/Tag:crossing%3Dmarked) and [crossing=unmarked](https://wiki.openstreetmap.org/wiki/Tag:crossing%3Dunmarked) both of these presets are for crosswalks **_not_** controlled by traffic lights.
<hr>
Additionally, there are some presets called "crosswalk", while others "crossing". Please make them consistent where appropriate to make it easier to search for them.

Also, if a way is manually tagged with `crossing=traffic_signals`, iD names it **Pedestrian Crossing**. However, that preset is not available to pick from or during search.

**Comment by 1ec5** [comment]
This was fixed in #192.

**Comment by mxxcon** [comment]
Was it not released yet?

**Comment by 1ec5** [comment]
No, 0b0d7981af9d0f1029b13d2026423fded9cdeeea hasn’t been released yet.

**Comment by tyrasd** [comment]
see also https://github.com/openstreetmap/iD/discussions/8866#discussioncomment-1917730
