### ISSUE TITLE
Presets for forward/backward would be better for speed camera direction

### ISSUE THREAD

**Issue by martenjj** [openstreetmap/id-tagging-schema#338]
Currently there is a "Direction (Degrees Clockwise)" field for highway=speed_camera, but it is a numeric field allowing positive or negative in 5 degree increments.  This would be suitable for a standalone surveillance camera, but for a speed camera placed on a way a more sensible direction preset would be either "forward" or "backward".  If typed manually in the entry field, iD supports these direction specifications and shows the camera node appropriately.

Suggest that "forward"/"backward" are added either in addition to the direction present (if this is possible) or as the only preset.  This highway feature would then work similarly to traffic lights, give way signs etc.

**Comment by tyrasd** [comment]
The [OSM wiki does suggest](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dspeed_camera) to use the direction in degrees:

> `direction=*` can be used to specify the way the the speed camera faces, usually in degrees or sometimes with cardinal directions.

This can also be seen in current usage statistics: the values `forward` and `backward` are only used on 18 and 17 speed camera nodes, respectively.

As far as I know, one needs to use a [enforcement relation](https://wiki.openstreetmap.org/wiki/Relation:enforcement) to accurately map which direction of the road the speed camera monitors.
