### ISSUE TITLE
Use embassy=yes instead of embassy=embassy

### ISSUE THREAD

**Issue by overflorian** [openstreetmap/id-tagging-schema#340]
Hi,
In iD, I propose to stop suggesting the use of embassy=embassy
An embassy should instead be tagged embassy=yes, as detailled in the [documentation](https://wiki.openstreetmap.org/wiki/Key:embassy).

### Current situation
For an embassy the following tags are used:
* office=diplomatic
* diplomatic=embassy
* both values embassy=embassy and embassy=yes are proposed to the user

### Proposed evolution
The editor stop to suggest embassy=embassy and only propose the following tags to use, as described in the [documentation](https://wiki.openstreetmap.org/wiki/Key:embassy):
* embassy=yes - an classic embassy with an ambassador
* embassy=high_commission - high commission
* embassy=nunciature - diplomatic mission sent from the Vatican
* embassy=interests_section - a country that represents another sovereign state in a country where it lacks its own diplomatic representation
* embassy=mission - diplomatic mission to or from a multilateral organization such as the United Nations
* embassy=delegation - a delegation is headed by an ambassador
* embassy=branch_embassy - like trade office or cultural centre
* embassy=residence

**Comment by tyrasd** [comment]
Do I understand you correctly that the issue is that the value `embassy` is proposed in the "Type" field of the embassy preset? See screenshot below:

<img src="https://user-images.githubusercontent.com/1927298/148597618-0f970fbe-bc56-426f-ab60-19f9cdca3eb5.png" width="300">

**Comment by overflorian** [comment]
Yes

**Comment by matkoniecz** [comment]
https://github.com/openstreetmap/id-tagging-schema/pull/341 is related

**Comment by overflorian** [comment]
Hi, you closed this issue but I still see the "embassy" value in the form. Should I just wait for your implementation to appear?
Thanks.

**Comment by tyrasd** [comment]
The changes will be published (i.e. made available for the public iD editor) in the next [release](https://github.com/openstreetmap/id-tagging-schema/releases) of this package. I'm still in the process of working through the backlog of the issues of this repository right now, but am planning to publish a release relatively soon (in one or two weeks presumably).
