### ISSUE TITLE
Add preset for `shop=nuts`

### ISSUE THREAD

**Issue by Dimitar5555** [openstreetmap/id-tagging-schema#352]
Is it possible to have a preset for `shop=nuts` despite it's very niche use (206 uses as of `2022-01-11`)?

**Comment by tyrasd** [comment]
Why not…? We have at least one shop preset for `shop=wigs` with even lower usage. :sweat_smile:

**Comment by tyrasd** [comment]
Hm, at first glance, this looks like a bug in the nsi/presets matching of iD, since adding a preset for `shop=nuts` doesn't seem to help.

**Comment by matkoniecz** [comment]
@bhousel 

> I've updated the NSI script to just generate a fallback preset (like shop=yes) if it doesn't match the specific preset in id-tagging-schema that it's looking for.

Is there list of affected ones somewhere? Ideally proper shop values would be used, not `shop=yes`

(I just made PR adding `shop=honey` to iD presets and can make more similar ones)
