### ISSUE TITLE
Deprecate vending=parcel_pickup

### ISSUE THREAD

**Issue by overflorian** [openstreetmap/id-tagging-schema#358]
Hi,
A new tag just [has been approved](https://wiki.openstreetmap.org/wiki/Proposed_features/amenity%3Dparcel_locker): [amenity=parcel_locker](https://wiki.openstreetmap.org/wiki/Proposed_features/amenity%3Dparcel_locker) and describes a parcel locker.
It replaces previously used (and now deprecated) amenity=vending_machine + vending=parcel_pickup

I propose to:
- Stop proposing the preset amenity=vending_machine + vending=parcel_pickup
- Stop proposing the preset amenity=vending_machine + vending=parcel_pickup;parcel_mail_in
- Create a new dedicated preset for amenity=parcel_locker

Thanks

PS: deprecation follow-up (including similar requests to other tools) is available on this wiki page: https://wiki.openstreetmap.org/wiki/Tag:vending%3Dparcel_pickup#Deprecation_follow-up

**Comment by tyrasd** [comment]
this was already implemented in https://github.com/openstreetmap/id-tagging-schema/pull/234

**Comment by overflorian** [comment]
OK that's great, thank you and sorry for the duplicate.
