### ISSUE TITLE
translations are not working

### ISSUE THREAD

**Issue by Mahabarata** [openstreetmap/id-tagging-schema#363]
Hi,

according to this issue #53 and according to this [list](https://github.com/openstreetmap/id-tagging-schema/tree/main/dist/translations), translations for french presets are up to date since yesterday (yay !).

But in ID it doesn't work,

For example for shop=garden_center, the last translation in transifex was made 1 month ago ("Jardinerie"), in the file fr.json the translation is ok but in ID we have the previous translation ("Magasin spécialiste du jardin").

Could you have a look (or explain what's going on) ?

Best regards

**Comment by riQQ** [comment]
Works for me. Have you cleared your caches e.g. by reloading iD via <kbd>Ctrl</kbd> + <kbd>F5</kbd> (Windows / Linux browsers shortcut).

![iD screenshot](https://user-images.githubusercontent.com/3404787/150641658-2b204de2-1a87-47d3-ba54-8349e0f31cfc.png)

**Comment by Mahabarata** [comment]
Oh, yes ! Great ! Thank a lot !
Best regards
