### ISSUE TITLE
Deprecate various building=* values

### ISSUE THREAD

**Issue by maro-21** [openstreetmap/id-tagging-schema#37]
`shop` [9730] → `building=retail`
`factory` [4652] → `building=manufacture`
`abandoned` [4421] → `building=yes + abandoned=yes`
`dwelling_house` [4059] → `building=residential`
`apartment` [2371] → `building=apartments`
`storage` [2159] → `building=warehouse`
`other` [1578] → `building=yes`
`power_substation` [1512] → `building=service + power=substation`
`part` [1193] → `building:part=yes`
`offices` [890] → `building=office`
`House` [853] → `building=house`
`building=building` [840] → `building=yes`
`building=Building` [509] → `building=yes`
`appartment` [441] → `building=apartments`
`Residential` [379] → `building=residential`
`constraction` [335] → `building=construction`
`fixme` [316] → `building=yes + fixme=yes`
`convenience` [197] → `building=retail`
`under construction` [190] → `building=construction`
`shops` [173] → `building=retail`
`appartments` [128] → `building=apartments`
`public_building` [330] → `building=public`
`railway_station` [189] → `building=train_station`
~~`railway` [201] → `building=train_station`~~
`detached_house` [182] → `building=detached`
`services` [137] → `building=service`
`Service` [51] → `building=service`
`comercial` [73] → `building=commercial`
`y` [373] → `building=yes`
`Yes` [78] → `building=yes`
`true` [108] → `building=yes`
`oui` [160] → `building=yes`
`Si` [68] → `building=yes`
`yess` [20] → `building=yes`

Code below.

<details><summary>CODE</summary>
<p>

```
  {
      "old": {"building": "abandoned"},
      "replace": {"building": "yes", "abandoned": "yes"}
  },
  {
      "old": {"building": "apartment"},
      "replace": {"building": "apartments"}
  },
  {
      "old": {"building": "appartments"},
      "replace": {"building": "apartments"}
  },
  {
      "old": {"building": "appartment"},
      "replace": {"building": "apartments"}
  },
  {
      "old": {"building": "Building"},
      "replace": {"building": "yes"}
  },
  {
      "old": {"building": "building"},
      "replace": {"building": "yes"}
  },
  {
      "old": {"building": "comercial"},
      "replace": {"building": "commercial"}
  },
  {
      "old": {"building": "constraction"},
      "replace": {"building": "construction"}
  },
  {
      "old": {"building": "convenience"},
      "replace": {"building": "retail"}
  },
  {
      "old": {"building": "detached_house"},
      "replace": {"building": "detached"}
  },
  {
      "old": {"building": "dwelling_house"},
      "replace": {"building": "residential"}
  },
  {
      "old": {"building": "factory"},
      "replace": {"building": "manufacture"}
  },
  {
      "old": {"building": "fixme"},
      "replace": {"building": "yes", "fixme": "yes"}
  },
  {
      "old": {"building": "House"},
      "replace": {"building": "house"}
  },
  {
      "old": {"building": "offices"},
      "replace": {"building": "office"}
  },
  {
      "old": {"building": "other"},
      "replace": {"building": "yes"}
  },
  {
      "old": {"building": "oui"},
      "replace": {"building": "yes"}
  },
  {
      "old": {"building": "part"},
      "replace": {"building:part": "yes"}
  },
  {
      "old": {"building": "power_substation"},
      "replace": {"building": "service", "power": "substation"}
  },
  {
      "old": {"building": "public_building"},
      "replace": {"building": "public"}
  },
  {
      "old": {"building": "railway_station"},
      "replace": {"building": "train_station"}
  },
  {
      "old": {"building": "Residential"},
      "replace": {"building": "residential"}
  },
  {
      "old": {"building": "services"},
      "replace": {"building": "service"}
  },
  {
      "old": {"building": "Service"},
      "replace": {"building": "service"}
  },
  {
      "old": {"building": "shops"},
      "replace": {"building": "retail"}
  },
  {
      "old": {"building": "shop"},
      "replace": {"building": "retail"}
  },
  {
      "old": {"building": "Si"},
      "replace": {"building": "yes"}
  },
  {
      "old": {"building": "storage"},
      "replace": {"building": "warehouse"}
  },
  {
      "old": {"building": "true"},
      "replace": {"building": "yes"}
  },
  {
      "old": {"building": "under construction"},
      "replace": {"building": "construction"}
  },
  {
      "old": {"building": "yess"},
      "replace": {"building": "yes"}
  },
  {
      "old": {"building": "Yes"},
      "replace": {"building": "yes"}
  },
  {
      "old": {"building": "y"},
      "replace": {"building": "yes"}
  },
```
</p>
</details>

**Comment by westnordost** [comment]
There is also `building=semi`, quite well used actually. But according to the [wiki page](https://wiki.openstreetmap.org/wiki/Tag%3Abuilding%3Dsemi), it is most probably a synonymous for `semidetached_house`.
StreetComplete treats `semi` as synonym to it.

**Comment by matkoniecz** [comment]
Disclaimer: not a native speaker, may be wrong

>  factory [4652] → building=manufacture

I would say that factory is a subset of manufacture (large scale one) 

>  storage [2159] → building=warehouse

I think that not every kind of storage is a warehouse.

**Comment by quincylvania** [comment]
@maro-21 Are you going to open a PR?

**Comment by peternewman** [comment]
> > @maro-21 Are you going to open a PR?
> 
> I'm sorry but I can't make pull requests. That's why I pasted the code.

@maro-21 for future info you can add simple content like this directly on the website needing nothing more than you did to comment on this issue:
https://guides.github.com/activities/hello-world/#commit
