### ISSUE TITLE
Consider removing deprecation of amenity=dancing_school

### ISSUE THREAD

**Issue by tyrasd** [openstreetmap/id-tagging-schema#373]
See https://github.com/openstreetmap/iD/pull/6251#issuecomment-487589188 and following comments.

This would involve the following changes:

* drop the deprecation of `amenity=dancing_school`
* change the "Dance School" preset to use `amenity=dancing_school` as its tag
* (optional) add a field to indicate that a "Dance Hall" also offers lessons (`dance:teaching=yes`)

**Comment by matkoniecz** [comment]
see also https://www.openstreetmap.org/changeset/114834704

**Comment by simonpoole** [comment]
General remark: could we be somewhat more conservative with "deprecating" stuff in general (in this case it was always clearly wrong). There is no agreed on process for deprecating tags, which does not mean that it is never a good idea, but simply something snuck in to a tagging proposal should not be enough.  See also https://www.openstreetmap.org/user/Mateusz%20Konieczny/diary/398555#comment51838

**Comment by mnalis** [comment]
(ref: https://community.openstreetmap.org/t/list-of-deprecated-tags-linked-to-the-new/96737)
