### ISSUE TITLE
Add automatic operator/brand wikidata presets to `amenity=telephone`

### ISSUE THREAD

**Issue by PeterLeGras** [openstreetmap/id-tagging-schema#397]
It would be nice if `amenity=telephone` would have operator presets based on wikidata in the same way that substations, power poles, ATMs, post drop boxes, certain stores etc have prefilled wikidata for popular operators.
![image](https://user-images.githubusercontent.com/52308086/152997340-99e8b1c9-b768-4bda-9a89-303cdb5cdb2b.png)

For example I imagine that typing "Telstra" would bring up a preset for public telephone rather than just their store outlet.
![image](https://user-images.githubusercontent.com/52308086/152997236-5e8b04e9-1088-40c8-a29d-6b30be5e00f5.png)

In Australia, all public phones have the same operator and this would make it significantly less painful to add wikidata to them.

**Comment by tordans** [comment]
My understanding is, that this needs to happen in https://github.com/osmlab/name-suggestion-index.

The data in your example is from https://nsi.guide/?t=brands&tt=telstra, for example.

**Comment by PeterLeGras** [comment]
Thank you, that is enlightening. That is definitely what I am after.

**Comment by bhousel** [comment]
Yes, this was just opened in the NSI repo recently.. I'll add the category 👍
