### ISSUE TITLE
Describe shop=yes as "Unspecific shop"

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/id-tagging-schema#399]
Right now there is no good hint that `shop=yes` is a poor tagging and something specific would be better.

Maybe have weaker form of complaint like one appearing for ways not tagged alone and not being part of relations?

(BTW, the same could be useful for `office=yes)

**Comment by bhousel** [comment]
Wait no, it's not an "unspecific shop".. 
It's just a shop type that doesn't have a preset yet.

Please don't do this - people will see "unspecific shop" and use it for things like "variety store" or "general store".

**Comment by matkoniecz** [comment]
I am not experienced with iD code, but is the new presets going to match say `shop=magic_items`? I expect it to match just `shop=yes` when there are no tags putting it into other preset.

>  It's just a shop type that doesn't have a preset yet.

Vast majority of `shop=yes` that I have seen have iD preset, just mapper have not used them (though it is biased by fact that I keep reporting missing values for inclusion if spotted)

**Comment by bhousel** [comment]
> I am not experienced with iD code, but is the new presets going to match say `shop=magic_items`? I expect it to match just `shop=yes` when there are no tags putting it into other preset.

This type of preset is a fallback preset that matches `shop=*` when there is no better match.
It will show a "Type" field so user can supply any tag they like (or choose from the taginfo-seeded list).

<img width="300" alt="Screen Shot 2022-02-14 at 11 38 50 AM" src="https://user-images.githubusercontent.com/38784/153906728-0d27f9cb-af18-4239-b818-61d0b29ab4d6.png">

**Comment by tyrasd** [comment]
In 1527ba5a4e4d60fd0300112507d8b869f77e537a I went with the title `Shop (Unspecified Type)`, which is the same wording the [wiki uses](wiki.openstreetmap.org/wiki/Tag:shop=yes): _A shop of unspecified type […]_

It's also not searchable, so only existing features are matched with the preset.

Sorry for not making this clear when closing the issue from the commit.

> Please don't do this - people will see "unspecific shop" and use it for things like "variety store" or "general store".

Do you still think this will be an issue?

**Comment by bhousel** [comment]
> In [1527ba5](https://github.com/openstreetmap/id-tagging-schema/commit/1527ba5a4e4d60fd0300112507d8b869f77e537a) I went with the title `Shop (Unspecified Type)`, which is the same wording the [wiki uses](wiki.openstreetmap.org/wiki/Tag:shop=yes): _A shop of unspecified type […]_

Oh I see now.. I thought you were changing the wording on the fallback "Shop" preset.  I didn't realize you were making a new unsearchable preset that matches a literal `shop=yes` tag.

> Do you still think this will be an issue?

I guess it's not as bad, since people wouldn't be choosing this as a preset.

**Comment by 1ec5** [comment]
Apparently it [used to be common](https://wiki.openstreetmap.org/wiki/Talk:Homonymous_keys#shop.3Dyes) to add `shop=yes` alongside `amenity=fuel` to indicate that there’s a convenience store attached to the gas station. I don’t think we should encourage that practice anymore, but if a feature like that is selected, would iD continue to show the Gas Station preset, or would it now show the “Shop (Unspecified Type)” preset?

**Comment by tas50** [comment]
That's still pretty common around the US, but those should really get split out to proper convenience store tags so they'd show up in a search for convenience stores.

**Comment by 1ec5** [comment]
Agreed, though it would be mildly confusing if they started getting identified as unclassified shops[^unclassified] instead of gas stations.

[^unclassified]: If only we didn’t have `highway=unclassified`, it wouldn’t be so confusing to call this preset “Unclassified Shop”, which reads nicer without the parentheses.

**Comment by bhousel** [comment]
> if a feature like that is selected, would iD continue to show the Gas Station preset, or would it now show the “Shop (Unspecified Type)” preset?

Could add a `matchScore`
https://github.com/ideditor/schema-builder#matchscore

**Comment by matkoniecz** [comment]
Or make all unsearchable presets to rank below searchable ones of the same `matchScore`?

**Comment by tyrasd** [comment]
> `shop=yes` alongside `amenity=fuel` […] would iD continue to show the Gas Station preset, or would it now show the “Shop (Unspecified Type)” preset?

good point. 305e689 assures that iD will always choose a "regular" preset over the `*=yes` ones.

> Or make all unsearchable presets to rank below searchable ones of the same `matchScore`? (if not done already)

As far as I can see, this is currently not the case. But it sounds like a good suggestion in general.
