### ISSUE TITLE
stop "COVID-19 Pandemic Hours" field being shown if `opening_hours:covid19` is not present

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/id-tagging-schema#401]
At this point it is clear that COVID19 is not going to disappear and changed opening hours should be tagged in `opening_hours`

There is no point in encouraging people to fill this field

![screen01](https://user-images.githubusercontent.com/899988/153761662-33bfe153-cfa5-44f9-bb1d-3f8fa309171a.png)

**Comment by tyrasd** [comment]
This request is reasonable, but I think that editors should not be the first to implement this change.

If there is consensus (which I would assume there is), a start would be to update the various pages on the osm wiki to reflect this new way of handling this topic. Afterwards, we can update the presets here.

**Comment by matkoniecz** [comment]
Modified https://wiki.openstreetmap.org/wiki/Key:opening_hours:covid19 a bit, posted to tagging mailing list

**Comment by matkoniecz** [comment]
It seems that there is a clear support for stopping promotion of that tag, at least I interpreted it this way.

**Comment by matkoniecz** [comment]
Can someone else review https://lists.openstreetmap.org/pipermail/tagging/2022-February/thread.html#63959 and judge is there consensus to stop prominent promotion of that tag?

Note also that recently many places started dropping COVID restrictions, at least for now. And I think that noone expects COVID19 to be fully eradicated any time soon.

**Comment by mxxcon** [comment]
Unless I missed some messages or misunderstood meaning, I didn't see anyone saying this field should remain.

**Comment by tyrasd** [comment]
[4de347d](https://github.com/openstreetmap/id-tagging-schema/commit/4de347dd48b01206266b86e9fc35cc492e36fa4e) starts the phasing out of this field by making the field an optional (`moreFields`) field which is not shown by default when selecting a preset. This approach allows mappers to easily see now potentially outdated pandemic opening hours and check/update/fix/convert them accordingly.

PS: Here's a current usage graph of the tag:

![image](https://user-images.githubusercontent.com/1927298/169560446-904d3539-d969-44b9-aa25-bd49c2656b1b.png)

I tend to keep the field around until we have at least one of the following:

* the tag's status is deprecated on the wiki
* there is significant drop in usage compared to the current numbers and negative trend
* usage of the tag remain stagnant for a longer time (~1 year)

**Comment by matkoniecz** [comment]
Not sure whether we will reach any time soon a situation where this tag should be removed on sight which would justify a deprecation rule. 

> There is no point in encouraging people to fill this field

This is achieved, so I will close this issue.

> there is significant drop in usage compared to the current numbers and negative trend

Though for the love of all what is holy: do not try to run undiscussed bot/mass edits to achieve this! Consult with local community before doing this.
