### ISSUE TITLE
Use dedicated bicycle parking icon

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/id-tagging-schema#402]
For example https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/amenity/bicycle_parking.svg could be used

![screen02](https://user-images.githubusercontent.com/899988/153761759-dec43287-7214-4af7-a49f-4c23a2427466.png)

Part of #41 where I have a specific idea for a fix

**Comment by matkoniecz** [comment]
P seems more recognizable, but in most cases there is text already and other context, so it is not so bug problem I guess

**Comment by tyrasd** [comment]
what we have to keep in mind is that the icons on the map are rendered quite small, which makes using icons with fine details (like the bike symbol in the corner of the `P` in <img src="https://raw.githubusercontent.com/gravitystorm/openstreetmap-carto/1178dfba278f1eee0ce018f72bcc88b5596d2929/symbols/amenity/bicycle_parking.svg" height="30px">) pretty hard to discern. Here's how it would approximately look on the map in iD:

<img src="https://user-images.githubusercontent.com/1927298/153916922-a8c1d103-07d8-4396-9931-363658dc65d2.png" width=80px>

**Comment by tyrasd** [comment]
added in #460
