### ISSUE TITLE
Stuck in the sand bunker

### ISSUE THREAD

**Issue by davidpnewton** [openstreetmap/id-tagging-schema#409]
This is a companion issue to 9000 in the main iD repository.

There has been some progress on the issue of tagging for the renderer and golf features. The grass features have been dealt with by #203, but that still leaves the issue of golf bunkers.

The wiki says, "A type of hazard, also known as a sand trap, which is a depression in the ground filled with sand. Recommended to also tag with surface=sand or natural=sand. Do not use natural=beach--it's not a beach!"

So at the moment like the issue with grass golf features iD appears to arguably not be following conventions. The renderer is not rendering bunkers without natural=sand as golf features in the editing portion. The validator is further suggesting that natural=sand be added so that both surface=sand and natural=sand are present.

This is causing people like DaveF to still go on a crusade to remove this tagging from bunkers and thus producing massive edits both in number of alterations and area covered:

https://www.openstreetmap.org/changeset/117492432

1722 affected ways in that edit covering essentially the whole of England.

In this case iD is nearer to the wiki in its treatment of the situation, but issues are still being caused and edit wars with massive, inappropriately-sized edits are occurring.

From a semantic point of view I'd argue that tagging natural=sand is not correct, but iD is not the only editor to do this. Vespucci also sets natural=sand for golf bunkers as does JOSM. So the case is less clear-cut than for tees, fairways and greens etc.

In the case of the validator and the iD tagging when creating a golf bunker it tags golf=bunker and natural=sand. That is perfectly in line with the wiki's description. Taginfo also has overwhelming use of natural=sand at 402,000 v surface=sand at 60,000.

For me two alterations need to happen, one of which is within the purview of the tagging schema. At the moment where tagging is golf=bunker and surface=sand the validator prompts to add natural=sand. The change I would like to see is the validator prompting to add natural=sand but also removing surface=sand when doing so.

Alternatively if DaveF's opinion is to dominate then the validator should flag natural=sand and replace it with surface=sand for golf bunkers.

I would prefer natural=sand to prevail as only having that tag is in line with the wiki but also does not conflict with other commonly used editors.

The second alteration is for DaveF to stop mass-editing across the whole of the UK as a crusade!

**Comment by matkoniecz** [comment]
> The second alteration is for DaveF to stop mass-editing across the whole of the UK as a crusade!

If that is an actual problem and there is consensus in UK community that such edits are unwanted: revert them and contact DWG ( https://wiki.openstreetmap.org/wiki/Data_working_group ). Rather than making issues at iD preset issues tracker.

**Comment by tyrasd** [comment]
let's "fix" this in #534
