### ISSUE TITLE
"Gas Pump" preset clarifications

### ISSUE THREAD

**Issue by cmoffroad** [openstreetmap/id-tagging-schema#411]
The Gas Pump preset automatically includes amenity=vending_machine+vending=fuel

Is this supposed to be micro-mapped for an individual gas pump inside a "Gas station" (amenity=fuel), or for a standalone automated vending machine(s) point of sales ?

https://wiki.openstreetmap.org/wiki/Tag:vending%3Dfuel
has this confusing statement: "To avoid tag conflicts, a fuel station sells fuel using a fuel vending machine, it's good to mark it as [amenity](https://wiki.openstreetmap.org/wiki/Key:amenity)=[fuel](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dfuel) + [vending_machine](https://wiki.openstreetmap.org/wiki/Key:vending_machine)=yes."

**Comment by matkoniecz** [comment]
> Is this supposed to be micro-mapped for an individual gas pump inside a "Gas station" (amenity=fuel)

yes

> or a standalone automated vending machine(s) point of sales ?

In which case it would not be inside `amenity=fuel`? Or part of `shop=fuel`?

**Comment by cmoffroad** [comment]
> In which case it would not be inside `amenity=fuel`? Or part of `shop=fuel`?

Not always. I was looking to tag small-capacity roadside vending machines selling gas (common in developing countries).
Sometimes they are found in front of grocery stores, but often they are on their own on the side of the road and not part of any shop.

They have a small capacity and are only typically used to refill motorcycles, hence the need to differentiate tags from a standard retail gas station.

**Comment by tyrasd** [comment]
> Is this supposed to be micro-mapped for an individual gas pump inside a "Gas station" (amenity=fuel)

As I read the wiki page, that tag is not meant to be used for micromapping of gas pumps inside as gas station. Or, at least it would be limited to the special pumps of a gas station that are operated like a vending machine (self-service, payment directly at the pump).

_Gas Pump_ doesn't seem like a very good name for these, does it? Maybe _Gas Vending Machine_ would be better?

**Comment by Dimitar5555** [comment]
Or *Fuel Vending Machine* and additional preset for *Fuel Pump* (`man_made=fuel_pump`)?

**Comment by cmoffroad** [comment]
@Dimitar5555, I appreciate your pull request! It effectively addresses the problem where micro-mapped pumps and standalone vending machines were previously referred to using the same or similar tags in the wiki. With your contribution, we now have a clear distinction through two separate presets, namely "Gas Vending Machine" and "Gas Vending Pump."

PS: Have you thought about keeping the original "Gas Pump" label for the latter option?

**Comment by Dimitar5555** [comment]
@cmoffroad The PR uses "Gas" for both presets since this is what was used in the original preset.

**Comment by Dimitar5555** [comment]
Thank you for the note! I've updated the PR accordingly.

**Comment by cmoffroad** [comment]
@Dimitar5555, my apologies, I got the names mixed up while reviewing the PR diffs.

Personally, I would prefer to see "Gas Vending Machine" instead of "Gas Vending Pump." The reason being, "Pump" typically signifies an individual "Gas Pump" (`man_made=fuel_pump`), whereas a machine could encompass multiple pumps (as seen in the thumbnail picture here: https://wiki.openstreetmap.org/wiki/Tag:vending%3Dfuel).

PS: We are currently discussing this and other related gas station topics at the following link. Please feel free to join the conversation; your feedback is highly valuable! https://community.openstreetmap.org/t/differing-approaches-to-tagging-vending-machines-for-motor-fuel-dispensing-have-caused-confusion/103421/26

**Comment by Dimitar5555** [comment]
> Personally, I would prefer to see "Gas Vending Machine" instead of "Gas Vending Pump." The reason being, "Pump" typically signifies an individual "Gas Pump" (`man_made=fuel_pump`), whereas a machine could encompass multiple pumps (as seen in the thumbnail picture here: https://wiki.openstreetmap.org/wiki/Tag:vending%3Dfuel).

That is already addressed. The preset name is "Gas Vending Machine" for the vending machine and "Gas Pump" for `man_made=gas_pump`.

> PS: We are currently discussing this and other related gas station topics at the following link. Please feel free to join the conversation; your feedback is highly valuable! https://community.openstreetmap.org/t/differing-approaches-to-tagging-vending-machines-for-motor-fuel-dispensing-have-caused-confusion/103421/26

I've left a reply on that topic.
