### ISSUE TITLE
`highway=service` areas neither provided nor accepted

### ISSUE THREAD

**Issue by ManDay** [openstreetmap/id-tagging-schema#431]
Carto renders `area=yes; highway=service`, but iD suggests `area:highway=service` for the "Road Area" preset and complains about the former not being a line.

**Comment by ManDay** [comment]
It may not be exactly canon, but I subscribe to the perspective that OSM effectively encodes a vectorized (as opposed to voxel/pixelized) volume/surface description, to the effect that both lines and areas are nothing but some arbitrary building blocks for that description.

When a surface area is too complex to be described by a line (pretty much everything which is not "road shaped", i.e. translational symmetry along a line), an area has to be used.

So, bluntly put, I think **everything** which exists as a `area=no` should, in theory, also be supported as an `area=yes` for cases where the shape of the entity demands it. So something like `highway=path` with `area=yes` does make sense, although it is perhaps uncommon. In the end, your call which combinations you deem relevant enough to support them as a distinct rendering. In my personal opinion, `highway=service` with `area=yes` is fairly common, though.

**Comment by matkoniecz** [comment]
> So, bluntly put, I think everything which exists as a area=no should, in theory, also be supported as an area=yes for cases where the shape of the entity demands it.

This is blatantly wrong.

Mapping for example area of motorway carriageway is done with `area:highway=motorway` not `highway=motorway + area=yes`

Mapping area of tree row is done with `landuse=forest` not `natural=tree_row + area=yes`

Mapping area of `waterway=river` is not done with `waterway=river + area=yes`

`highway=service` + `area=yes` is widely misused where `area:highway=*` should be used.

**Comment by ManDay** [comment]
I think these are separate tags, though I agree I wasn't precise enough when I said "surface description".

`area:highway=*` is to designate the **surface material** associated with a `highway=*` path (of an `area=no` highway), whereas `highway=*; area=yes` is to designate the **surface usage** (of an `area=yes` highway).

You are correct w.r.t. the forest, but I already said that my view is not strictly canon (and tagging schemes are a matter of frequent dispute anyway).

I think the description I gave is simple, consistent, and compatible with the existing `area:highway=*` and `highway=*` semantics, therefore it makes sense to adopt it. The fact that other tags (like the forest example) are not necessarily compatible and sometimes messy notwithstanding.

**Comment by matkoniecz** [comment]
> area:highway=* is to designate the surface material associated with a highway=* path (of an area=no highway), whereas highway=*; area=yes is to designate the surface usage (of an area=yes highway).

That is completely wrong and is your personal tagging idea.

Mapping for example area of motorway carriageway is done with `area:highway=motorway` not `highway=motorway + area=yes`

`highway=motorway + area=yes` is a clear tagging mistake.

**Comment by ManDay** [comment]
No, what you quoted is actually established practice (and described in the [wiki](https://wiki.openstreetmap.org/wiki/Key:area:highway)). What you say about a motorway is correct but is in no contradiction to what I said. The fact that you will rarely to never find the specific combination `highway=motorway; area=yes` is because motorway usage is inherently linear. A motorway therefore does not require the semantics I described (where usage is of the kind `area=yes`), but you shouldn't dismiss the principle just because you found an example to which it does not apply.

**Comment by matkoniecz** [comment]
You claimed general rule covering everything:

> So, bluntly put, I think **everything** which exists as a `area=no` should, in theory, also be supported as an area=yes

bolding original from https://github.com/openstreetmap/id-tagging-schema/issues/431#issuecomment-1126297896

> because motorway usage is inherently linear

not on toll plazas ( https://commons.wikimedia.org/wiki/File:%C3%9Ajharty%C3%A1n_l%C3%A9gifot%C3%B3.jpg ), motorway air strip sections and numerous other places

(I will unsubscribe as it is getting quite offtopic here, sorry)

**Comment by ManDay** [comment]
Yes, that's correct. That's what I claimed should be supported. And if you agree that there are features where usage is not a network of linear paths (which, by the way, I suppose might still the case for many toll stations, though), then indeed, that would be a case where `highway=motorway; area=yes` is appropriate. Again, that is in accordance with what's written on the wiki.

Perhaps it would help if you could clearly formulate the objection that you have in the sense of "if that is done like X, then Y breaks", or something of the sorts. I'm afraid I have not exactly understood why you started this discussion.

**Comment by tyrasd** [comment]
@ManDay I appreciate your enthusiasm, but this issue is not a good place to discuss potential changes to the way the OSM tagging system. Please consider moving the discussion to a place like the tagging mailing list for example.

<hr>

Back on topic:

I found that there are two more `highway` values which are documented to be allowed on areas, although they both seem to be somewhat unclear or controversial situations:
* [`highway=footway`](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dfootway#Areas) – quote: _There is no clear consensus on this topic_ 
* [`highway=unclassified`](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dunclassified) – the wiki is slightly inconsistent on this one: the [`highway=*` overview page](https://wiki.openstreetmap.org/wiki/Key:highway) lists the `unclassified` as a line-only tag

**Comment by matkoniecz** [comment]
> [highway=unclassified](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dunclassified) – the wiki is slightly inconsistent on this one: the [highway=* overview page](https://wiki.openstreetmap.org/wiki/Key:highway) lists the unclassified as a line-only tag

this seems clearly wrong, I edited wiki: https://wiki.openstreetmap.org/w/index.php?title=Tag%3Ahighway%3Dunclassified&type=revision&diff=2326550&oldid=2310410

> [highway=footway](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dfootway#Areas) – quote: There is no clear consensus on this topic

in some areas people widely use `area=yes + highway=footwat/pedestrian` to map areas of sidewalks.

**Comment by ManDay** [comment]
It was not my idea to start this discussion. I just tried to respond to @matkoniecz when they started criticizing my perspective. I think the issue which I filed about `highway=service; area=yes` is not at all proposing any changes to the tagging system. It is well confirmed by practice, wiki, and carto.

**Comment by richlv** [comment]
Thank you for fixing this. With iD complaining about highway=service + area=yes, people went around "fixing" such occurrences, in most cases breaking things - that is, instances where an area was mapped, not outline of a linear way.
