### ISSUE TITLE
hot_spring

### ISSUE THREAD

**Issue by Mahabarata** [openstreetmap/id-tagging-schema#436]
Hi,

According to the wiki : https://wiki.openstreetmap.org/wiki/Tag:natural%3Dhot_spring, a hot spring may be on a node or on an area : the picture on the right shows for example the hot_spring lake of Grand Prismatic in Yellowstone National Park.

But in iD, when we add the tags natural=hot_spring to an area, we have a warning message saying that this tag is only for nodes.

Could you fix that ?

Best regards

**Comment by danieldegroot2** [comment]
This seems to have been changed from `area` to `point` in https://github.com/openstreetmap/iD/commit/1c3928160f68734aedadf977b723c833e8b19791
(perhaps by mistake, as the wiki page has had both since it was created.)

**Comment by Mahabarata** [comment]
Thanks for your work
Best regards
