### ISSUE TITLE
Potential new validation rules?: information=* => board_type=*

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/id-tagging-schema#45]
It seems between 2009 and 2010 the tagging scheme changed a bit from `information=nature` to `information=board` + [`board_type=nature`](https://wiki.openstreetmap.org/wiki/Key:board_type).

I found this by looking to this chart: https://taginfo.openstreetmap.org/tags/information=nature#chronology
And checking an old wiki version of the corresponding template from that time ([third last table-line](https://wiki.openstreetmap.org/w/index.php?title=Template:Map_Features:information&diff=228009&oldid=228002)) gives a quite good evidence.

Would that justified for deprecating this tag & and add a new validation rule?

Seems there are also other combinations with , `history` and `wild_life` / `wildlife`, compare same old wiki version and [taginfo information values](https://taginfo.openstreetmap.org/keys/information#values).

Edit:

Similar for `hikingmap` & `citymap`, but this changed from
`information=hikingmap` to `information=map` + `hiking=yes` + `map_type=topo`
`information=citymap` to  `information=map` + `map_size=city` + `map_type=street`

So, also osm-carto would show more specific icons on the map after these tag upgrades :-)

**Comment by tyrasd** [comment]
The two map examples are even documented as "possible mistagging" on the wiki: https://wiki.openstreetmap.org/wiki/Tag:information%3Dmap#Possible_Mistagging

I think adding these to the list of upgradable tags would be certainly beneficial. :+1:

**Comment by Hufkratzer** [comment]
If you upgrade
> information=hikingmap to information=map + hiking=yes + map_type=topo

then hiking=yes should also be visible and editable in the presets for [information=map (preset)](https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/tourism/information/map.json).

The same for information=bicyclemap -> bicycle=yes

And also analogously for [guidepost (wiki)](https://wiki.openstreetmap.org/wiki/Key:guidepost): 
guidepost=hiking -> hiking=yes
guidepost=bicycle -> bicycle=yes
etc.

The advantage is that a guidepost or map can have more than one of the *=yes tags at one time (avoiding a semicolon-separated list), see [information=guidepost#Examples (wiki)](https://wiki.openstreetmap.org/wiki/Tag:information=guidepost#Examples)

But there may be opposition to use hiking=yes, bicycle=yes, mtb=yes, horse=yes etc. this way; compare old closed issue https://github.com/openstreetmap/iD/issues/3832
