### ISSUE TITLE
Remove `name` field from `building=garages` and `building=garage`

### ISSUE THREAD

**Issue by Dimitar5555** [openstreetmap/id-tagging-schema#450]
https://taginfo.openstreetmap.org/tags/building=garages
771k uses of which 4 430 have `name` (~0.6%)

https://taginfo.openstreetmap.org/tags/building=garage
5768k uses of which 9 134 have `name` (~0.2%)

**Comment by bryceco** [comment]
Those percentages are off by x100. Should be 0.6% and 0.2%.

**Comment by Dimitar5555** [comment]
I also noticed that they seem odd but I wasn't sure what's wrong. Thanks for pointing it out. I've updated them.

**Comment by tyrasd** [comment]
the name field was moved to an optional field in #423 for garage(s).
