### ISSUE TITLE
Addition of Services field for bicycle on shops

### ISSUE THREAD

**Issue by brierjon** [openstreetmap/id-tagging-schema#464]
Mostly applicable to shop=bicycle, shop=outdoor, shop=sports the bicycle services keys should be displayed for these shop types. https://wiki.openstreetmap.org/wiki/Key:service:bicycle and could replace #43, but is different in that adding services would not change the primary label for the store type. Changing on tag combination if desired could be separate logic than needed to add a field to answer yes/no for each of these tags.

- [service:bicycle:retail](https://wiki.openstreetmap.org/wiki/Key:service:bicycle:retail)=* 
- [service:bicycle:repair](https://wiki.openstreetmap.org/wiki/Key:service:bicycle:repair)=*
- [service:bicycle:rental](https://wiki.openstreetmap.org/wiki/Key:service:bicycle:rental)=*
- [service:bicycle:pump](https://wiki.openstreetmap.org/wiki/Key:service:bicycle:pump)=*
- [service:bicycle:diy](https://wiki.openstreetmap.org/wiki/Key:service:bicycle:diy)=*
- [service:bicycle:cleaning](https://wiki.openstreetmap.org/wiki/Key:service:bicycle:cleaning)=*
- [service:bicycle:second_hand](https://wiki.openstreetmap.org/wiki/Key:service:bicycle:second_hand)=*

Example for inclusion of outdoor shops as [REI](https://nsi.guide/index.html?t=brands&k=shop&v=outdoor&tt=rei) has [ bike shops](https://www.rei.com/stores/bike-shop) offering bicycle repair services.

Example for inclusion of sports shops as [Dicks Sporting Goods]() has [bike repair](https://www.dickssportinggoods.com/s/bike-services) as a service.

Having the ID UI expose these tags in a structured field either starting with "unknown" and accommodating yes/no/only/separate depending on the tag's scope.

Currently these only display in the tags field, but are useful metadata to have about bicycle services.
![image](https://user-images.githubusercontent.com/717866/169611357-4cc08b53-5df9-4300-b0db-d966558937e3.png)

**Comment by 1ec5** [comment]
The existing Services field for `service:bicycle:*` would be added to the Sports Store and Outdoors Store presets, which are what stores like [Dick’s](https://nsi.guide/index.html?t=brands&k=shop&v=sports&tt=dick#dickssportinggoods-89ce6f) and [REI](https://nsi.guide/index.html?t=brands&k=shop&v=outdoor&tt=rei#rei-72e82e) are using:

https://github.com/openstreetmap/id-tagging-schema/blob/257b06edb102425edb7eb9d276e13f7b178f994d/data/fields/service/bicycle.json#L2 https://github.com/openstreetmap/id-tagging-schema/blob/257b06edb102425edb7eb9d276e13f7b178f994d/data/presets/shop/sports.json#L3-L8 https://github.com/openstreetmap/id-tagging-schema/blob/257b06edb102425edb7eb9d276e13f7b178f994d/data/presets/shop/outdoor.json#L3-L6

To avoid confusion, the field should probably be renamed to Bicycle Services.
