### ISSUE TITLE
Individual items of playground=* and area=

### ISSUE THREAD

**Issue by imagoiq** [openstreetmap/id-tagging-schema#466]
Hi,

I would to clarify the usage of `leisure=playground` and `playground=*`. As stated in the wiki, it seems possible to tag some individual devices with an area, but there is a very explicit warning when I try to do it.
At the same time, this behaviour is flagged as an error on Osmose, so I opened a similar ticket: https://github.com/osm-fr/osmose-backend/issues/1457 The error is a bit different: Osmose flag an area without certain tags as an error : https://github.com/osm-fr/osmose-backend/blob/master/plugins/TagFix_Area.py#L30

![Screenshot 2022-05-23 at 17-43-25 OpenStreetMap](https://user-images.githubusercontent.com/12294151/169861336-77fbecb6-0e51-4734-8570-5aff8e067b3b.png)

I'm a bit confuse and not sure what it's the appropriate way to tag them, and if it's a mistake on the schema or a personal one.

**Comment by matkoniecz** [comment]
it is kind of extreme nanomapping, but it does not seem wrong

**Comment by danieldegroot2** [comment]
From my time mapping them (correct it where needed).

[playground](https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dplayground) / [equipment](https://wiki.openstreetmap.org/wiki/Key:playground)
Line and area mapping of playground equipment _is possible_, but is mainly intended for the playground equipment itself -not the surface around it- and is usually used on structures, to detail the individual parts. It is still uncommon, as this is mostly done when aerial imagery has a high resolution.
> Each item of play equipment is tagged as a node, way or area **depending on its shape and size**

So if seperate (from a structure) I would not tag these as ways or areas.

Playground(s)...
- If they are inside a `leisure=playground`
-- Individual surfaces around each piece of equipment can be mapped as an area `area=yes` + `surface` .
-- Individual pieces of equipment can be mapped as a node `playground`.
- If it is a standalone piece of equipment on ie. some grass in a residential area, you can map it as you do in a playground, but without any `leisure=playground` area. [1]
- If they are _inside_ a [`leisure=schoolyard`](https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dschoolyard) (my personal choice)
-- Individual surfaces around each piece(s) of equipment can be mapped as an area **`leisure=playground`** + `surface`.
--- You may choose to map these as inners of the schoolyard, but a regular area is also ok.
-- Individual pieces of equipment can be mapped as a node `playground`.

Sidenotes:
- `leisure=playground` overlapping/inside another `leisure=playground` is, at least technically, a duplicate (one object, one osm object(/tag))
- It is disputed to use `playground` on `leisure=playground` to indicate multiple pieces of equipment inside the area; it is unclear where the equipment is located -it is usually visible on imagery-, which does not add to the map.
-- [1] `playground` to indicate a single piece of equipment is ok, but you could argue `leisure=playground` (when mapped as area) for this is redundant (and tagging for the renderer) and would have to be ideally named/signed (like with man_made=bridge being disputed).

**Comment by imagoiq** [comment]
Thanks for this complete explanation!


> Line and area mapping of playground equipment is possible, but is mainly intended for the playground equipment itself 

Ok It makes sense. By the way, do you know if there is a way to tag the surface only underneath?

**Comment by tyrasd** [comment]
the wrong warning should be fixed with f2629f5

**Comment by danieldegroot2** [comment]
> do you know if there is a way to tag the surface only underneath?
Nah, make an area for the general surface around the piece of equipment, as I mentioned. If you want to go as far as tag the surface underneath the seats of the seesaw, yea you can make little areas for that too. Again, might want to make it a multipolygon because it's an area inside another area. But yeah, that's another way of micromapping it further.
