### ISSUE TITLE
New fields might not be linked correctly

### ISSUE THREAD

**Issue by arch0345** [openstreetmap/id-tagging-schema#468]
_Originally posted by @Dimitar5555 in https://github.com/openstreetmap/id-tagging-schema/pull/453#issuecomment-1137692260_

It looks like the new fields are not linked correctly. None of them show up in the iD instance on openstreetmap.org nor in version that is published on https://ideditor.org/latest-id/. These are the messages that appear in the console and they are mostly identical for all types of crossings.
![image](https://user-images.githubusercontent.com/19364673/170337954-8d5b89a4-5bdc-48e9-bf1e-c81d76a8f15e.png)

**Comment by tyrasd** [comment]
It looks like our CDN still had the old version of the `fields` data in cache. I've manually refreshed it now. Clearing your browser cache and reloading iD should make the fields available for you. 

See https://github.com/openstreetmap/iD/issues/8909 for a fix which would prevent such issues in the future.
