### ISSUE TITLE
Golf Cartpath is insufficiently distinguished from service roads for cars

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/id-tagging-schema#48]
The Golf Cartpath preset adds a `highway=service` tag, relying on `golf=cartpath` and `golf_cart=designated` to distinguish the path from a regular motorized service road:

https://github.com/openstreetmap/id-tagging-schema/blob/0df7b20019c48c969fa9f9124724117de321f563/data/presets/golf/cartpath.json#L14-L16

openstreetmap/iD#6165 added the `highway=service` tag to the preset because major renderers weren’t on board with rendering `golf=cartpath` specifically, for example in gravitystorm/openstreetmap-carto#3734. Unfortunately, the workaround of adding `highway=service` creates ambiguity for routers, which are no more likely to special-case `golf=cartpath`. `golf_cart=designated` means the path is intended for use by golf carts, but routers can’t assume that ordinary motor vehicles are banned from these paths. (In fact, `golf_cart=designated` could apply to an ordinary `highway=residential` in a golf club community, or to any low-speed public street [in Ohio](https://www.theintelligencer.net/news/community/2016/12/golf%u2008carts-legal-on-ohio%u2008streets-beginning-sunday/).)

A quick fix would be to [add `motor_vehicle=no`](https://www.openstreetmap.org/way/805817989) to this preset. This will prevent routers from potentially sending full-size vehicles down narrow, winding, and [sometimes impassable](https://www.mlive.com/news/2020/11/amazon-driver-takes-wrong-turn-onto-michigan-golf-course-wedges-truck-in-cart-tunnel.html) paths designed for tiny golf carts. (A golf cart is a kind of motor vehicle, but `golf_cart=designated` will override `motor_vehicle=no`.) However, for all I know, some mappers could disagree with tagging access restrictions that in many cases may be implicit. After all, there’s no guarantee that a golf course would post [<img src="https://upload.wikimedia.org/wikipedia/commons/b/bb/MUTCD_R5-3.svg" width="24" alt="No Motor Vehicles" align="top">](https://commons.wikimedia.org/wiki/File:MUTCD_R5-3.svg) signs all over.

In the long term, it may be worth getting the community on board with a dedicated `service=cartpath` tag or (fancifully) a `highway=cartway` tag, so that mappers can succinctly indicate the restriction and the reason for the restriction without pretending there’s a <img src="https://upload.wikimedia.org/wikipedia/commons/b/bb/MUTCD_R5-3.svg" width="24" alt="No Motor Vehicles" align="top"> sign. Or maybe `highway=path` is a safer replacement for `highway=service`. But that would be outside the scope of this repository, probably better for the tagging mailing list.

**Comment by matkoniecz** [comment]
> some mappers could disagree with tagging access restrictions that in many cases may be implicit

Is it actually a view expressed by some group of mappers? ("some mappers could disagree with" is true for nearly any aspect of tagging)

**Comment by 1ec5** [comment]
I was flagging it as a possible downside because it’s analogous to the situation with implicit turn restrictions, in that tagging `motor_vehicles=no` would technically erase the distinction between paths that have a “no motor vehicles” sign and those that don’t. But in my opinion, it’s a distinction without a difference, which is why I’m proposing that we add the `motor_vehicles=no` tag anyways.

**Comment by matkoniecz** [comment]
Alternative fix would be using `highway=path` as highway tag for ones that are too small for cars.

And right now https://wiki.openstreetmap.org/wiki/Proposed_features/cartpath is active

**Comment by 1ec5** [comment]
There’s a view among some mappers that access tags like `motor_vehicle=no` [should only indicate strict legal prohibitions](https://lists.openstreetmap.org/pipermail/tagging/2021-January/thread.html#58857), in which case automatically adding `motor_vehicle=no` would be inappropriate for a preset. It would be a stretch for iD to assume that a golf cart path is on a private golf course or that local laws explicitly prohibit motor vehicles from using these paths, even though a golf cart path by definition is generally unsuitable for full-size motor vehicles.

This legalistic interpretation would leave us with `highway=path` (which doesn’t clarify the kind of path, to the frustration of renderers) or the proposed `highway=golf_cart_path` (which is fine with me but comes with tradeoffs). In my opinion, common sense would call for us to add `motor_vehicle=no` or at least `motor_vehicle=private` to this preset in the meantime and ignore the theoretical problem of overstating the prohibition.

**Comment by danieldegroot2** [comment]
Ref https://community.openstreetmap.org/t/is-there-a-list-of-accidents-caused-by-osm-osm/109035/9
