### ISSUE TITLE
Cycleways with `bicycle=no` but also `mofa=yes|designated` or `moped=yes|designated` should not raise a warning

### ISSUE THREAD

**Issue by jdhoek** [openstreetmap/id-tagging-schema#484]
There is check in `data/deprecated.json` for the combination of `bicycle=no` and `highway=bicycle`:

```json
{
    "old": {"highway": "cycleway", "bicycle": "no"},
    "replace": {"highway": "path", "bicycle": "no"}
},
```

This makes sense, and would usually point to a mapping error. However, in the Netherlands this raises this warning for a common feature on Dutch roads.

We have three variants of cycleways in our legal code. Two of them are relevant here: the `G11` which is mandatory for `bicycle` and `mofa`, but forbidden for `moped`, and the `G12a`, which is mandatory for all three of these road user categories. When a cycleway switches from `G11` to `G12a` or vice versa, mopeds use small links to move to or from the main road:

![Screenshot from 2022-06-01 17-01-31](https://user-images.githubusercontent.com/683699/171437326-f9d56e8b-7770-43a3-80e8-cd48c9ecde6b.png)

We've settled on the following tagging scheme for these links:

```
highway          cycleway
bicycle          no
foot             no
mofa             no
moped            designated
oneway           yes
traffic_sign     NL:D104 (or) NL:D103
```

[This is the link shown on that photograph on the map.](https://www.openstreetmap.org/way/731968881)

These are still `highway=cycleway` in the Dutch context, because mopeds are one of the designated road user classes for cycleways in the Netherlands (provided it is signed with a `G12a` sign).

Is there a way to exclude these from the deprecation warning? That is, keep the check, but don't suggest it if either `mofa` or `moped` is set to a permissive value?

**Comment by tyrasd** [comment]
> Is there a way to exclude these from the deprecation warning?

Unfortunately, this is not possible to implement in the current [schema](https://github.com/ideditor/schema-builder). :disappointed: 

The next best thing we can do is to deactivate the deprecation warning completely for now and think about a better solution for this.

**Comment by jdhoek** [comment]
Can that be done regionally? (i.e., just the Netherlands.)

**Comment by tyrasd** [comment]
I was just about to write that that would also not be possible (because the deprecation rules are really very [basic](https://github.com/ideditor/schema-builder/blob/main/schemas/deprecated.json#L3)), but then I remembered that there is also the functionality of preset [`replacements`](https://github.com/ideditor/schema-builder#replacement) which can use the whole functionality of a preset, including regional limitations. It's going to be a bit of a hassle, but I think it can work. Let me give it a try.

**Comment by tyrasd** [comment]
see #509 for a possible fix
