### ISSUE TITLE
resolved:outdated_tags:incomplete_tags

### ISSUE THREAD

**Issue by hungerburg** [openstreetmap/id-tagging-schema#487]
Hello,

Yesterday an mapper got a badge "resolved:outdated_tags:incomplete_tags" for adding "bicycle=designated" to a "highway=cycleway".

This makes me wonder: What is outdated? What is incomplete?

**Comment by tyrasd** [comment]
can you please add  a link to the changeset where you saw this? I didn't receive this changeset flag when trying to reproduce this: https://api06.dev.openstreetmap.org/changeset/238048.

**Comment by hungerburg** [comment]
Sorry to not have written, a bit whodidit and overpass helped me find CS 121771472 and 121796864 - the user fixed a lot, mostly useful :)

**Comment by tyrasd** [comment]
Ah, I see.

This warning comes from the [Cycle & Foot Path](https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/highway/cycleway/bicycle_foot.json) preset, which is set up to add `bicycle=designated` if an object has `highway=cycleway` and `foot=designated`. (PS: I didn't trigger the warning in my test, as I was testing in an area where this preset is inactive.)

According to https://wiki.openstreetmap.org/wiki/Tag:highway%3Dcycleway, the `bicycle=designated` is strictly necessary (as it should be implied by the highway type already), but it also doesn't hurt to add it for clarity, I guess. :shrug:

Do you think it could be confusing for mappers to get this warning?
