### ISSUE TITLE
Make Sources field default on *every* feature preset

### ISSUE THREAD

**Issue by lectrician1** [openstreetmap/id-tagging-schema#50]
_I'm not sure if this request belongs in this repo..._

Making sure mappers leave sources for every elements they edit is important. 

Yes, you can select Sources for your changeset when you submit, but it's not like it adds those sources to every element you've edited.

Also, going into `Add field:` and then scrolling down and clicking on sources which is the _14th_ element in the list is very painstaking and annoying.

**Comment by lectrician1** [comment]
I'll put my lack of knowledge here too:
https://wiki.openstreetmap.org/wiki/Key:source

**Comment by quincylvania** [comment]
> I'm not sure if this request belongs in this repo...

You found the right place!

> Making sure mappers leave sources for every elements they edit is important.

Maybe, I'm not sure this is a widely-help opinion. Mostly we expect iD mappers are tracing features from imagery, so inviting them to specify that for hundreds of buildings or whatnot sounds like a chore. They can just add sources to changesets. If we do https://github.com/openstreetmap/iD/issues/7755 then the source field would always be shown for changesets.

> Also, going into Add field: and then scrolling down and clicking on sources which is the 14th element in the list is very painstaking and annoying.

The list varies per feature type and language. You can also start typing "source" and it will appear at the top. 
https://github.com/openstreetmap/iD/issues/5734 is about customizing the default list of fields so you won't have to add it manually every time.

**Comment by matkoniecz** [comment]
Nowadays it is recommended to rather tag source on changeset (except some extreme cases with really unusual data).

Adding `source=Bing` to every building is not considered as a good idea nowadays, for multiple reasons.

**Comment by bryceco** [comment]
Some people want sources per changeset, others per object, others per tag. This is an OSM database problem, not something that should be solved by editors IMO.

**Comment by quincylvania** [comment]
Okay, I think there are ways that source tagging in OSM could be improved, but iD's approach seems fine for the present patterns.
