### ISSUE TITLE
Translation data

### ISSUE THREAD

**Issue by westnordost** [openstreetmap/id-tagging-schema#53]
The translations for the presets used to be part of the main translation files here https://github.com/openstreetmap/iD/tree/develop/dist/locales

Is this going to change with the move of the presets to a new repository? It looks like translations would be here:
https://github.com/openstreetmap/id-tagging-schema/tree/main/dist/translations 
but there is only English.

**Comment by quincylvania** [comment]
@westnordost Yes! I already added the code for this [here](https://github.com/ideditor/schema-builder/commit/bff95a958f7fe19920d9e1b91e7e239ceb479a1f). Just need to publish a new version of the builder and update this repo.

**Comment by westnordost** [comment]
Nice! Would you mind dropping a comment here when this is done or closing this issue when it is done so I am notified of it?

**Comment by quincylvania** [comment]
All the translation files are now included at https://github.com/openstreetmap/id-tagging-schema/tree/main/dist/translations. 

There's also an [index.json](https://github.com/openstreetmap/id-tagging-schema/blob/main/dist/translations/index.json) file that shows the completion percentage for every language. We'll use this in iD to avoid downloading backup langauges if one of the user's preferred languages is already complete.
