### ISSUE TITLE
Latest version number discrepancy

### ISSUE THREAD

**Issue by arch0345** [openstreetmap/id-tagging-schema#530]
In [tags](https://github.com/openstreetmap/id-tagging-schema/tags)/[npm](https://www.npmjs.com/package/@openstreetmap/id-tagging-schema), it's referred to as v3.4.2, but in the [changelog](https://github.com/openstreetmap/id-tagging-schema/blob/main/CHANGELOG.md#341) it's referred to as v3.4.1

**Comment by tyrasd** [comment]
yes, I made a small mistake while publishing the 3.4.1 version and had to re-release it as 3.4.2… I forgot to update the version number on the changelog :see_no_evil:  thanks for the hint
