### ISSUE TITLE
Describe barrier=yes as "Unspecific barrier value" and complain about it in validator

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/id-tagging-schema#531]
triggered by https://www.openstreetmap.org/note/3264943

See also #399 ("Describe shop=yes as "Unspecific shop"")

**Comment by 1ec5** [comment]
Note that “unspecified” is a more natural word than “unspecific”.

I’m not sure that there’s a readily available validator rule that could be defined in this repository for `barrier=yes`, unless you mean that this tag should be deprecated in favor of… something. I think there would need to be a change downstream in iD to implement a new validator rule for nonspecific tags, if it’s really so urgent to choose a tag other than `barrier=yes`. (From a routing standpoint, at least, a much more urgent task would be to set access tags. Routers don’t assume the default access tags that most mappers intuitively expect.)

**Comment by matkoniecz** [comment]
`barrier=yes` is a valid tag to use and should not be deprecated, but replacing it with more specific values is very useful.

**Comment by tyrasd** [comment]
ea34244 adds a preset for barrier=yes called `Barrier (Unspecified Type)` following the case of `shop=yes` in #399.

> but replacing it with more specific values is very useful.

can you open a new feature request for a validator message on the iD [repo](https://github.com/openstreetmap/iD/issues), please?

**Comment by matkoniecz** [comment]
Thanks!
