### ISSUE TITLE
golf=bunker should use surface 

### ISSUE THREAD

**Issue by DaveF63** [openstreetmap/id-tagging-schema#534]
Given it's been agreed in #203 that other golf features use the surface tag to indicate their, err... surface, it appears illogical to auto add natural=sand to golf=bunker.

natural=* is a primary tag, designed to be used in isolation, not a supplementary, sub/adjective tag.  

Oh, and not all bunkers are sand.

**Comment by tyrasd** [comment]
[Earlier this year](https://wiki.openstreetmap.org/w/index.php?title=Tag:leisure%3Dgolf_course&oldid=2230842), the wiki still recommended `natural=sand` (or `surface=sand`), but I agree that `surface` would do a better job at it.

> not all bunkers are sand.

Oh, really? What other types of bunkers exist? FWIW, at least the [USGA](https://www.usga.org/content/usga/home-page/rules/rules-2019/rules-of-golf/rules-and-interpretations.html#!ruletype=fr&section=rule&rulenum=12) considers bunkers to be a term specific for sandy obstacles:

> Bunkers […] are specially prepared areas intended to test your ability to play a ball from the sand.

**Comment by matkoniecz** [comment]
> natural=* is a primary tag, designed to be used in isolation, not a supplementary, sub/adjective tag.

in some cases multiple primary tags may apply (though in this case using `surface` is not making things worse)

BTW,  #409 appears to request exact opposite

**Comment by DaveF63** [comment]
> [Earlier this year](https://wiki.openstreetmap.org/w/index.php?title=Tag:leisure%3Dgolf_course&oldid=2230842), the wiki still recommended `natural=sand` (or `surface=sand`), but I agree that `surface` would do a better job at it.
> 
> > not all bunkers are sand.
> 
> Oh, really? What other types of bunkers exist? 
https://www.golfcompendium.com/2019/10/grass-bunker.html
https://golf.com/travel/ways-architects-use-grass-hazards

Admittedly, they're much rarer, but they do exist, even in the US.

**Comment by tyrasd** [comment]
Hm… these things should probably be mapped as `golf=rough` instead of `golf=bunker`, as they are not actually bunkers:

> Important note: Grass bunkers are not, technically, bunkers at all under the Rules of Golf.

**Comment by DaveF63** [comment]
> in some cases multiple primary tags may apply

Disagree. 
Primary: "First in a group or series.", "placed ahead of others."

Do you have any OSM examples?

**Comment by matkoniecz** [comment]
> Do you have any OSM examples?

```
amenity = drinking_water
man_made = water_tap
```

```
amenity = place_of_worship
man_made = cross
```

```
amenity = place_of_worship
building = chapel
```

```
amenity = shelter
building = yes
```

```
amenity = drinking_water
man_made = drinking_fountain
``

**Comment by DaveF63** [comment]
?!?

I'll discuss these on another forum as this one is inappropriate. 

> ```
> amenity = drinking_water
> man_made = water_tap
> ```

**Comment by matkoniecz** [comment]
Feel free to ping me here or via mail if that is not tagging mailing list or OSM wiki with ping template being used.

**Comment by DaveF63** [comment]
> Oh, really? What other types of bunkers exist? FWIW, at least the [USGA](https://www.usga.org/content/usga/home-page/rules/rules-2019/rules-of-golf/rules-and-interpretations.html#!ruletype=fr&section=rule&rulenum=12) considers bunkers to be a term specific for sandy obstacles:

What you're actually quoting is The R&A. Their concern is with the likes of competition courses. 

Around the world there are hundreds of smaller courses, municipal run pitch 'n' putt etc which can have grass covered craters to reduce maintenance costs.

**Comment by DaveF63** [comment]
To check, are there any other tags prescribing `natural-sand` or is this swap purely `golf=bunker`? 

https://taghistory.raifer.tech/#***/natural/sand&***/surface/sand
