### ISSUE TITLE
Add Playground Map preset

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/id-tagging-schema#538]
[`playground=map`](https://wiki.openstreetmap.org/wiki/Tag:playground%3Dmap) should have a preset named Playground Map. As of writing, `playground=map` is one of the most widely used documented `playground=*` tags that doesn’t have an iD preset yet, with several less common tags already being supported. The Subject and Surface fields would both be relevant.

**Comment by tyrasd** [comment]
it's probably tricky to find a good name for this preset. Initially, I thought a "playground map" would be a (sign containing) a map of a playground. :speak_no_evil: Do you have an idea how we could name this accurately?

**Comment by tyrasd** [comment]
PS: This could also be a candidate for a `subject:wikidata` field (see #533)
