### ISSUE TITLE
Feature Request: Supply a non-minified presets.json in dist/

### ISSUE THREAD

**Issue by westnordost** [openstreetmap/id-tagging-schema#54]
In the `dist` folder, there is only `presets.min.json`. When pulling a new version of this data, it would be easier to review what changed if one could pull a `presets.json` instead of the minified version like it was possible before when the tagging schema definitions was part of the iD repos. The old URL was

https://raw.githubusercontent.com/openstreetmap/iD/develop/data/presets/presets.json

**Comment by quincylvania** [comment]
Sounds fine. I'm thinking we only need to update the JSON files in the `dist` directory when releasing and not for every commit.

**Comment by quincylvania** [comment]
I added non-minified version of all the files in https://github.com/openstreetmap/id-tagging-schema/tree/main/dist except for the locales. If you need the non-minified locales too then we could figure that out.

**Comment by westnordost** [comment]
Yes, for the locales it would certainly be nice as well - for the same reason. To see a proper diff when pulling a new version. Shall I open a new ticket for that?
