### ISSUE TITLE
Name tag upgrade warning triggered by brand has risky edge cases

### ISSUE THREAD

**Issue by jdhoek** [openstreetmap/id-tagging-schema#544]
# Issue

When POI's have certain `branch` tags associated with it, the following tag-upgrade suggestion can pop up if `name` differs from what is expected:

![Screenshot from 2022-07-19 18-45-16](https://user-images.githubusercontent.com/683699/179806278-5ce496ca-7c47-4985-a598-2b1042549b47.png)

This is usually correct, and helps fix minor spelling variations of the same name. A supermarket with `brand=EDEKA` is usually also called and signposted as 'EDEKA'.

But for many POI's (supermarkets included), not all branches are owned by the brand. Many are franchisers, and these often have their own name (such as 'EDEKA Etwas Etwas' or in this specific case 'Zurheide Feine Kost').

This tag-upgrade suggestion offers one way to disable the warning; by changing `brand:wikidata=*` to `not:brand:wikidata=*`. This is fine in some cases, but not with franchisers, where the brand is actually correct.

(The 'Ignore this issue' button only disables the warning for the current mapper, correct?)

# Reproduction

[See this node for example.](https://www.openstreetmap.org/edit?node=5497632657#map=19/51.21947/6.78259) ID will trigger the warning.

# Expected

The solution depends on what is possible with these warnings, but one part I would suggest is to disable this tag-upgrade dialog also when `not:name=*` is set to the name expected by the current brand. In this specific case, I've added `not:name=EDEKA`.

A step above would be to add an option that sets `not:name=[BRAND]`, something like this?

![Screenshot from 2022-07-19 19-00-51](https://user-images.githubusercontent.com/683699/179807921-fc51f7d5-6b35-4603-91f4-52ec35e7d316.png)

# Concerns

While edge cases are normally fine to ignore if more experienced mappers can handle them, I worry that the current tag-upgrade suggestion seems to get applied by well-meaning mappers unintentionally. In this specific case, this seems to have happened in [this changeset](https://www.openstreetmap.org/changeset/108705306). After all, ID showed a warning! (On the ground, and on the web, that supermarket is certainly EDEKA branded, but it is labelled clearly as 'Zurheide Feine Kost').

It would be good to have a way to disable the warning in cases where the mapper consciously uses a different `name`.

**Comment by bhousel** [comment]
It's pretty common for a large brand to operate a bunch of store formats. 
In NSI we can always just add more of these store formats, then the validator can make better suggestions.. 
So I think we can just add an entry for "Zurheide Feine Kost", and then you won't get this suggestion anymore.

(We currently have these store formats for EDEKA):

```js

    {
      "displayName": "EDEKA",
      "id": "edeka-0a839e",
      "locationSet": {"include": ["de"]},
      "matchNames": [
        "e neukauf",
        "edeka neukauf"
      ],
      "tags": {
        "brand": "EDEKA",
        "brand:wikidata": "Q701755",
        "name": "EDEKA",
        "shop": "supermarket"
      }
    },
    {
      "displayName": "EDEKA aktiv markt",
      "id": "edekaaktivmarkt-0a839e",
      "locationSet": {"include": ["de"]},
      "tags": {
        "brand": "EDEKA",
        "brand:wikidata": "Q701755",
        "name": "EDEKA aktiv markt",
        "shop": "supermarket"
      }
    },
    {
      "displayName": "EDEKA xpress",
      "id": "edekaxpress-0a839e",
      "locationSet": {"include": ["de"]},
      "tags": {
        "brand": "EDEKA",
        "brand:wikidata": "Q701755",
        "name": "EDEKA xpress",
        "shop": "supermarket"
      }
    },
```

**Comment by jdhoek** [comment]
That would solve that one specific case, but note that these are not store formats. These are franchisers, where a common franchise naming format is this:

https://www.openstreetmap.org/edit#map=19/53.17949/5.82567

Most branches of this supermarket chain are just called 'Jumbo', but franchisers tend to add their own name. Here it is 'Jumbo Els Boek'. It is the only location named thus, and there are dozens of franchisers for this one Dutch supermarket chain alone.

So that solution unfortunately wouldn't work. We can't maintain a list of all franchisers for every POI.

**Comment by bhousel** [comment]
> The suggested update here is not good either:
> 
> ![Screenshot from 2022-07-19 20-30-24](https://user-images.githubusercontent.com/683699/179823328-c1cbb8cd-488e-42bf-ac41-749c223f77f6.png)
> 
> Because the name on the signs is literally 'Jumbo Els Boek'. This is documented on [Key:branch](https://wiki.openstreetmap.org/wiki/Key:branch) too:
> 

I think most people would be pretty okay with this suggestion.  But I can set up on the NSI side that Jumbo and EDEKA are brands where they sometimes use a custom `name` value.

**Comment by jdhoek** [comment]
Note that the fact that `name` can vary within a chain is explicitly the reason `brand` and `brand:wikidata` are employed: these latter two are the stable identifier for the POI chain. The name is expected to vary, even if often the name will be uniformly the same as the chain name. Franchisers are a common exception.

Having a way to mark an entity as an exception would be very useful.
