### ISSUE TITLE
Add preset for `traffic_calming=mini_bumps`

### ISSUE THREAD

**Issue by Dimitar5555** [openstreetmap/id-tagging-schema#549]
### OSM Tag(s)

traffic_calming=mini_bumps

### How would you like this tag to see supported?

As a Preset

### Label

Mini Bumps

### Aliases

small bumps

### Link to OSM Wiki page

https://wiki.openstreetmap.org/wiki/Tag%3Atraffic_calming%3Dmini_bumps

### Status of the Tag

Approved

### Usage of the tag

864

**Comment by tyrasd** [comment]
> Usage of the tag
> 864

At first, I thought this is slightly on the low side for a dedicated preset: only accounting for 0.1% of all `traffic_calming` objects. For comparison: the three least common tag values which do have a dedicated preset (`dip`, `chicane` and `rumble_strip`) have 4k, 17k and 22k objects respectively. But on the other hand, it is the most common value which doesn't currently have a preset (ignoring the `no` value) and usage seems to be increasing quite fast after the tag got approved in early 2021:

![image](https://user-images.githubusercontent.com/1927298/181317727-cfc8451c-8ecf-4f60-98c0-3174f86a533d.png)
