### ISSUE TITLE
`parking:orientation` field is showing additional undocumented rare values

### ISSUE THREAD

**Issue by jdhoek** [openstreetmap/id-tagging-schema#553]
I've noticed that ID is suggesting two additional undocumented and nearly unused values for `parking:orientation`:

![2022-07-30-205459_2560x1440_scrot](https://user-images.githubusercontent.com/683699/181937821-1e72ea61-50ac-49c4-a87c-188b8d7a1ac2.png)

The value `orthogonal` (85 uses) seems like an undocumented alternative for `perpendicular` and `marking` is used just 16 times (no idea what that means).

Why are these showing up in the list? Is this automated based on TagInfo data?

Is it possible to leave them out?

**Comment by arch0345** [comment]
Yeah, it looks like these are fetched from Taginfo:
https://github.com/ideditor/schema-builder#autosuggestions

**Comment by jdhoek** [comment]
@arch0345 Interesting. Weird how that is pulling in tag values used only 80 and 16 times. That's bound to cause mappers to choose bad values.
