### ISSUE TITLE
Make playground equipment searchable

### ISSUE THREAD

**Issue by lectrician1** [openstreetmap/id-tagging-schema#56]
https://github.com/openstreetmap/id-tagging-schema/blob/bf95421f65018ccd7f398f8459b37462febddcba/data/presets/_playground.json#L26

**Comment by matkoniecz** [comment]
Note https://github.com/openstreetmap/id-tagging-schema/blob/bf95421f65018ccd7f398f8459b37462febddcba/data/presets/_playground.json#L24

This preset is capable of roughly describing what is tagged, it is not possible to tag with it

**Comment by lectrician1** [comment]
I'm a bit confused? Yes the preset comes up when you add the `playground` tag, I just found it annoying to type it in every time instead of being able to search for it like it prompts you to do after creating a feature.

**Comment by matkoniecz** [comment]
This preset that you linked has no values for specific equipment, it is a catchall for any `playground` tag.

If it would be searchable - `playground=*` would be tagged after selecting it, not a specific value.

And in case adding (or having) more specific values like `playground=swing` this would remain as an unsearchable catchall anyway.

**Comment by quincylvania** [comment]
> If it would be searchable - playground=* would be tagged after selecting it, not a specific value.

@matkoniecz The file is misleading, the tag would be `playground=yes`, which appears to be used for specifying if a facility has a playground, not for generic playground equipment.

@lectrician1 The problem would appear to be that there's no great way to tag generic playground equipment in OSM right now.

**Comment by lectrician1** [comment]
**Could searching for "playground" show all already-existing presets for playground instead?**

I notice that presets have the `"terms"` JSON element to tell iD to show the preset when specific things are searched.

Could something be implemented that allows the all of the playground features to be shown when searching for "playground", without having to add the `"terms": "playground"` element to every playground preset? Of course, these should probably be rank below a standard Playground feature, but they should still show up in the search.

This could also apply to other OSM tags. For example, searching for "highway" displays all of the presets with the highway tag (ranked below of course).

**Also,** another solution could be actually making it searchable and then prompting the user to enter a type of equipment. If the user does not enter a type, iD could create an issue. Then if no type is selected even at submit then it discards the feature.

Idk. Just some ideas.

>  The problem would appear to be that there's no great way to tag generic playground equipment in OSM right now.

I'm a bit confused by this statement?

**Comment by quincylvania** [comment]
> Could something be implemented that allows the all of the playground features to be shown when searching for "playground", without having to add the "terms": "playground" element to every playground preset?

We could add a category for the playground presets, like the Golf Features category.

> I'm a bit confused by this statement?

It doesn't look like there's a tag that says "this is playground equipment" without specifying what type of equipment it is. This is different from tags like `historic=yes` which means "this is a historic feature" without further context.

**Comment by lectrician1** [comment]
I would be for a category.

_In the process of writing this I thought of these things (moved them to new issues):_
https://github.com/openstreetmap/iD/issues/8207
https://github.com/openstreetmap/id-tagging-schema/issues/58
