### ISSUE TITLE
Support traffic signals on cycleway crossings

### ISSUE THREAD

**Issue by BubbaJuice** [openstreetmap/id-tagging-schema#568]
### OSM Tag(s)

cycleway=crossing and crossing=traffic_signals

### How would you like this tag to see supported?

Other (please indicate below)

### Label

Cycle Crossing with Pedestrian Signals

### Link to OSM Wiki page

https://wiki.openstreetmap.org/wiki/Tag:crossing%3Dtraffic_signals; https://wiki.openstreetmap.org/wiki/Tag:cycleway%3Dcrossing

### Status of the Tag

Other (please indicate below)

### Usage of the tag

6,603

### Regional Tag?

global

### Further Information

The existing "Cycle Crossing" preset should be improved upon with new presets for cycle crossings with pedestrian signals. These would support the same tags as the "Crossing with Pedestrian Signals" preset. `cycleway=crossing` is de facto while `crossing=traffic_signals` is approved.

`cycleway=crossing` + `crossing=traffic_signals` taginfo:
![image](https://user-images.githubusercontent.com/68205167/184038246-e37ea892-79a9-4a1f-8b74-7189bb6b1903.png)

**Comment by 1ec5** [comment]
Related: https://github.com/openstreetmap/id-tagging-schema/issues/507#issuecomment-1179832250.

**Comment by tyrasd** [comment]
I'd like to wait on this until the voting period of the proposal for `crossing:markings` tag is over (this weekend):
https://wiki.openstreetmap.org/wiki/Proposed_features/crossing:markings, as all crossing presets would likely need to be adjusted for that anyway.

**Comment by tyrasd** [comment]
The [proposal](https://wiki.openstreetmap.org/wiki/Proposed_features/crossing:markings) for the `crossing:markings` tag was recently approved.
