### ISSUE TITLE
"message=" field to "advertising" key

### ISSUE THREAD

**Issue by Coolawik** [openstreetmap/id-tagging-schema#577]
### OSM Tag(s)

message=*

### How would you like this tag to see supported?

As a Field

### Label

Message

### Link to OSM Wiki page

https://wiki.openstreetmap.org/wiki/Key:message

### Status of the Tag

In Use

### Usage of the tag

27 000

### Regional Tag?

global

### Further Information

Add _message=*_ field to _advertising_ key.
![image](https://user-images.githubusercontent.com/106607132/188317685-2bbf6612-4863-4b9d-bc44-40c1025f2d75.png)

Recommended use on OSM wiki:
![image](https://user-images.githubusercontent.com/106607132/188317763-87b73dfe-6b30-4b5b-ae1d-4e98c5c9ba0c.png)

**Comment by Lukas458** [comment]
I'm not so sure about this.

For some values of message=*, to be honest I Do not really guess whats the difference:

1. between advertising=* + message=local and
tourism=information + information=board + board_type=notice?

2. between advertising=* + message=legal and
tourism=information + information=board + board_type=rules?

3. between advertising=* + message=map and
tourism=information + information=map + map_type=*?


For example, if the advertisement is a "column", I understand that this is different from information=board. But sometimes I find it really difficult to differentiate between advertising and "tourist information". Some are both in one (tourist map and map of local shops for example).

**Comment by k-yle** [comment]
oh I added this in #785, I guess this issue can be closed now
