### ISSUE TITLE
Add a preset for `natural=tree_stump`

### ISSUE THREAD

**Issue by Dimitar5555** [openstreetmap/id-tagging-schema#588]
### OSM Tag(s)

natural=tree_stump

### How would you like this tag to see supported?

As a Preset

### Label

Tree Stump

### Terms

cut tree, removed tree

### Link to OSM Wiki page

https://wiki.openstreetmap.org/wiki/Tag:natural=tree_stump

### Status of the Tag

De Facto

### Usage of the tag

4 153

**Comment by tyrasd** [comment]
:+1: 

https://github.com/ideditor/temaki/pull/76 has a proposed icon for this preset
