### ISSUE TITLE
complain about image=https://westnordost.de/* 

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/id-tagging-schema#591]
moved to https://github.com/openstreetmap/iD/issues/9302

**Comment by 1ec5** [comment]
iD’s deprecated tag validator rule only tells the user that the tag is deprecated and offers a replacement. It doesn’t give the user any additional context. Moreover, I think deprecated.json in this repository doesn’t accept wildcards or pattern matching. The proposed warning is a better fit for the existing [invalid format](https://github.com/openstreetmap/iD/blob/3bf8d52ca9a8d371f31e6d25243c12bf31a7b94f/modules/validations/invalid_format.js) validator rule or a new rule.

**Comment by matkoniecz** [comment]
moved to https://github.com/openstreetmap/iD/issues/9302 then
