### ISSUE TITLE
A list of data users that use this repo and how

### ISSUE THREAD

**Issue by tordans** [openstreetmap/id-tagging-schema#607]
https://github.com/Zverik/every_door/issues/452 and https://github.com/bryceco/GoMap/issues/618 make me think it is a good idea to have a list of data users and how thy consume the data in this repo.

(Or maybe the schema-builder-repo, but AFAIK all(?) use the data here direclty.)

I suggest to add a section to the readme or maybe a separate file where each data consumer can add her application.

| Repository (Link) | Use data | Data consumption process |
|---|---|---|
| iD Editor | Show, list, search all data | … |
| RapID | Show, list, search all data | … |
| [GoMap!!](https://github.com/bryceco/GoMap) | Show, list, search all data | Manual update before a release. [Docs](https://github.com/bryceco/GoMap#how-to-update-external-assets) |
| [Every Door](https://github.com/Zverik/every_door) | … | … |
| [MapComplete](https://github.com/pietervdvn/MapComplete) | Provide the presets to be reused in other layers | … [Docs](https://github.com/pietervdvn/MapComplete/blob/develop/Docs/Layers/id_presets.md) |

**Comment by 1ec5** [comment]
The [presets wiki page](https://wiki.openstreetmap.org/wiki/Preset) also mentions limited usage of this repository by StreetComplete (via [osmfeatures](https://github.com/westnordost/osmfeatures/)) and the Overpass turbo query wizard.

**Comment by tyrasd** [comment]
I've created a wiki section for this repository, with a page for projects which use this repository:
https://github.com/openstreetmap/id-tagging-schema/wiki/Projects-that-are-using-this-tagging-schema. Anyone should be able to edit the list, I hope.
