### ISSUE TITLE
some font awesome icons are missing from new release

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/id-tagging-schema#616]
See https://github.com/streetcomplete/StreetComplete/issues/4519#issuecomment-1281361668

I reported https://github.com/FortAwesome/Font-Awesome/issues/19387 but I do not expect it to be fixed (it may be a deliberate crippling to extract more cash from premium version)

Maybe https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/shop/deli.json#L2 should have  `"icon": "fas_6-jar",` and https://github.com/openstreetmap/id-tagging-schema/blob/abe59b253d30cb02ef1d491fe937fbafdcd746fb/data/presets/amenity/nightclub.json should have `"icon": "fas_master-cocktail",` ?

Or document at https://github.com/ideditor/schema-builder/blob/c9541bd78ea3f6c997102b40530eef1128b3f4df/README.md#icon that all branches should be checked for icon? Or that `6.x` and `master` branches should be checked?

**Comment by tyrasd** [comment]
> that all branches should be checked for icon

Actually, consumers should only use the most recent release of the [Font-Awesome](https://github.com/FortAwesome/Font-Awesome) icon set and take into account that these icons have `aliases` (see https://github.com/streetcomplete/StreetComplete/issues/4519#issuecomment-1282081770).

There is already an issue to improve the documentation about this: #314. One way to generally improve the situation with icons would be to bundle the icons in this repo (see https://github.com/ideditor/schema-builder/issues/4), such that consumers wouldn't have to .

**Comment by matkoniecz** [comment]
Another option would be for iD to resolve this aliases and edit preset files so latest name is referenced.
