### ISSUE TITLE
Request addition of more octane levels to Fuel Types

### ISSUE THREAD

**Issue by kevinp2** [openstreetmap/id-tagging-schema#621]
### OSM Tag(s)

fuel:octane_XX where XX = 85 through 91

### How would you like this tag to see supported?

As a Field Value

### Label

XX Octane

### Link to OSM Wiki page

https://wiki.openstreetmap.org/wiki/Template:Fuel_types

### Status of the Tag

Unspecified / Unknown

### Usage of the tag

see [below](https://github.com/openstreetmap/id-tagging-schema/issues/621#issuecomment-1286576881)

### Replaces other Tag?

No

### Further Information

I have added new Octane levels commonly found in the western US to the list of fuel types maintained in https://wiki.openstreetmap.org/wiki/Template:Fuel_types 

In my travels I have encountered octane levels ranging from 85 through 91.  Some of them are already listed in the file https://github.com/openstreetmap/id-tagging-schema/blob/7a9a9d5e391a2f08b1a74588eeb0e6edd56eec31/data/fields/fuel/fuel_multi.json

I request to add the missing octane levels 85, 88 and 90 to the list.  This will then enable a project to correctly map all gas stations in some areas with the list of octane levels that they offer to travelers.

**Comment by 1ec5** [comment]
For context, the main reason for these much lower values is that some countries (including all of North America and also Brazil) measure octane using the AKI formula rather than the RON formula. This was a point of confusion on the wiki and elsewhere until 2019.

**Comment by tyrasd** [comment]
some current usage stats

tag value | usage | listed on wiki table | currently included in field
-- | -- | -- | --
`octane_76` | ⣧⠀⠀⠀ 52 | :x: | :x: 
`octane_80` | ⣿⣿⣇⠀ 2.9k | :heavy_check_mark: | :heavy_check_mark: 
`octane_83` | ⠀⠀⠀⠀ 12 | :x: | :x: 
`octane_84` | ⣆⠀⠀⠀ 20 | :x: | :x: 
`octane_85` | ⣿⣄⠀⠀ 150 | :heavy_check_mark: | :x: 
`octane_86` | ⣄⠀⠀⠀ 14 | :heavy_check_mark: | :x: 
`octane_87` | ⣿⣿⣧⠀ 4k | :heavy_check_mark: | :heavy_check_mark: 
`octane_88` | ⣿⠀⠀⠀ 93 | :heavy_check_mark: | :x: 
`octane_89` | ⣿⣿⠀⠀ 1.1k | :heavy_check_mark: | :heavy_check_mark: 
`octane_90` | ⣿⣄⠀⠀ 170 | :heavy_check_mark: | :x: 
`octane_91` | ⣿⣿⣿⠀ 9.5k | :heavy_check_mark: | :heavy_check_mark: 
`octane_92` | ⣿⣿⣿⣄ 16k | :heavy_check_mark: | :heavy_check_mark: 
`octane_93` | ⣿⣷⠀⠀ 620 | :heavy_check_mark: | :x: 
`octane_94` | ⣧⠀⠀⠀ 60 | :x: | :x: 
`octane_95` | ⣿⣿⣿⣿ 74k | :heavy_check_mark: | :heavy_check_mark: 
`octane_96` | ⣧⠀⠀⠀ 47 | :x: | :x: 
`octane_97` | ⣿⣷⠀⠀ 630 | :x: | :x: 
`octane_98` | ⣿⣿⣿⣧ 41k | :heavy_check_mark: | :heavy_check_mark: 
`octane_99` | ⣇⠀⠀⠀ 35 | :x: | :x: 
`octane_100` | ⣿⣿⣷⠀ 6.7k | :heavy_check_mark: | :heavy_check_mark: 
`octane_101` | ⠀⠀⠀⠀ 9 | :x: | :x: 
`octane_102` | ⣿⣆⠀⠀ 200 | :x: | :x:
