### ISSUE TITLE
Add support for crossing island as way

### ISSUE THREAD

**Issue by kaneap** [openstreetmap/id-tagging-schema#633]
### OSM Tag(s)

footway=traffic_island

### How would you like this tag to see supported?

As a Preset

### Label

Crosswalk island

### Aliases

Crossing island, traffic island, refuge island

### Link to OSM Wiki page

https://wiki.openstreetmap.org/wiki/Tag:footway%3Dtraffic_island

### Status of the Tag

In Use

### Usage of the tag

4,062

### Replaces other Tag?

no

### Further Information

Often times I see users tagging the island part of the crossing way with `footway=crossing`, `crossing:island=yes`(which has different implications. Adding this key will improve detailed tagging of crossing and avoid future mistagging.

**Comment by 1ec5** [comment]
I think the name of this preset should be consistent with the name of the `crossing:island` field, which is currently “Refuge Island”:

https://github.com/openstreetmap/id-tagging-schema/blob/0c8be6bf01c2e5b8e7361da8550e2c22b7768cc1/data/fields/crossing/island.json#L4

**Comment by tyrasd** [comment]
I've included this preset in the PR for crossings refactoring: #590
