### ISSUE TITLE
office=engineer

### ISSUE THREAD

**Issue by DiogoBaptista98** [openstreetmap/id-tagging-schema#639]
### OSM Tag(s)

office=engineer

### How would you like this tag to see supported?

As a Preset

### Label

Engineer

### Terms

Engineering

### Link to OSM Wiki page

https://wiki.openstreetmap.org/wiki/Tag:office%3Dengineer

### Status of the Tag

In Use

### Usage of the tag

1,015

**Comment by tyrasd** [comment]
> Label

Maybe _engineering office_ would be a slightly more fitting label?
