### ISSUE TITLE
emergency=dry_riser_inlet

### ISSUE THREAD

**Issue by DiogoBaptista98** [openstreetmap/id-tagging-schema#642]
### OSM Tag(s)

emergency=dry_riser_inlet

### How would you like this tag to see supported?

As a Preset

### Label

Dry riser

### Link to OSM Wiki page

https://wiki.openstreetmap.org/wiki/Tag:emergency%3Ddry_riser_inlet

### Status of the Tag

Approved

### Usage of the tag

1,224

**Comment by tyrasd** [comment]
:+1:

Should _Fire Department Connection_ be an alias for this preset (and _fdc_ a term)? I saw these mentioned on the wiki page of the tag.

**Comment by DiogoBaptista98** [comment]
> 👍
> 
> Should _Fire Department Connection_ be an alias for this preset (and _fdc_ a term)? I saw these mentioned on the wiki page of the tag.

Yes you’re right! 🙏

**Comment by matkoniecz** [comment]
there is some ongoing discussion how to tag riser inlets that re not dry

**Comment by kjonosm** [comment]
> there is some ongoing discussion how to tag riser inlets that re not dry

@matkoniecz: Where does that discussion take place? And is that a reason to not add a preset for `emergency=dry_riser_inlet`?

**Comment by k-yle** [comment]
> Where does that discussion take place?

Hi, there is a proposal to deprecate this tag and replace it with a more flexible system. The proposal is **[here](https://wiki.osm.org/Proposal_features/Building_inlet)** and [the discussion is also happening on the wiki](https://wiki.osm.org/Talk:Proposal_features/Building_inlet).

**Comment by matkoniecz** [comment]
There was also some discussion on tagging mailing list and/or the official forum.

**Comment by tyrasd** [comment]
superseded by https://github.com/openstreetmap/id-tagging-schema/pull/806
