### ISSUE TITLE
"roof/colour" preset doesn't use the new "colour" type

### ISSUE THREAD

**Issue by bryceco** [openstreetmap/id-tagging-schema#647]
It's great to see the new colour type. It looks like it is only being used by the "colour" field, but not "roof/colour". There are also colors for seamarks but I think those are being treated special already (https://github.com/openstreetmap/id-tagging-schema/issues/512).

Also I think https://github.com/openstreetmap/id-tagging-schema/issues/284 can be closed now.

**Comment by tyrasd** [comment]
Thanks for the hint!
