### ISSUE TITLE
Schema documentation missing

### ISSUE THREAD

**Issue by westnordost** [openstreetmap/id-tagging-schema#65]
When the presets were still part of the iD project, there used to be an extensive documentation on the fields used and what they are used for. For example here:

https://github.com/openstreetmap/iD/blob/v2.15.2/data/presets/README.md

This documentation seems to be missing now.

**Comment by quincylvania** [comment]
@westnordost The documentation has been moved [here](https://github.com/ideditor/schema-builder#source-files), as linked in the readme.

**Comment by westnordost** [comment]
Thanks, Is seem to have missed it
