### ISSUE TITLE
Running `npm run test` locally results in an error

### ISSUE THREAD

**Issue by arch0345** [openstreetmap/id-tagging-schema#655]
**Describe the bug**
Running `npm run test` locally results in an error. This used to work before the release of v5

**To Reproduce**
1. Run `npm install`
2. Run `npm run test`

**Expected behavior**
![image](https://user-images.githubusercontent.com/85302075/204174443-53ebad81-f436-460c-b5d6-0abe35d1c799.png)
Prints out `schema okay` or an error related to code you've added.

**Screenshots**
![image](https://user-images.githubusercontent.com/85302075/204174279-99ae5d68-1d4a-4018-acc7-3469f86919e4.png)
This is the error I'm getting.

**Comment by tyrasd** [comment]
:thinking: I cannot reproduce this error as this works fine for me. Also for a freshly checked out version of the repository. I assume you have no local changes made to the repo? Would you mind sharing which versions of `node`, `npm` and operating system you are running?

**Comment by tyrasd** [comment]
Wait, I _do_ see this when running `npm test` on windows. Might be related to https://github.com/ideditor/schema-builder/pull/55
