### ISSUE TITLE
Question: dist/translations/en.json superfluous?

### ISSUE THREAD

**Issue by westnordost** [openstreetmap/id-tagging-schema#67]
So far I assumed that the localizable strings in `presets.json` were all in English (`en`). However, there is the file `dist/translations/en.json`. 

My question would be: Are the contents for the strings in that file 1:1 the same as the localizable strings in the `presets.json`? If yes, are there any plans to remove the localizable strings from the `presets.json` or can I assume that this "default translation" will stay in the `presets.json`?

**Comment by westnordost** [comment]
* except suggestions (brand names) of course as they are not translated.

**Comment by westnordost** [comment]
Nevermind, turns out it is not relevant for my implementation.

**Comment by quincylvania** [comment]
@westnordost That's an interesting point. iD could avoid some download size by avoiding this duplication. I'm not sure what changes would be needed, but it's something to think about.
