### ISSUE TITLE
UK post box fields

### ISSUE THREAD

**Issue by boothym** [openstreetmap/id-tagging-schema#670]
In the UK, there are two well-used tag fields which are missing from the post box preset - namely post_box:type and royal_cypher, see https://taginfo.openstreetmap.org.uk/tags/amenity=post_box#combinations

Meanwhile the drive_through field is in the preset despite it being highly unlikely that you will find a drive through post box in the UK. It is only used 61 times out of 6,000 for something other than "no", and I'm guessing some of these will be mapping errors.

Don't know if it is possible, but could this be changed just for one country?

**Comment by tyrasd** [comment]
> Don't know if it is possible, but could this be changed just for one country?

Yes, we can define are regional presets/fields using the [`locationSet`](https://github.com/ideditor/schema-builder#locationset) property.

**Comment by UKChris-osm** [comment]
How would this be achieved?

Would the current [post_box.json](https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/amenity/post_box.json) file need to have a locationSet exclusion, such as:

`"locationSet": {`
`"exclude": ["gb"]`
`},`

... added to it? And then a new copy of the file created with a different name and amended tagging, such as "_post_box_gb.json_" containing:

`"locationSet": {`
`"include": ["gb"]`
`},`
