### ISSUE TITLE
Marked Crossing Ways now default to crossing=uncontrolled instead of crossing=marked

### ISSUE THREAD

**Issue by pardthemonster** [openstreetmap/id-tagging-schema#715]
**Describe the bug**
Creating Marked Crossing ways now defaults to `crossing=uncontrolled` instead of `crossing=marked`.

**Expected behavior**
Similar to Unmarked Crossings, I would expect when creating, that tag be `crossing=marked`, but instead is now `crossing=uncontrolled`.

**Comment by 1ec5** [comment]
See #568 and #408 for previous discussion.
