### ISSUE TITLE
Do not suggest service:bicycle:rental

### ISSUE THREAD

**Issue by Adamant36** [openstreetmap/id-tagging-schema#719]
### Deprecated OSM Tag(s)

service:bicycle:rental

### Replacement OSM Tag(s)

bicycle_rental, rental

### Link to OSM Wiki page

https://wiki.openstreetmap.org/wiki/Proposed_features/bicycle_rental:type

### Further Information

There was a vote [here](https://wiki.openstreetmap.org/wiki/Proposed_features/bicycle_rental:type) in January to approve the usage of both bicycle_rental and rental for places that rent bicycles. So iD Editor should stop suggesting service:bicycle:rental since it's clearly depreciated by the approved tags. Unfortunately the proposals a little convoluted, but I assume the alternatives would be either shop=bicycle_rental + bicycle_rental=shop, simply bicycle_rental=yes, or some other bicycle_rental=* tag depending on what is being mapped. 

Thanks.

**Comment by Lukas458** [comment]
The only pity of that is, of course, is that the whole thing falls out of the acutually uniform service:bicycle tagging scheme then (https://wiki.openstreetmap.org/wiki/Key:service:bicycle:*).

**Comment by tyrasd** [comment]
I think for the situation where iD is using the `service:bicycle:rental`, i.e. for bike shops which also rent out bikes, the new tag does not apply: 

> When not to use this tag: 
> […]
> For a bicycle shop which also happens to rent out bikes. These get [`shop=bicycle`](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dbicycle) + [`service:bicycle:rental=yes`](https://wiki.openstreetmap.org/wiki/Key:service:bicycle:rental).

**Comment by Lukas458** [comment]
I also got it so that especially `bicycle_rental` is a subtag for `amenity=bicycle_rental` and for `shop=bicycle_rental`.

For `shop=bicycle`, it would then dance out of line:

`service:bicycle:pump=yes`
`service:bicycle:retail=yes`
`service:bicycle:cleaning=yes`
`service:bicycle:second_hand=yes`

So that's exactly the reason why `service:bicycle:rental` stays for these, as @tyrasd mentioned, as said in https://wiki.openstreetmap.org/wiki/Proposed_features/bicycle_rental:type

**Comment by Adamant36** [comment]
> For shop=bicycle, it would then dance out of line: service:bicycle:second_hand=yes

Not to side track the discussion, but in that case wouldn't the correct tag be **`second_hand=*`**?

**Comment by Lukas458** [comment]
> > For shop=bicycle, it would then dance out of line: service:bicycle:second_hand=yes
> 
> Not to side track the discussion, but in that case wouldn't the correct tag be **`second_hand=*`**?

Oops ¯\_( ͡❛ ͜ʖ ͡❛)_/¯

But there we see again that there are - depending on the rest of the object/ the use case - different tags for the same statement.

One way is "as simple as possible before complicated" and "don't invent two tags for saying the same thing",

the other way is "ONE tagging scheme, in itself as uniform as possible, at least for one and the same use case".
