### ISSUE TITLE
Taginfo Projects: Generalize project description

### ISSUE THREAD

**Issue by danieldegroot2** [openstreetmap/id-tagging-schema#726]
iD editor, Go Map!! and Overpass are specifically mentioned in the project description, while applications like Every Door are also using data from this project - a more generalized description would be better in this case.

https://taginfo.openstreetmap.org/projects/id_editor

**Comment by 1ec5** [comment]
How about mentioning Every Door in the description too? It could be useful to name other editors in the project description (and also in the readme); otherwise, people might mistakenly think this project is just about iD, based on the name.

**Comment by danieldegroot2** [comment]
Let me clarify "generic description" (feel free to dislike the post, it's up to you), it _could_
- say "and other editors" (generalized) and this could be true for other projects. Taginfo could then consider a feature which lets projects indicate which other projects are using it.
- specify as many editors as it wants in the description, but imo a project description should describe the project _itself_, it can't describe all the applications which are using its data, just like taginfo can
- name a few examples (besides "and other applications"), that'd be fine too, though _within taginfo_ it could become inconsistent with other projects which might also like to display this. It'd go something like either of these
-- "used in the iD editor, editor A, software B and other applications"
-- "used in the iD editor and applications like editor A and software B"
- not name any at all and only specify it in the readme or another file in the project

Those are just some options, it's up to you. I'm not creating an issue to force one of these options onto you..

**Comment by danieldegroot2** [comment]
This is also at least partially covered by the "Used by" section on GitHub, which lists some repositories using it as dependency. Mentioning the notable ones can't hurt, of course.
