### ISSUE TITLE
golf=driving_range suggests "+ landuse=grass" instead of surface=grass

### ISSUE THREAD

**Issue by pardthemonster** [openstreetmap/id-tagging-schema#727]
**Describe the bug**
[Wiki page](https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dgolf_course) discourages `landuse=*` (grass) for `golf=*` features and suggests to use `surface=*` (grass) instead.

**Comment by tordans** [comment]
Probably related https://github.com/openstreetmap/id-tagging-schema/issues/534
