### ISSUE TITLE
`traffic_calming=table` on a way is a valid combination

### ISSUE THREAD

**Issue by Dimitar5555** [openstreetmap/id-tagging-schema#733]
**Describe the bug**
When a crossing which is mapped as way has `traffic_calming=table`, the validator raises a warning that it should be an area.

**To Reproduce**
1. Open https://www.openstreetmap.org/edit?way=1072051270#map=19/42.68599/23.32891

**Expected behavior**
There should be no warning

**Screenshots**
![image](https://user-images.githubusercontent.com/19364673/212341786-54bc4fb3-e009-4566-966d-fd40effbaba9.png)

**Additional context**
N/A

**Comment by tyrasd** [comment]
Good catch! This was an unintended side-effect of a change in the latest version (v5.2.0) of the tagging schema, which I didn't see while testing. For a reason which I still have to figure out (and fix), iD's validator doesn't take into account that the tag in question (here: `traffic_calming`) can be either a standalone preset, but also a property (field) of another preset. The geometry-check should not be triggered in the case where the tag is used as a field of a preset.

I've resolved the issue for now by reverting the change of the traffic calming presets and issued a hotfix release containing the fix: v5.2.1.

**Comment by ireun** [comment]
@tyrasd I don't think `traffic_calming=island` should be allowed on areas. 
[Wiki](https://wiki.openstreetmap.org/wiki/Tag%3Atraffic_calming%3Disland) states that `area:highway=traffic_island` should be used instead. And `traffic_calming=*` should be used only on nodes or ways.
