### ISSUE TITLE
Post Boxes suggesting brand as Post Office instead of Royal Mail

### ISSUE THREAD

**Issue by timothywashere** [openstreetmap/id-tagging-schema#738]
When editing a postbox with the brand "Royal Mail", eg https://www.openstreetmap.org/node/624633219
It suggests the following edit, which I believe is entirely incorrect

```
Some features, for example retail chains or post offices, are expected to have certain tags in common.
Suggested updates:
- brand=Royal Mail
+ brand=Post Office
- brand:wikidata=Q638098
+ brand:wikidata=Q1783168
- operator=Royal Mail
+ operator=Post Office
- operator:wikidata=Q638098
+ operator:wikidata=Q1783168
```

The Post Office operate shops where you can send letters and a lot more
The postal network is operated by Royal Mail. Post boxes are operated by Royal Mail

They are two serate brands and have different ownership.

**To Reproduce**
Edit any postbox in the UK with Royal Mail brand / operator tags set

**Expected behavior**
Suggests Royal Mail brand tags if not completely set. Should not suggest Post Office

**Comment by tyrasd** [comment]
Confirming. But this is not an issue with the id-tagging-schema itself, but rather with the name-suggestion-index (NSI). I've opened an issue there, with some preliminary findings I made while debugging this problem. See https://github.com/osmlab/name-suggestion-index/issues/7660 for further details.

**Comment by timothywashere** [comment]
> Confirming. But this is not an issue with the id-tagging-schema itself, but rather with the name-suggestion-index (NSI). I've opened an issue there, with some preliminary findings I made while debugging this problem. See [osmlab/name-suggestion-index#7660](https://github.com/osmlab/name-suggestion-index/issues/7660) for further details.

Thank you

**Comment by UKChris-osm** [comment]
This should now be fixed with a new update to the NSI data in iD - my apologies for the mistake occurring.

**Comment by tyrasd** [comment]
Thanks for the quick fix, @UKChris-osm ! 

PS @timothywashere it might be the case that your browser still has the previous version of the NSI data cached (it's kept for 1 week by default). To get the fixed version immediately, you might need to manually clear the browser cache.
