### ISSUE TITLE
Add amenity=cannabis_dispensary

### ISSUE THREAD

**Issue by TalOrenshtein** [openstreetmap/id-tagging-schema#739]
### OSM Tag(s)

cannabis_dispensary

### How would you like this tag to see supported?

As a Field

### Label

Cannabis dispensary

### Aliases

Weed dispensary

### Terms

Cannabis, weed, dispensary

### Link to OSM Wiki page

none

### Status of the Tag

Approved

### Usage of the tag

~~303~~ //edit @tyrasd 0 occurences

### Replaces other Tag?

Not

### Regional Tag?

global

**Comment by tyrasd** [comment]
> amenity=cannabis_dispensary

I cannot find any occurences of this tag in osm (see [taginfo](https://taginfo.openstreetmap.org/tags/amenity=cannabis_dispensary#overview)), and the osm wiki also doesn't have any info about it. Did you maybe mean [`shop=cannabis`](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dcannabis)?

**Comment by TalOrenshtein** [comment]
> > amenity=cannabis_dispensary
> 
> I cannot find any occurences of this tag in osm (see [taginfo](https://taginfo.openstreetmap.org/tags/amenity=cannabis_dispensary#overview)), and the osm wiki also doesn't have any info about it. Did you maybe mean [`shop=cannabis`](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dcannabis)?

Year that's it. So I guess it does appear, I wonder why it doesn't show at my clients... Anyway, closing this.

**Comment by tyrasd** [comment]
> I wonder why it doesn't show at my clients

In 9c1669f80d443357d484c1c005287e2db2a01af1, I've added "cannabis dispensary" explicitly as a possible search  term for `shop=cannabis`.
