### ISSUE TITLE
Provide also NSI data in a presets.full.json?

### ISSUE THREAD

**Issue by westnordost** [openstreetmap/id-tagging-schema#74]
Since the commit for 2.0.0, the NSI data seems to be missing from the presets.

If this was deliberate, are you planning to provide an alternative `presets.json` with that data included?

**Comment by westnordost** [comment]
I've looked at https://github.com/osmlab/name-suggestion-index/blob/main/dist/presets/name-suggestions.json which I guess would be the "raw" distribution, however the format is quite a bit different. So if I was to write a new parser for that, I'd need to do some research on that. 

A few things that I see:
- There is no `addTags`(, `removeTags`) though even though this information is necessary because there is a difference between "full tagging" of a brand and tagging that makes the NSI/iD recognize that it is this or that brand. Without this differenciation I don't really know what to do with that data
- The `imageURL` is missing
- categorization is different than in the `presets.json`

**Comment by bhousel** [comment]
>So if I was to write a new parser for that, I'd need to do some research on that.

You don't have to do that - my plan is to just generate presets for NSI that conform to the id tagging schema once it settles.
https://github.com/osmlab/name-suggestion-index/issues/4718

**Comment by westnordost** [comment]
What does that mean? Does this mean that the NSI will become the go-to-place to get the "full" `presets.json`? Or does it mean that there will (soon) be a `nsi-presets.json` in the dist folder in the NSI repository that has the same schema as the id-tagging-schema?

**Comment by bhousel** [comment]
> Or does it mean that there will (soon) be a `nsi-presets.json` in the dist folder in the NSI repository that has the same schema as the id-tagging-schema?

☝️ this one

**Comment by westnordost** [comment]
Ok nice, but then my initial question remains:

> are you planning to provide an alternative presets.json with that data included?

It would be more convenient (for me) to have only one file to download that included everything.

**Comment by quincylvania** [comment]
> are you planning to provide an alternative presets.json with that data included?

Not presently. As part of making iD more modular, the idea is to be able to support preset packs from multiple sources rather than having everything live in one big file. Though we'll have to see how this works in practice.

**Comment by westnordost** [comment]
Ok I added this functionality (to load presets.jsons + translations if any from several sources) to the osmfeatures library. However I did not release the new version yet in case some more changes to the schema will appear in the next days. I have the impression that the dust did not settle on v2.0.0 yet.

**Comment by quincylvania** [comment]
@westnordost Great. Things are still changing, yes, but now with version control this should be a bit easier to account for.
