### ISSUE TITLE
change parking:orientation to orientation

### ISSUE THREAD

**Issue by kaneap** [openstreetmap/id-tagging-schema#740]
### OSM Tag(s)

orientation=*

### How would you like this tag to see supported?

As a Field

### Label

(no change from existing preset)

### Link to OSM Wiki page

https://wiki.openstreetmap.org/wiki/Key:orientation

### Status of the Tag

Approved

### Usage of the tag

14,955

### Replaces other Tag?

parking:orientation=*

### Further Information

`parking:orientation=*` for `amenity=parking` was deprecated with the new street parking proposal. ID should support the new tagging scheme and offer to upgrade old tags.

**Comment by tyrasd** [comment]
Thanks for the suggestion. This one was however already proposed in #673. :slightly_smiling_face:
