### ISSUE TITLE
inclined elevators

### ISSUE THREAD

**Issue by troposphhere** [openstreetmap/id-tagging-schema#75]
Following a discussion on the tagging mailing list, I wonder if it would be valuable to have a preset with `highway=elevator` on a way to map inclined elevators. This is explicitly supported by [the wiki](https://wiki.openstreetmap.org/wiki/Tag:highway%3Delevator#How_to_map_as_a_way).
`railway=funicular` is often used for that purpose instead, but there are many indoors inclined elevators that really look and behave like regular elevators and not funiculars at all; see for example the left of the picture in [this article](http://nyttiflempan.sh.se/flemingsberg/2015-04-21/S%C3%B6dert%C3%B6rns-rulltrappa-en-huvudv%C3%A4rk-f%C3%B6r-kommunen-12389.html) or on the right [here](https://www.sll.se/verksamhet/kollektivtrafik/aktuella-projekt/hissar-och-rulltrappor/). 

Those elevators are not displayed on the default OSM map, and one of the arguments against supporting them there is that they are rare in the database... but I suspect they are rare mostly because they are not supported by editors in the first place. I personally know several of those elevators around Stockholm, and they may be common in other places too.

In addition, when typing "elevator" in the search bar for the feature type when selecting a way, only irrelevant results appear, which might lead some features to be incorrectly tagged.
Right now this is what I get on Firefox:
![elevator_search](https://user-images.githubusercontent.com/17337046/101261321-acb16280-3736-11eb-84b3-ff47486cb9a9.png)

**Comment by quincylvania** [comment]
This sounds okay. Elevators are important for accessibility, so we should try to support them as completely as we can. I don't expect most mappers to know the technical difference between inclined elevators and funiculars, but I expect most could look at a large cable railways versus a small urban elevator and know which is which.

One thing to note is that there are some `highway=elevator` micromapped as areas in OSM, and if they're missing `area=yes` then iD will erroneously consider them to be inclined elevator lines.
