### ISSUE TITLE
Cycle & Foot Path preset missing from search results in France

### ISSUE THREAD

**Issue by davidpnewton** [openstreetmap/id-tagging-schema#759]
**Describe the bug**

When searching for presets for cycle tracks in France using the search string "cycle &" the presets Cycle & Foot Crossing and Cycle & Foot Path do not show up in the presets list whereas in the UK the same search produces those presets as part of the results. Such paths occur both in the UK and France as the presets cover both segregated and unsegregated versions of such paths.

**To Reproduce**

Search for presets using the search string "cycle &" when over an area of France.

**Expected behavior**

Presets Cycle & Foot Crossing and Cycle & Foot Path showing up in the search results.

**Screenshots**

![image](https://user-images.githubusercontent.com/74616419/214577251-a6a899db-e331-486a-89c9-3e8395027a2d.png)

**Comment by tyrasd** [comment]
the preset has an explicit exception to not show up in France (and some other countries), see https://github.com/openstreetmap/iD/issues/6836#issuecomment-529391949 

If I understood this right, this is because the preferred tagging of a "Cyle & Foot Path" in France is `highway=path + bicycle=designated + foot=designated`. Is that right?

In this case, it would make sense to provide an additional preset for cycle-and-foot paths in these countries using the `highway=path` tagging variant.

**Comment by davidpnewton** [comment]
Ah. I see it's the same sort of exceptionalism as the silly treatment of addresses in France. Aka not wanting the consistent treatment and tagging of things just because.

It's one thing where there are genuine legal differences. Priorite a droite's an example of that. Are there places in France with segregated cycle track and pavement where the only segregation is a white line? Yes. One of them is exactly where I wanted to use the correct preset.

Solution? Consistent tagging. Where there is a genuine need for different tagging such as legal differences then support it and encourage its use. If it's just some people being contrary, even if it's an entire national community being contrary, then it needs to be treated as such.

This is a substantive difference. It produces different renderings. It causes unnecessary complications for data consumers. Therefore it needs to be eliminated. Choose one scheme or the other. Then eliminate the second.

**Comment by tordans** [comment]
This was added in https://github.com/openstreetmap/id-tagging-schema/pull/1384
Please use [the PR preview](https://pr-1384--ideditor-presets-preview.netlify.app/id/dist/#locale=en) to test it out.
