### ISSUE TITLE
A few new presets for NSI

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/id-tagging-schema#76]
NSI is depending on this repo for presets now - see https://github.com/osmlab/name-suggestion-index/issues/4718! 

Here are some features being tracked in NSI that we didn't find iD presets for in the latest build:
- [ ] Warning - no iD source preset found for amenity/motorcycle_rental
- [ ] Warning - no iD source preset found for office/security
- [ ] Warning - no iD source preset found for shop/repair
- [ ] Warning - no iD source preset found for emergency/lifeboat_station
- [ ] Warning - no iD source preset found for route/aerialway

**Comment by bhousel** [comment]
Thanks! 👍

**Comment by quincylvania** [comment]
@bhousel Sure! Thanks for all your great work on NSI 🚉
