### ISSUE TITLE
"psychiatrist" is not finding anything

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/id-tagging-schema#778]
![screen02](https://user-images.githubusercontent.com/899988/216838123-f51a6826-13f4-4791-bdac-d54ed00b14b5.png)

compare results for chiropractic

![screen03](https://user-images.githubusercontent.com/899988/216838139-d7f169ec-02ee-4b76-b8b0-59ded1391dd5.png)

If chiropractic gets results then psychiatrist likely also should

**Comment by matkoniecz** [comment]
They seem to be missing from https://github.com/openstreetmap/id-tagging-schema/tree/main/data/presets/amenity/doctors

**Comment by westnordost** [comment]
What about psychotherapist? This is different from what a psychiatrist does, I think.

**Comment by HolgerJeromin** [comment]
> What about psychotherapist? This is different from what a psychiatrist does, I think.

Yes. At least in Germany the education is different (last one is a full medical doctor).

**Comment by tyrasd** [comment]
> psychotherapist

For reference: these are not mapped as `amenity=doctors` in OSM, and already had a dedicated preset ([`healthcare=psychotherapist`](https://github.com/openstreetmap/id-tagging-schema/blob/v5.2.1/data/presets/healthcare/psychotherapist.json)) for a while.
