### ISSUE TITLE
Deprecate leisure=table_tennis_table

### ISSUE THREAD

**Issue by westnordost** [openstreetmap/id-tagging-schema#78]
I noticed `leisure=table_tennis_table`. It is used 140 times worldwide.

On https://wiki.openstreetmap.org/wiki/Tag%3Aleisure%3Dtable_tennis_table it is 
- ...since 9th October 2016‎ described as **less used than** `leisure=pitch + sport=table_tennis` and **confusing** to use
- ...since 29th April 2020‎ still described as such but **framed in a red warning box**

![taghistory(2)](https://user-images.githubusercontent.com/4661658/101695586-1bfbbf00-3a75-11eb-9b94-617e3fe3b932.png)
https://taghistory.raifer.tech/#***/leisure/table_tennis_table&***/sport/table_tennis

**Comment by westnordost** [comment]
I created a PR in which I copy&pasted the description.

**Comment by quincylvania** [comment]
> I created a PR in which I copy&pasted the description.

That's fine, but generally if you want to create issues we'd leave them open until the PR is merged, and then link to the issue in the PR. Alternatively you can just open PRs without issues.
