### ISSUE TITLE
shed / workshop 

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/id-tagging-schema#801]
Please see https://github.com/simonpoole/beautified-JOSM-preset/issues/366

**Comment by tyrasd** [comment]
I don't understand. https://github.com/simonpoole/beautified-JOSM-preset/issues/366 claims that _"Searching for shed only finds building part"_, but it obviously works in iD:

![image](https://user-images.githubusercontent.com/1927298/221402866-74992afa-e4e7-4e03-8d04-5511ac55c98d.png)

Did you mean to link https://github.com/simonpoole/beautified-JOSM-preset/issues/365?
