### ISSUE TITLE
Allow tagging crossing without specifying variety (just highway=crossing)

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/id-tagging-schema#834]
Sometimes memory or aerial is not good enough to specify exact one 0 for example presence of traffic signals may be not entirely clear.

On node within way:

![screen01](https://user-images.githubusercontent.com/899988/227155318-30d68ca2-bbf7-4037-8d12-02348822d21c.png)

**Comment by tyrasd** [comment]
:+1:  This would require to make the `highway/_crossing.json` preset searchable and potentially renaming it to something like `Crossing (Unspecified Type)`.

**Comment by 1ec5** [comment]
Just “Crossing” is probably sufficient. There are some other unspecified-type presets that we give simpler names, such as “Building”. But if we need to differentiate, I’d suggest saying something about a “path–road crossing” or somesuch, to differentiate it from “Railway–Road Crossing” and “Railway–Railway Crossing”. (The standard real-world term for these is “road crossing”, but users could be confused about when they’re supposed to use one preset versus another.)

**Comment by matkoniecz** [comment]
What about "Pedestrian Road Crossing"? path has a bit messy implications as a term, some are sure that it is invalid for sidewalks (which is BTW causing problem with people retagging `highway=path surface=paved bicycle=designated foot=designated segregated=yes`)

**Comment by 1ec5** [comment]
“Pedestrian Road Crossing” would be an accurate description of most occurrences of `highway=crossing`. However, in many regions, it’s also normal to use `highway=crossing` for where a cycleway crosses a road or a footway crosses a cycleway. On the other hand, the icon already depicts a pedestrian, so it’d be no more misleading than before.

**Comment by matkoniecz** [comment]
Is it possible to have different preset match based on way where it is a vertex? Probably no.

**Comment by tyrasd** [comment]
> Is it possible to have different preset match based on way where it is a vertex? Probably no.

No, that's not currently possible in the tagging schema, unfortunately. iD could however implement a validation rule that any `highway=crossing` node should always be on a `highway=*` way (and any `footway/cycleway=crossing` way should intersect a `highway=*` way). iD could also suggest a fix to convert the `highway=crossing` mapped on – say – a railway to the appropriate key (`railway=crossing` in that case).
