### ISSUE TITLE
iD recommends adding barrier=kerb to kerb=* when it shouldn't

### ISSUE THREAD

**Issue by osmuser63783** [openstreetmap/id-tagging-schema#858]
**Describe the bug**
When `kerb=*` appears by itself on a node, iD recommends adding `barrier=kerb`. This is a problem because `barrier=kerb` implies that anyone travelling over the node has to cross a kerb, but `kerb=raised` often appears on nodes that are part of roads, at the location where the footway meets the road, to say that there is a high kerb on each side of the road. (`kerb=raised` is used this way by StreetComplete) There is community consensus that adding `barrier=kerb` here is wrong.

**To Reproduce**
1. Find any node where `kerb=raised` appears by itself on a node that is part of a road ([Overpass query](https://overpass-turbo.eu/s/1tt3)) and open it in iD.
2. You'll see that iD says that "Raised kerb has incomplete tags"
3. If you "upgrade" the tags it will lead to unexpected results - for example, OSRM will no longer route cars over it because it avoids `kerb=raised` in its default car profile.

**Expected behavior**
`kerb=raised` without `barrier=kerb` should not be considered to have incomplete tags. No action should be recommended by iD.

**Screenshots**
![Screenshot 2023-03-31 at 10 43 53_2](https://user-images.githubusercontent.com/127188803/230591167-91ff52d0-83bc-427b-8271-a64a5532dec6.png)

**Additional context**
This has been reported as a [bug in OSRM](https://github.com/Project-OSRM/osrm-backend/issues/6582) but I think it is iD's behaviour that should change.

More background info can be found in this [community discussion](https://community.openstreetmap.org/t/tagging-kerbs-on-crossings/9290).

Maybe the problem is with the preset [`kerb/raised.json`](https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/barrier/kerb/raised.json)? Can this file be modified so that iD still includes a preset `barrier=kerb kerb=raised` but `kerb=raised` without `barrier=kerb` is no longer considered incomplete?

**Comment by tyrasd** [comment]
If I read the [wiki](https://wiki.openstreetmap.org/w/index.php?title=Key:kerb&oldid=2501049#By_itself) correctly, this situation occurs when one wants to use the `kerb` key to indicate the accessibility properties of a road crossing. I.e. when the vertex has at least also the `highway=crossing` tag.

Unfortunately, it seems that streetcomplete doesn't add the `highway=crossing` tag in such situations, which seems to be a bit questionable to me. But that's a bug for another day/repo, I guess. :innocent: 

#862 adds the `kerb` tag as an optional field for crossing nodes, and makes the match for the `barrier=kerb` presets stricter, to fix this bug. Can you double-check at https://pr-862--ideditor-presets-preview.netlify.app/id/dist/#locale=en if it works as exptected?

**Comment by osmuser63783** [comment]
This is great, thanks for fixing this. I can confirm that it works as expected, the user no longer gets prompted to "upgrade" nodes tagged `kerb=raised` by adding `barrier=kerb`.

When playing with the preview, I noticed some odd (and maybe unintended?) side effects of  #837.
- an unspecific crossing (i.e. a node that only has highway=crossing) doesn't have an icon on the map
- when you add an unspecified crossing and then click the yes under raised, the node turns into a feature type "speed table", so the suggested fields for a crossing disappear and those for a speed table show up
- when you add an unspecified crossing and then select the crossing type "island", this sets `crossing=island` and immediately prompts a warning about outdated tags

Also (unrelated to #837), changing the type of a crossing to `crossing=no` doesn't remove `highway=crossing`, but it probably should.

Should I create separate bug reports for these?

**Comment by tyrasd** [comment]
> Should I create separate bug reports for these?

yes, please.

**Comment by westnordost** [comment]
> Unfortunately, it seems that streetcomplete doesn't add the highway=crossing tag in such situations, which seems to be a bit questionable to me. But that's a bug for another day/repo, I guess. 😇

I explained why here:

https://community.openstreetmap.org/t/tagging-kerbs-on-crossings/9290/24
