### ISSUE TITLE
prefix on a waterway

### ISSUE THREAD

**Issue by Mahabarata** [openstreetmap/id-tagging-schema#861]
When using a prefix on an old canal (like demolished:waterway=canal or abandoned: or disused:), iD shows a warning telling us that the unclosed way should be an area.

**Comment by matkoniecz** [comment]
on the other hand such tagging (lifecycle prefixes on ladforms) is quite dubious, so should not be encouraged or presented as valid

**Comment by k-yle** [comment]
This was fixed 3 months ago in https://github.com/openstreetmap/iD/pull/9483 but that PR still hasn't been merged

**Comment by Mahabarata** [comment]
Ok, perfect, so I close this issue.
