### ISSUE TITLE
Add `amenity=kneipp_water_cure` with subtags

### ISSUE THREAD

**Issue by tordans** [openstreetmap/id-tagging-schema#866]
### OSM Tag(s)

amenity=kneipp_water_cure

### How would you like this tag to see supported?

As a Preset

### Label

[_Kneipp facility_](https://en.wikipedia.org/wiki/Kneipp_facility) 

### Aliases

Maybe Hydrotherapy?

### Link to OSM Wiki page

https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dkneipp_water_cure

### Status of the Tag

Approved

### Usage of the tag

2,200

### Replaces other Tag?

No

### Regional Tag?

Could be Germany and Austria, see https://taginfo.openstreetmap.org/tags/amenity%3Dkneipp_water_cure#map

### Further Information

Not a too much usage but something I want to map but have to look up every time I see it. 

The additional fields are quite useful, but have little usage, yet.
* 800 https://taginfo.openstreetmap.org/keys/kneipp_water_cure%3Afoot
* 400 https://taginfo.openstreetmap.org/keys/kneipp_water_cure%3Aarm#overview

**Comment by tyrasd** [comment]
there already exists a preset: [`amenity/kneipp_water_cure.json`](https://github.com/openstreetmap/id-tagging-schema/blob/v6.1.0/data/presets/amenity/kneipp_water_cure.json) and field: [`fields/kneipp_water_cure_multi.json`](https://github.com/openstreetmap/id-tagging-schema/blob/v6.1.0/data/fields/kneipp_water_cure_multi.json) for this tag & subtags. see https://github.com/openstreetmap/iD/pull/7332

The field is missing translatable strings and the preset could use some terms / aliases, but otherwise it should be already quite usable…

**Comment by tordans** [comment]
Thanks! Don't know why I did not see it before 🤷 :).

The terms look good at https://app.transifex.com/openstreetmap/id-editor/translate/#de/presets/192709229?q=key%3Akneipp_water_cure. 

Found a small issue in GoMap that was reported and fixed (no values showed for the `:arm` … sub-tags).

We could think about adding a custom Icon like suggested in https://wiki.openstreetmap.org/wiki/File:Kneipp_water_cure.svg, but thats not worth the effort for just 2k items IMO. => Closing this issue.

**Comment by tordans** [comment]
Reopening this after talking to @bryceco. Right now, the multiCombo https://github.com/openstreetmap/id-tagging-schema/blob/main/data/fields/kneipp_water_cure_multi.json does not list keys, so it relies on taginfo lists. Which is an issue, since the keys have little use, so they fall below a threshold to be visible.

An easy fix would be to add "foot", "arm" as explicit strings like in https://github.com/openstreetmap/id-tagging-schema/blob/2fce8f986ab632b69437e86b7cf46debbf868cd5/data/fields/plant/output.json#L5-L16 for example. (I would only add those two, since they are actually "in use".

>kneipp_water_cure:foot – 800
kneipp_water_cure:arm – 400
kneipp_water_cure:face – just 40 https://taginfo.openstreetmap.org/keys/kneipp_water_cure%3Aface#overview
kneipp_water_cure:cold_affusion – just 10 https://taginfo.openstreetmap.org/keys/kneipp_water_cure%3Acold_affusion#overview

**Comment by tordans** [comment]
Thanks a lot, @tyrasd
