### ISSUE TITLE
Milk churn stand

### ISSUE THREAD

**Issue by b-unicycling** [openstreetmap/id-tagging-schema#869]
### OSM Tag(s)

man_made=milk_churn_stand

### How would you like this tag to see supported?

As a Preset

### Label

Milk churn stand

### Aliases

milk can stand

### Link to OSM Wiki page

https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dmilk_churn_stand

### Status of the Tag

In Use

### Usage of the tag

485 (2023-04-23)
502 (2023-04-25)
517 (2023-04-27)
570 (2023-05-01)
605 (2023-05-04)
620 (2023-05-06)
641 (2023-05-09)
704 (2023-05-16)
755 (2023-05-30)

### Regional Tag?

global

### Further Information

I had introduced this tag in March 2023 and wrote [a diary post](https://www.openstreetmap.org/user/b-unicycling/diary/401218) about it. WeeklyOSM [mentioned it](https://weeklyosm.eu/archives/16399) shortly after. 
The usage of the tag has since taken off, especially in Finland, where ca. 275 ([overpass-turbo](http://overpass-turbo.eu/s/1tPn)) have been mapped since Easter Sunday. I have been approached by a Finnish mapper, if it could be made easier for mapping beginners using iD by allowing them to type "maitolaituri" (Finnish for "milk churn stand") into the iD editor search. It would really help making it easier for new mappers; some might stick around for more mapping.

[Global search on overpass-turbo](http://overpass-turbo.eu/s/1tPo).

I've tried to make sure to have all types of words for them recorded in different languages on [wikidata](https://www.wikidata.org/wiki/Q10586871) as well.

### Suggested tags to ask for in preset (on node or area)
`disused`: yes/ no/ unknown
`material`
`description`
`wikimedia_commons`
`mapillary`
`check_date`

**Comment by tyrasd** [comment]
It's a pretty rare map feature, but I see no harm in adding a preset for it. Only thing is that we don't seem to have a matching [icon](https://github.com/ideditor/schema-builder/blob/main/ICONS.md) in the icons sets we have available. 

I guess the icon from the [wiki](https://wiki.openstreetmap.org/wiki/File:Milk_churn_stand.svg) could be added to [temaki](https://github.com/rapideditor/temaki) more or less as is… @b-unicycling  would you be able to do that or do you help with that?

**Comment by b-unicycling** [comment]
I haven't ever added an icon, but I can give it a try and cry for help, if I get stuck. Thanks!

**Comment by b-unicycling** [comment]
It worked once yesterday and then not again. Why would that be?

**Comment by tyrasd** [comment]
could it be that you used the test/preview instance (see https://github.com/openstreetmap/id-tagging-schema/pull/926#issuecomment-1598089509) yesterday? Because while the pull request is merged, the presets have not yet been [released](https://github.com/openstreetmap/id-tagging-schema/releases).

**Comment by b-unicycling** [comment]
It could indeed. It was late at night.--On 24/06/2023, 11:36 Martin Raifer ***@***.***> wrote:

   
  could it be that you used the test/preview instance (see #926 (comment)) yesterday? Because while the pull request is merged, the presets have not yet been released.

**Comment by b-unicycling** [comment]
The preset has been active in the iD editor for a few days now. I can't tell exactly since when, suddenly I just noticed it. THANK YOU very much to everyone involved for getting it this far.

The only question I have is: why does it work when I type "milk churn stand" and "creamery stand" and "Milchramp" (one of the German words short the final -e) into the search in the iD editor, but for example not the Finnish or Swedish word? Is there anything I can do to get other languages to work?

**Comment by tordans** [comment]
@b-unicycling the english terms need to be added to this list https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/man_made/milk_churn_stand.json#L10-L14 

The German terms (and any other language) need to be added via the translation tool.

More on this is explained in https://github.com/openstreetmap/id-tagging-schema/blob/main/CONTRIBUTING.md#translating

**Comment by b-unicycling** [comment]
> @b-unicycling the english terms need to be added to this list https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/man_made/milk_churn_stand.json#L10-L14
> 
> The German terms (and any other language) need to be added via the translation tool.
> 
> More on this is explained in https://github.com/openstreetmap/id-tagging-schema/blob/main/CONTRIBUTING.md#translating

Thanks, I think I figured it out and I've added a couple more languages from wikidata.
