### ISSUE TITLE
Allow selecting multiple genders for  shop=hairdresser

### ISSUE THREAD

**Issue by mnalis** [openstreetmap/id-tagging-schema#894]
### Description

Currently, for [shop=hairdresser](https://wiki.openstreetmap.org/wiki/Tag:shop=hairdresser), iD allows selecting **only one** of the gender values [male=*](https://wiki.openstreetmap.org/wiki/Key:male), [female=*](https://wiki.openstreetmap.org/wiki/Key:female) and [unisex=*](https://wiki.openstreetmap.org/wiki/Key:unisex), i.e. UI control is radio-button.

That however presents a problem when users try to edit objects that have more than one value set - most commonly combination of `male` + `female` tags, especially due to `unisex=*` ambiguity/controversy documented on its [wiki page](https://wiki.openstreetmap.org/wiki/Key:unisex) and related iD issues (like related https://github.com/openstreetmap/id-tagging-schema/issues/895 and https://github.com/openstreetmap/iD/issues/7427).

Request: It would be preferable if iD allowed entering all three gender keys (`male`, `female`, `unisex`) via  **checkboxes instead of radiobuttons** 

This is how most other popular editors do it (screenshots of JOSM and Vespucci attached). Current iD handling of that situation is very subtle, and unless user has display of raw tags displayed and uses that instead of user-friendly presets, is likely to result in _unintended_ modification / retagging / data loss  on edits. (see iD picture, in which iD would_ silently remove all gender tags except one that was selected via radio button_ if it were clicked on, regardless of their previous combinations/values)

### Screenshots

![josm](https://user-images.githubusercontent.com/156656/233216279-7679b2c8-c7e5-4445-bb57-a5481eba4a67.png)
![small_Screenshot_20230420_004438_de blau android](https://user-images.githubusercontent.com/156656/233216297-21262ef7-e313-4fec-8078-e3db8b391dcc.jpg)
![id](https://user-images.githubusercontent.com/156656/233217152-2ed8a7a6-5238-4a2e-b4d4-94abb2b8b7fd.png)

**Comment by tyrasd** [comment]
Fixed by switching the field to a `manyCombo`

![image](https://user-images.githubusercontent.com/1927298/235630136-2d846d55-b6f7-4adb-af24-e999230b9b6e.png)

Currently, this does not display mapped `no` values (e.g. `female=yes` + `male=no` would be displayed the same as `female=yes`), nor does it allow to explicitly map `no` states  in the UI. But this was also not possible before using the radio-button field.

I do plan to add support mapping of `no` values in iD in multiCombo/manyCombo fields, as this would also be useful in other scenarios.

**Comment by bhousel** [comment]
> Fixed by switching the field to the `manyCombo` type

Hey that is great!  I did not know about `manyCombo`.

**Comment by amandasaurus** [comment]
> I’ve never heard of a “unisex hairdresser”; I think one that serves both men and women would just be a hairdresser for men and women.

Pedantically, I [know of a hairdresser](https://www.unisex-friseure.de/) which tried to be “gender neutral”, rather than “men & women”. But your general point is correct. Unlike toilet (where “male & female” ≠ “unisex”), in the context of hairdressers, one can treat them mostly as the same.
