### ISSUE TITLE
Should `barrier=log` be allowed on standalone points?

### ISSUE THREAD

**Issue by Mahabarata** [openstreetmap/id-tagging-schema#898]
According to the wiki : https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dlog, this tag can be used on a node (currently 6 730 uses according to taginfo) or a way (2002 uses).

But, on iD editor, when it is used on a node, we have a warning telling us that this tag should be used only on ways.

Could you remove this warning ?

**Comment by matkoniecz** [comment]
is it possible that it is free-floating node but it should be attached to a path/road?

**Comment by tyrasd** [comment]
See https://github.com/openstreetmap/id-tagging-schema/pull/822#issuecomment-1477639549 and the following comment, as well as https://github.com/openstreetmap/id-tagging-schema/pull/506#issuecomment-1276003624. My interpretation of the tag (as documented on the wiki) is that it is only meant for logs which _block_ a path or similar object, thus the use as standalone points is not intended. Maybe I'm overlooking a valid use, though. Do you have any concrete examples of where it should be used?

**Comment by Mahabarata** [comment]
According to this query : https://overpass-turbo.eu/s/1uWC, there are currently 611 nodes (with this tag) not on a way.

I didn't look at all, some are probably misplaced (see node 422081105) but some other seems ok to me to explain a change in the direction of a way (with the node not on the way itself), see for example nodes 1729229124 or 539312449.

**Comment by matkoniecz** [comment]
> there are currently 611 nodes (with this tag) not on a way

note that most of them are node within a way - so will not raise this warning

**Comment by tyrasd** [comment]
>  explain a change in the direction of a way

This seems to be a good use of the tag, which I had overlooked. While not extremely common, it still makes up a not completely insignificant number of occurrences. I'll change the preset to also allow "standalone" `point` geometry. :+1: 

PS: The wiki also mentions the following use case for the tag:

> Logs may also be placed along highways or areas (similar to guard rails and fences). 

An example for this would be [n4405402004](https://www.openstreetmap.org/node/4405402004). Unfortunately, the current name of the preset _"Fallen Tree Obstruction"_ does not fit this situation very well, but I that's an issue for another ticket, I guess.

**Comment by Mahabarata** [comment]
Thanks
