### ISSUE TITLE
tag issue issue

### ISSUE THREAD

**Issue by Higuys153** [openstreetmap/id-tagging-schema#900]
this 
<img width="177" alt="Screenshot 2023-05-10 092523" src="https://github.com/openstreetmap/id-tagging-schema/assets/118638000/f1509e43-a2ea-47de-bfc8-1bf925559bca">
<img width="269" alt="Screenshot 2023-05-10 090828" src="https://github.com/openstreetmap/id-tagging-schema/assets/118638000/c81c816a-b070-4de6-9893-276de52375b1">

**Comment by Higuys153** [comment]
if this is the wrong place for this please tell me where i report this

**Comment by tyrasd** [comment]
This is actually a bug in iD which already has a fix: https://github.com/openstreetmap/iD/pull/9483

It will be soon be merged upstream and fix this issue. :bow:
