### ISSUE TITLE
man_made=watermill

### ISSUE THREAD

**Issue by tiptoptom** [openstreetmap/id-tagging-schema#906]
### OSM Tag(s)

man_made=watermill

### How would you like this tag to see supported?

As a Preset

### Label

watermill

### Link to OSM Wiki page

https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dwatermill

### Status of the Tag

Approved

### Usage of the tag

11,111

**Comment by tyrasd** [comment]
A preset for this tag already [exists](https://github.com/openstreetmap/id-tagging-schema/blob/v6.2.0/data/presets/man_made/watermill.json).

Did you encounter a situation where it didn't match a particular osm object with that tag?

**Comment by tyrasd** [comment]
I noticed that the preset was lacking fields (i.e. not even the `name` field was offered by default): I've added a couple in 75a8c9f8

**Comment by tiptoptom** [comment]
Ok, sorry. My mistake.
