### ISSUE TITLE
Change English text for Japanese address

### ISSUE THREAD

**Issue by ffff-23** [openstreetmap/id-tagging-schema#907]
The Japanese address policy was voted on and changed in Jun 2022.

I think it is appropriate to change English text of the address preset as follows.

neighbourhood!jp
`Chōme/Aza/Koaza` → `Machi/Chōme/Aza/Koaza`

quarter!jp
`Ōaza/Machi` → `Ōaza`

suburb!jp
`Ward` → `Ward (in ordinance-designated city)`

[Japan tagging](https://wiki.openstreetmap.org/wiki/Japan_tagging#Places)
[JA:Key:addr:*](https://wiki.openstreetmap.org/wiki/JA:Key:addr:*#日本の住所表記について)
[spreadsheet](https://docs.google.com/spreadsheets/d/1aOnXzGhZ8DYn0rSUXbT2C0JACesqfJbdpqiz2Jty8n0/edit#gid=0)

**Comment by tyrasd** [comment]
Hello. Thank you for the suggestions. I can change the labels immediately. Only the new label for `addr:suburb` would be quite a bit too long for the field currently:

![image](https://github.com/openstreetmap/id-tagging-schema/assets/1927298/a6623aa5-940f-45ba-b2f4-4096178afc66)

Is the added description (_in ordinance-designated city_) very important in this context? If yes, we'd need to tweak the field to either give it enough space to display the full description, or add a hover-text which shows the untruncated message.

**Comment by ffff-23** [comment]
Yes, it is important. I think the method using Japanese term is fine.

`Ward (政令市)`
