### ISSUE TITLE
 Cycle Crossing With Traffic Signals preset does not offer Crossing Markings field

### ISSUE THREAD

**Issue by RudyTheDev** [openstreetmap/id-tagging-schema#908]
"Cycle Crossing With Traffic Signals" line preset does not appear to offer the "Crossing Markings" field, even when `crossing:markings` are manually set. (This is in contrast to the footway "Crossing With Pedestrian Signals", which does offer it.) I assume it should offer it same as pedestrian one and same as other the "Marked" version.

iD 2.25.2

**Comment by tyrasd** [comment]
Yes, this was an oversight when the field was added. It was however already fixed a couple of days ago in 57fe16f29d598d8bef5486952f5be5dcb6cff8df and will be available with the next release of the tagging schema.
