### ISSUE TITLE
What does 🄿🄵🅅🄳 mean?

### ISSUE THREAD

**Issue by playgithub** [openstreetmap/id-tagging-schema#919]
in `dist/taginfo.json`

**Comment by arch0345** [comment]
🄿: [preset](https://github.com/openstreetmap/id-tagging-schema/tree/main/data/presets)
🄵: [field](https://github.com/openstreetmap/id-tagging-schema/tree/main/data/fields)
🄵🅅: field value
🄳: [deprecated tag](https://github.com/openstreetmap/id-tagging-schema/blob/main/data/deprecated.json)

**Comment by tordans** [comment]
I wonder, is this documented somewhere on the taginfo side? I only found https://wiki.openstreetmap.org/wiki/Taginfo/Projects and https://taginfo.openstreetmap.org/taginfo/projects which does not explain the file structure.

**Comment by playgithub** [comment]
Also https://wiki.openstreetmap.org/wiki/Map_features
BTW, I've searched for 🄿/🄵/🅅/🄳 in project `id-tagging-schema` and at wiki.openstreetmap.org, no explanation for that, so I ask here.

**Comment by 1ec5** [comment]
These mnemonics come from [schema-builder](https://github.com/ideditor/schema-builder/blob/8f6c4ee3b3f525892b33315e211fe925011b53e5/lib/build.js#L522).

I similarly put emoji into the Mapbox Navigation SDK for iOS project file but [added a decoder ring to the `description`](https://github.com/mapbox/mapbox-navigation-ios/blob/293621c5dfaf76d1a2cc70ada7e21846cb247de4/taginfo.json#L5). Consider requesting that change in schema-builder.

**Comment by tordans** [comment]
I think its worth documenting this somewhere since it in deed very cryptic when looking at taginfo only … so here we go, maybe this will help someone next time https://github.com/ideditor/schema-builder/pull/102
