### ISSUE TITLE
Add `shop=pasta`, shop focused on selling (fresh) pasta

### ISSUE THREAD

**Issue by Robot8A** [openstreetmap/id-tagging-schema#930]
### OSM Tag(s)

shop=pasta

### How would you like this tag to see supported?

As a Preset

### Label

Pasta Store

### Aliases

Fresh Pasta Shop

### Terms

ravioli, spaghetti

### Link to OSM Wiki page

https://wiki.openstreetmap.org/wiki/Tag:shop%3Dpasta

### Status of the Tag

In Use

### Usage of the tag

684

### Further Information

https://taginfo.openstreetmap.org/tags/shop=pasta#overview

**Comment by govvin** [comment]
@Robot8A , there's a draft PR #953 , and I'm wondering if you have any suggestions for a better icon?

**Comment by Robot8A** [comment]
I sent a mail to the Italian community to ask for their feedback https://lists.openstreetmap.org/pipermail/talk-it/2023-July/074863.html

**Comment by govvin** [comment]
Please have a look at this page: https://github.com/ideditor/schema-builder/blob/main/ICONS.md, for additional information about icons.

**Comment by Robot8A** [comment]
For me personally I am ok with the icon you chose. Let's see if someone else has an opinion about it.

**Comment by govvin** [comment]
@Robot8A , please feel free to review #953 . It's no longer in draft mode.

**Comment by tyrasd** [comment]
the preset was added in #953, thank you!
