### ISSUE TITLE
Add `indoor` field to `amenity=parcel_locker`

### ISSUE THREAD

**Issue by Dimitar5555** [openstreetmap/id-tagging-schema#940]
### OSM Tag(s)

indoor

### How would you like this tag to see supported?

As a Field

### Label

Indoor

### Link to OSM Wiki page

https://wiki.openstreetmap.org/wiki/Key:indoor

### Status of the Tag

De Facto

### Usage of the tag

508k

### Replaces other Tag?

no

### Further Information

A simple unknown/yes/no field should work fine.

**Comment by kjonosm** [comment]
Should we use `location=indoor` or `indoor=yes`?

**Comment by Dimitar5555** [comment]
`location` seems to be used mainly on power related features.
