### ISSUE TITLE
Use established tag for 'barbecue'

### ISSUE THREAD

**Issue by bikeoid** [openstreetmap/id-tagging-schema#943]
**Describe the bug**
  When doing a feature search in ID for a type of barbecue restaurant, ID suggests "Barbeque Restaurant", which applies a tag cuisine=barbeque.   Although this is an accepted spelling in the English language, the established tag is cuisine=barbecue.
  

**To Reproduce**
1. Select a feature and search for 'barbe'

**Expected behavior**
 Should suggest Barbecue Restaurant

**Screenshots**
![image](https://github.com/openstreetmap/id-tagging-schema/assets/75929/941ea9eb-4735-4b2d-98de-46a50b46845c)

**Additional context**
Established tag in Wiki for cuisine https://wiki.openstreetmap.org/wiki/Key:cuisine#Style_or_Place

**Comment by 1ec5** [comment]
The preset’s name, “Barbeque Restaurant”, is also inconsistent with another barbecue preset:

https://github.com/openstreetmap/id-tagging-schema/blob/2a7faa922a7593b1530c8b577c1e527fa6d85460/data/presets/amenity/bbq.json#L22

[Wiktionary](https://en.wiktionary.org/wiki/barbeque#English) says “barbeque” is the Australian English and New Zealand English spelling. American English uses “barbecue” even though it’s abbreviated as “BBQ”.

**Comment by tyrasd** [comment]
It should now be consistent after changing the spelling of the preset name in 9c753cc5045e6edc568eed08cc6c54193558088a
