### ISSUE TITLE
Say "Elevation (meters)", not just Elevation

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/id-tagging-schema#95]
Here we see `Height (meters)`,

![20201209T222535](https://user-images.githubusercontent.com/1230959/101642254-bfe16c80-3a6d-11eb-91f2-3954ec9fc48f.jpg)

But no
`Elevation (meters)`
just
`Elevation`.
If we want to know the units, we have to click on its "i". It's "just not fair."

**Comment by 1ec5** [comment]
[This proposal](https://wiki.openstreetmap.org/wiki/Proposed_features/ele_with_units) would require us to hedge a bit: either remove “Meters” from the field name, or create a separate “Elevation (Feet)” field for use in the United States, or ideally implement a proper measurement field type that won’t require a gloss in the field name: ideditor/schema-builder#15.
