### ISSUE TITLE
Validator: building:levels vs building:level

### ISSUE THREAD

**Issue by sun-geo** [openstreetmap/id-tagging-schema#96]
Seems tags with key `building:level` are typos of `building:levels` and iD could inform the mappers to use `building:levels` instead.

Wiki `building:levels`: https://wiki.openstreetmap.org/wiki/Key:building:levels

Taghistory `building:level`: http://taghistory.raifer.tech/#***/building:level

**Comment by quincylvania** [comment]
Browsing around overpass, it does look like people meant to use `building:levels`. I'm not sure how so many typos got into OSM, but at least iD can help here.

![Screen Shot 2020-12-15 at 9 57 51 AM](https://user-images.githubusercontent.com/2046746/102231632-2a563a80-3ebc-11eb-9d49-36c217f187d6.png)
