### ISSUE TITLE
consider supporting shop=gold_buyer

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/id-tagging-schema#974]
### OSM Tag(s)

shop=gold_buyer

### How would you like this tag to see supported?

As a Preset

### Label

Gold buyer

### Aliases

Gold trader

### Link to OSM Wiki page

https://wiki.openstreetmap.org/wiki/Tag:shop%3Dgold_buyer

### Status of the Tag

In Use

### Usage of the tag

>200

### Replaces other Tag?

no

### Regional Tag?

global

### Further Information

part of #362 (sync NSI tags), but makes sense in general

**Comment by tyrasd** [comment]
usage (~240 features) is still(?) surprisingly low, but I agree that adding a preset for these businesses would make sense.

**Comment by andrewpmk** [comment]
Most of these are tagged as shop=pawnbroker I think.
