### ISSUE TITLE
Add preset for amenity=baking_oven

### ISSUE THREAD

**Issue by AntMadeira** [openstreetmap/id-tagging-schema#975]
### OSM Tag(s)

amenity=baking_oven

### How would you like this tag to see supported?

As a Preset

### Label

Baking Oven

### Link to OSM Wiki page

https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbaking_oven

### Status of the Tag

Approved

### Usage of the tag

752

### Further Information

Hi there.
I would like to request the addition of this preset to iD pluss the oven=* field.

Regards.

**Comment by N-45div** [comment]
@tyrasd sir can you please check the pull request and tell me any changes required

**Comment by N-45div** [comment]
@tyrasd sir i have made the necessary changes please check it...Thank You

**Comment by qugebert** [comment]
I think this can be closed as completed in #983
