### ISSUE TITLE
Add preset for `man_made=satelite_dish`

### ISSUE THREAD

**Issue by Dimitar5555** [openstreetmap/id-tagging-schema#976]
### OSM Tag(s)

man_made=satelite_dish

### How would you like this tag to see supported?

As a Preset

### Label

Satelite Dish

### Link to OSM Wiki page

https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dsatellite_dish

### Status of the Tag

In Use

### Usage of the tag

2 087

### Further Information

It would be nice if it also has `diameter` field.

**Comment by N-45div** [comment]
@Dimitar5555 Can you please review the preset added in the man_made group it has been committed in my fork repo it is referencing above...

**Comment by Dimitar5555** [comment]
Thank you @N-45div! It looks good to me.
