### ISSUE TITLE
leisure=indoor_play

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/id-tagging-schema#98]
From latest NSI build dist:
- Warning - no iD source preset found for brands/leisure/indoor_play

https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dindoor_play

We picked this up because someone added an item for "wacky warehouse"
https://nsi.guide/index.html?t=brands&k=leisure&v=indoor_play

**Comment by quincylvania** [comment]
I added this preset as "Indoor Play Center". I also added "Indoor Playground" for `leisure=playground` + `indoor=yes` (e.g. at some McDonald's), since I expect some people might mistag those as play centers if that's the preset they see.

**Comment by maro-21** [comment]
Could you tell me why do we need two presets/tags for the same? I see no difference.

**Comment by bhousel** [comment]
> Could you tell me why do we need two presets/tags for the same? I see no difference.

They are really different
- `leisure=indoor_play` is a business that hosts parties and runs classes for little kids
- `leisure=playground` + `indoor=yes` is just an indoor playground
