### ISSUE TITLE
Mountain Bike (MTB) routes in Relationships

### ISSUE THREAD

**Issue by michaelblyons** [openstreetmap/id-tagging-schema#99]
I would like an option for [`route=mtb`](https://wiki.openstreetmap.org/wiki/Tag%3Aroute%3Dmtb) when I create a new relation. Right now, I choose "Bicycle Route" and fiddle with it.

Perhaps more significantly, I'd like `route=mtb` to be a recognized concept in the link-to-existing-relationship autocomplete box. Hiking/Cycling/Horseback/(Walking?) have special handling that puts the route type before the word "Route" in the box. This would be helpful for MTB as well, particularly when there are multiple transit modes sharing the same name in the same area.

On a related note: Can you change the prefix for horseback routes to "Horse" instead of "Riding?" There are lots of things one could ride (bicycle, bus, etc.), and a bunch of them have dedicated `route` values. It would be easy for someone unfamiliar with OSM to link a bike path to a horse relationship in places with segregated paths.

**Comment by michaelblyons** [comment]
**Wow,** that was quick! 🚀 Thank you!

**Comment by quincylvania** [comment]
@michaelblyons Thanks for the suggestion, I hadn't realized that `route=mtb` had so much usage.

> Hiking/Cycling/Horseback/(Walking?) have special handling that puts the route type before the word "Route" in the box.

I'm not entirely sure what you mean, but I think this functionality might come for free via the preset.

**Comment by michaelblyons** [comment]
I think it does come free, now that I've compared your `horse` change to the new `mtb` change. I thought "Riding" was a prefix to "Route" rather than the a replacement of the default ("Route") with the `name` of the preset.

<img width="374" alt="Screen Shot 2020-12-21 at 10 14 40 AM" src="https://user-images.githubusercontent.com/2701605/102791913-9d215300-439f-11eb-90ee-66fe29dabe44.png">

Thanks again. This will be a great help.
